import Foundation
import simd

/// Surface color kernel — the hand-written SIMD Swift port of the Zig core's
/// `s4_palette_oklab_to_srgb8` (Native/src/kernels.zig:982). Maps a Q16 OKLab
/// triple `(L, a, b)` to an sRGB8 triple `(r, g, b)` using the EXACT
/// fixed-point integer ladder — no floating point in the math path:
///
///   1. M2⁻¹ matmul   (OKLab → l'm's', Q16)
///   2. exact integer cube  (l'm's' → lms, Q16:  v³ / 2³²)
///   3. M1⁻¹ matmul   (lms → linear sRGB, Q16)
///   4. gamma LUT lookup  (Q16 linear ∈ [0,65536] → sRGB8 byte)
///
/// The integer literals are the SAME ones used by both the Zig core and
/// `SixFour.Spec.ColorFixed.oklabToSrgb8Q16`, so the three implementations
/// agree byte-for-byte. The inverse-gamma transcendental is evaluated once,
/// offline, into `gamma_lut.bin` (65537 bytes, generated by `spec-fixtures`);
/// this kernel only indexes it, so it stays float-free and deterministic on
/// every device.
public enum SurfaceColor {

    // MARK: - Fixed-point constants (mirror kernels.zig / ColorFixed.hs)

    /// Q16 fixed-point unit (1.0).
    @usableFromInline static let q16: Int64 = 1 << 16

    // M2⁻¹ (OKLab → l'm's'): the a,b coefficients added to L, Q16.
    @usableFromInline static let m2iLA: Int64 = 25974
    @usableFromInline static let m2iLB: Int64 = 14143
    @usableFromInline static let m2iMA: Int64 = -6918
    @usableFromInline static let m2iMB: Int64 = -4185
    @usableFromInline static let m2iSA: Int64 = -5864
    @usableFromInline static let m2iSB: Int64 = -84639

    // M1⁻¹ (LMS → linear sRGB), Q16, row-major.
    @usableFromInline static let m1inv: [Int64] =
        [267173, -216774, 15137, -83128, 171033, -22369, -275, -46099, 111910]

    // MARK: - Gamma LUT

    /// The shared inverse-gamma table (65537 bytes), loaded once from the app
    /// bundle. Index = clamped Q16 linear ∈ [0, 65536]; value = round(255·sRGB).
    /// Byte-identical to the Zig core's `@embedFile`d `gamma_lut.bin` and to
    /// `SixFour.Spec.ColorFixed.gammaLut`.
    public static let gammaLut: [UInt8] = loadGammaLut()

    private static func loadGammaLut(bundle: Bundle = .main) -> [UInt8] {
        guard let url = bundle.url(forResource: "gamma_lut", withExtension: "bin"),
              let data = try? Data(contentsOf: url),
              data.count == 65537
        else {
            // The resource is part of the shipped bundle; absence is a build
            // misconfiguration, not a runtime condition. Fall back to an
            // all-zero table so the type stays total (callers get black).
            return [UInt8](repeating: 0, count: 65537)
        }
        return Array(data)
    }

    // MARK: - Scalar ladder

    /// `(v/2^16)^3` in Q16 = `v³ / 2³²`, truncating toward zero (sign-correct),
    /// matching Zig `cubeQ16` and Haskell `cubeQ16`.
    @inline(__always)
    static func cubeQ16(_ v: Int64) -> Int64 {
        (v &* v &* v) / 4_294_967_296
    }

    /// Clamp a Q16 linear value into the LUT's valid index range and read the
    /// gamma byte. Mirrors Zig `gammaByte` / Haskell `gammaByte`.
    @inline(__always)
    static func gammaByte(_ lin: Int64, _ lut: [UInt8]) -> UInt8 {
        let idx = lin < 0 ? 0 : (lin > 65536 ? 65536 : Int(lin))
        return lut[idx]
    }

    /// One Q16 OKLab triple `(L, a, b)` → sRGB8 `(r, g, b)`. Byte-for-byte
    /// identical to `s4_palette_oklab_to_srgb8` for a single centroid.
    @inline(__always)
    public static func oklabQ16ToSrgb8(_ lab: SIMD3<Int32>) -> SIMD3<UInt8> {
        oklabQ16ToSrgb8(lab, lut: gammaLut)
    }

    /// LUT-injectable variant (for tests / explicit-bundle callers).
    @inline(__always)
    public static func oklabQ16ToSrgb8(_ lab: SIMD3<Int32>, lut: [UInt8]) -> SIMD3<UInt8> {
        let bigL = Int64(lab.x)
        let a = Int64(lab.y)
        let b = Int64(lab.z)

        // 1. M2⁻¹: l'm's' (note the L coefficient is exactly q16, so the
        //    `q16 * bigL` term reproduces Zig's `@divTrunc(q16*L + …, q16)`).
        let lP = (q16 &* bigL &+ m2iLA &* a &+ m2iLB &* b) / q16
        let mP = (q16 &* bigL &+ m2iMA &* a &+ m2iMB &* b) / q16
        let sP = (q16 &* bigL &+ m2iSA &* a &+ m2iSB &* b) / q16

        // 2. exact integer cube
        let l = cubeQ16(lP)
        let m = cubeQ16(mP)
        let s = cubeQ16(sP)

        // 3. M1⁻¹: linear sRGB
        let r = (m1inv[0] &* l &+ m1inv[1] &* m &+ m1inv[2] &* s) / q16
        let g = (m1inv[3] &* l &+ m1inv[4] &* m &+ m1inv[5] &* s) / q16
        let bl = (m1inv[6] &* l &+ m1inv[7] &* m &+ m1inv[8] &* s) / q16

        // 4. gamma LUT
        return SIMD3<UInt8>(gammaByte(r, lut), gammaByte(g, lut), gammaByte(bl, lut))
    }

    // MARK: - Batched SIMD variant

    /// Map a whole palette of Q16 OKLab centroids to sRGB8. Loads the gamma
    /// LUT once and reuses it across the batch.
    public static func oklabQ16ToSrgb8(_ labs: [SIMD3<Int32>]) -> [SIMD3<UInt8>] {
        let lut = gammaLut
        var out = [SIMD3<UInt8>](repeating: SIMD3<UInt8>(0, 0, 0), count: labs.count)
        for i in labs.indices {
            out[i] = oklabQ16ToSrgb8(labs[i], lut: lut)
        }
        return out
    }
}
