//  KernelsColor.swift
//  Swift port of the color/LUT section of Native/src/kernels.zig (2026-07-06);
//  byte-exact twin, golden-gated.
//
//  Exported kernels (C names preserved via @_cdecl, signatures per
//  Native/include/sixfour_native.h):
//    s4_linear_to_oklab_q16, s4_palette_oklab_to_srgb8, s4_srgb8_to_oklab_q16,
//    s4_zone_profile_q16, s4_look_transfer_q16, s4_build_cube_q16.
//
//  NOT here (they live in Native/src/palette16.zig — another port slice):
//    s4_srgb8_to_linear16, s4_linear16_to_srgb8, s4_hlg10_to_linear16.
//
//  LUT access: kernels.zig @embedFile's five .bin goldens. This port reads the
//  byte-identical [UInt8] arrays in KernelsLUTData.swift. Where Zig reinterprets
//  the bytes as i32 tables (std.mem.readInt(i32, …, .little)), the typed tables
//  below are built ONCE with the same explicit little-endian byte composition
//  (b0 | b1<<8 | b2<<16 | b3<<24, then Int32(bitPattern:)) — determinism first.
//
//  Integer semantics follow the KernelsCore.swift dictionary: Zig trapping
//  +/-/* → Swift trapping +/-/*; @divTrunc → Swift `/` (truncates toward zero);
//  @intCast → trapping numeric init; i64 widenings replicated exactly.

// ── return codes (kernels.zig RC_* — private copies per port convention) ─────
private let rcOK: Int32 = 0
private let rcNullPtr: Int32 = 1
private let rcBadShape: Int32 = 2
private let rcScratchTooSmall: Int32 = 3
private let rcOutputTooSmall: Int32 = 4
private let rcInfeasibleSignificance: Int32 = 5
private let rcBadDitherMode: Int32 = 6
private let rcOutOfRange: Int32 = 7
private let rcNotImplemented: Int32 = 100

/// Q16 unit as the i64 the arithmetic runs in (kernels.zig `Q16_ONE` widened).
private let q16One64: Int64 = 1 << 16

// ── Embedded LUT reinterpretation (the @embedFile / bytesAsSlice twin) ───────

/// Compose a little-endian i32 table from raw golden bytes — the exact
/// semantics of Zig `std.mem.readInt(i32, lut[i*4..][0..4], .little)`.
private func s4I32TableLE(_ bytes: [UInt8], expectedBytes: Int, name: StaticString) -> [Int32] {
    precondition(bytes.count == expectedBytes, "\(name): embedded LUT byte-count mismatch")
    var out = [Int32]()
    out.reserveCapacity(bytes.count / 4)
    var i = 0
    while i < bytes.count {
        let u = UInt32(bytes[i])
            | (UInt32(bytes[i + 1]) << 8)
            | (UInt32(bytes[i + 2]) << 16)
            | (UInt32(bytes[i + 3]) << 24)
        out.append(Int32(bitPattern: u))
        i += 4
    }
    return out
}

/// The shared inverse-gamma LUT, generated by `spec-fixtures` from the Double
/// linearToSRGB and embedded byte-for-byte. Index = clamped Q16 linear ∈ [0,65536];
/// value = round(255·sRGB). Deterministic on every device — no runtime pow.
/// (Zig: GAMMA_LUT = @embedFile("gamma_lut.bin"), 65537 raw bytes — used as u8
/// directly, no reinterpretation.)
private let colorGammaLut: [UInt8] = {
    precondition(s4LutGamma.count == 65537, "gamma_lut.bin must be 65537 bytes; run `cd spec && cabal run spec-fixtures`")
    return s4LutGamma
}()

/// Embedded sRGB→linear LUT: 256 little-endian i32 of round(srgbToLinear(b/255)·2^16),
/// emitted by spec/app/Fixtures.hs from the SAME SixFour.Spec.Color.srgbToLinear, so
/// Swift and Haskell agree byte-for-byte. Inverse of the forward gamma path.
private let colorSrgbLinearLut: [Int32] =
    s4I32TableLE(s4LutSrgbLinear, expectedBytes: 1024, name: "srgb_linear_lut.bin")

// The transcendentals (Log3G10 decode, filmic exp) + the Q16 sRGB-encode output
// gamma are 1-D LUTs generated by spec/app/Fixtures.hs and embedded (the
// gamma_lut.bin pattern), so the whole path is integer-exact. 65537 i32 each.
private let colorLog3g10DecodeLut: [Int32] =
    s4I32TableLE(s4LutLog3g10Decode, expectedBytes: 65537 * 4, name: "log3g10_decode_lut.bin")
private let colorFilmicTonemapLut: [Int32] =
    s4I32TableLE(s4LutFilmicTonemap, expectedBytes: 65537 * 4, name: "filmic_tonemap_lut.bin")
private let colorSrgbEncodeLut: [Int32] =
    s4I32TableLE(s4LutSrgbEncode, expectedBytes: 65537 * 4, name: "srgb_encode_lut.bin")

// ── Fixed-point color constants (kernels.zig, byte-exact literals) ───────────

// Ottosson M1 (linear sRGB→LMS) and M2 (LMS'→OKLab), Q16, row-major. These are
// the SAME integer literals as SixFour.Spec.ColorFixed — the byte-exact contract.
private let m1Q16: [Int64] = [27015, 35149, 3372, 13887, 44610, 7038, 5787, 18463, 41286]
private let m2Q16: [Int64] = [13792, 52011, -267, 129630, -159160, 29530, 1698, 51300, -52997]

// Inverse matrices, Q16 — SAME integer literals as SixFour.Spec.ColorFixed.
// M2⁻¹ (OKLab→l'm's'): the a,b coefficients added to L.
private let m2iLA: Int64 = 25974
private let m2iLB: Int64 = 14143
private let m2iMA: Int64 = -6918
private let m2iMB: Int64 = -4185
private let m2iSA: Int64 = -5864
private let m2iSB: Int64 = -84639
// M1⁻¹ (LMS→linear sRGB), row-major.
private let m1InvQ16: [Int64] = [267173, -216774, 15137, -83128, 171033, -22369, -275, -46099, 111910]

private let lutN: Int64 = 65536 // == Q16_ONE: the decode LUT is indexed directly by the Q16 encoded value
private let filmicXMaxQ16: Int64 = 1048576 // = 16·65536 — MUST equal SixFour.Spec.RedFrontEnd.filmicXMaxQ16
private let blackLiftQ16: Int64 = 524 // round(0.008·65536)
private let minZonePop: Int64 = 1 // a 256-entry palette: any colour in a zone is signal (not python's >10)

// RWG → Rec.709, nine Q16 constants from the COMPOSED Double matrix — the SAME
// literals as SixFour.Spec.RedFrontEnd.rwgToRec709Q16 (row-major).
private let rwgToRec709Q16: [Int64] = [129870, -59001, -5343, -11675, 98337, -21124, -6673, -35087, 107312]
// Rec.709 luminance weights, Q16 (round(0.2126/0.7152/0.0722·65536)).
private let rec709LumaQ16: [Int64] = [13933, 46871, 4732]

// ── Private helpers (kernels.zig fn twins; parallel slices may duplicate) ────

/// Clamp an intermediate LMS value to the domain icbrtQ16 stays exact on
/// (kernels.zig `clampPosOklab`): linear ≤ 2.0 keeps icbrt inside i64.
@inline(__always)
private func clampPosOklab(_ v: Int64) -> Int64 {
    if v < 0 { return 0 }
    if v > 131072 { return 131072 }
    return v
}

/// Exact integer floor cube root in Q16: floor(cbrt(x/2^16) * 2^16), i.e. the
/// largest Y with Y³ ≤ x·2^32. Pure integer binary search — bit-for-bit
/// identical to SixFour.Spec.ColorFixed.icbrtQ16. x is clamped to [0, 131072]
/// so x·2^32 ≤ 2^49 and every mid³ ≤ 2^51 stays inside i64 (Swift traps too).
private func icbrtQ16(_ xIn: Int64) -> Int64 {
    if xIn <= 0 { return 0 }
    let x: Int64 = xIn > 131072 ? 131072 : xIn
    let n: Int64 = x << 32
    var lo: Int64 = 0
    var hi: Int64 = 1 << 17
    while lo < hi {
        let mid = (lo + hi + 1) / 2
        if mid * mid * mid <= n {
            lo = mid
        } else {
            hi = mid - 1
        }
    }
    return lo
}

/// (v/2^16)^3 in Q16 = v^3 / 2^32 (kernels.zig `cubeQ16`).
@inline(__always)
private func cubeQ16(_ v: Int64) -> Int64 {
    return (v * v * v) / 4294967296
}

/// Inverse-gamma LUT sample: clamped Q16 linear → sRGB byte (kernels.zig `gammaByte`).
@inline(__always)
private func gammaByte(_ lin: Int64) -> UInt8 {
    let idx: Int64 = lin < 0 ? 0 : (lin > 65536 ? 65536 : lin)
    return colorGammaLut[Int(idx)]
}

/// sRGB byte → Q16 linear via the embedded 256-entry i32 LUT (kernels.zig `srgbLinLut`).
@inline(__always)
private func srgbLinLut(_ b: UInt8) -> Int32 {
    return colorSrgbLinearLut[Int(b)]
}

/// Exact integer floor sqrt: largest Y with Y² ≤ n. Mirrors
/// SixFour.Spec.ColorFixed.isqrtFloor. n ≤ 2^40 (OKLab Q16 sum-of-squares) so
/// mid² ≤ 2^40 stays in i64 (Swift traps overflow too).
private func isqrtFloor(_ n: Int64) -> Int64 {
    if n <= 0 { return 0 }
    var lo: Int64 = 0
    var hi: Int64 = 1 << 20
    while lo < hi {
        let mid = (lo + hi + 1) / 2
        if mid * mid <= n {
            lo = mid
        } else {
            hi = mid - 1
        }
    }
    return lo
}

/// OKLab chroma magnitude in Q16 (the Q16 scale cancels): √(a²+b²).
@inline(__always)
private func chromaQ16Native(_ a: Int64, _ b: Int64) -> Int64 {
    return isqrtFloor(a * a + b * b)
}

// ── RED front-end (SixFour.Spec.RedFrontEnd) ─────────────────────────────────

@inline(__always)
private func log3g10DecodeSample(_ v: Int64) -> Int64 {
    let idx: Int64 = v < 0 ? 0 : (v > lutN ? lutN : v)
    return Int64(colorLog3g10DecodeLut[Int(idx)])
}

@inline(__always)
private func filmicTonemapSample(_ x: Int64) -> Int64 {
    if x <= 0 { return 0 }
    let raw = (x * lutN) / filmicXMaxQ16
    let idx: Int64 = raw > lutN ? lutN : raw
    return Int64(colorFilmicTonemapLut[Int(idx)])
}

@inline(__always)
private func srgbEncodeSample(_ lin: Int64) -> Int64 {
    let idx: Int64 = lin < 0 ? 0 : (lin > lutN ? lutN : lin)
    return Int64(colorSrgbEncodeLut[Int(idx)])
}

/// One Q16 RWG/Log3G10 grid coordinate → tonemapped linear Rec.709 Q16: decode →
/// matrix → clip negatives → filmic tonemap.
private func redDecodeToLinear(_ vr: Int64, _ vg: Int64, _ vb: Int64) -> (Int64, Int64, Int64) {
    let q16 = q16One64
    let lr = log3g10DecodeSample(vr)
    let lg = log3g10DecodeSample(vg)
    let lb = log3g10DecodeSample(vb)
    let m = rwgToRec709Q16
    let r0 = (m[0] * lr + m[1] * lg + m[2] * lb) / q16
    let g0 = (m[3] * lr + m[4] * lg + m[5] * lb) / q16
    let b0 = (m[6] * lr + m[7] * lg + m[8] * lb) / q16
    return (
        filmicTonemapSample(max(0, r0)),
        filmicTonemapSample(max(0, g0)),
        filmicTonemapSample(max(0, b0))
    )
}

@inline(__always)
private func gamutScaleFor(_ dev: Int64, _ y: Int64) -> Int64 {
    let q16 = q16One64
    if dev > 0 { return ((q16 - y) * q16) / dev }
    if dev < 0 { return (y * q16) / (-dev) }
    return q16
}

@inline(__always)
private func gamutOut(_ y: Int64, _ dev: Int64, _ sc: Int64) -> Int64 {
    let q16 = q16One64
    let v = y + (dev * sc) / q16
    return max(0, min(q16, v))
}

/// Luminance-preserving gamut compression on linear Rec.709 Q16. In-gamut input
/// is an exact fixed point.
private func gamutCompress(_ rgb: (Int64, Int64, Int64)) -> (Int64, Int64, Int64) {
    let q16 = q16One64
    let (r, g, b) = rgb
    let yRaw = (rec709LumaQ16[0] * r + rec709LumaQ16[1] * g + rec709LumaQ16[2] * b) / q16
    let y = max(1, yRaw)
    let devR = r - y
    let devG = g - y
    let devB = b - y
    var sc: Int64 = q16
    sc = min(sc, gamutScaleFor(devR, y))
    sc = min(sc, gamutScaleFor(devG, y))
    sc = min(sc, gamutScaleFor(devB, y))
    sc = max(0, min(q16, sc))
    return (gamutOut(y, devR, sc), gamutOut(y, devG, sc), gamutOut(y, devB, sc))
}

/// Black lift on linear Rec.709 Q16: out = lift + v·(1−lift). Before gamut compress.
private func applyBlackLift(_ rgb: (Int64, Int64, Int64)) -> (Int64, Int64, Int64) {
    @inline(__always)
    func lift(_ v: Int64) -> Int64 {
        return blackLiftQ16 + (v * (q16One64 - blackLiftQ16)) / q16One64
    }
    return (lift(rgb.0), lift(rgb.1), lift(rgb.2))
}

// ── OKLab forward/inverse single-triple helpers (reuse the existing matrices) ─

@inline(__always)
private func linToOklab1(_ r0: Int64, _ g0: Int64, _ b0: Int64) -> (Int64, Int64, Int64) {
    let q16 = q16One64
    let r = max(0, r0)
    let g = max(0, g0)
    let b = max(0, b0)
    let l = clampPosOklab((m1Q16[0] * r + m1Q16[1] * g + m1Q16[2] * b) / q16)
    let m = clampPosOklab((m1Q16[3] * r + m1Q16[4] * g + m1Q16[5] * b) / q16)
    let s = clampPosOklab((m1Q16[6] * r + m1Q16[7] * g + m1Q16[8] * b) / q16)
    let lc = icbrtQ16(l)
    let mc = icbrtQ16(m)
    let sc = icbrtQ16(s)
    return (
        (m2Q16[0] * lc + m2Q16[1] * mc + m2Q16[2] * sc) / q16,
        (m2Q16[3] * lc + m2Q16[4] * mc + m2Q16[5] * sc) / q16,
        (m2Q16[6] * lc + m2Q16[7] * mc + m2Q16[8] * sc) / q16
    )
}

@inline(__always)
private func oklabToLin1(_ bigL: Int64, _ a: Int64, _ b: Int64) -> (Int64, Int64, Int64) {
    let q16 = q16One64
    let l_ = (q16 * bigL + m2iLA * a + m2iLB * b) / q16
    let m_ = (q16 * bigL + m2iMA * a + m2iMB * b) / q16
    let s_ = (q16 * bigL + m2iSA * a + m2iSB * b) / q16
    let l = cubeQ16(l_)
    let m = cubeQ16(m_)
    let s = cubeQ16(s_)
    return (
        (m1InvQ16[0] * l + m1InvQ16[1] * m + m1InvQ16[2] * s) / q16,
        (m1InvQ16[3] * l + m1InvQ16[4] * m + m1InvQ16[5] * s) / q16,
        (m1InvQ16[6] * l + m1InvQ16[7] * m + m1InvQ16[8] * s) / q16
    )
}

// ── ZoneProfile + LookTransfer (SixFour.Spec.{ZoneProfile,LookTransfer}) ──────

@inline(__always)
private func zoneCenterL(_ nz: Int64, _ z: Int64) -> Int64 {
    return ((2 * z + 1) * q16One64) / (2 * nz)
}

/// Piecewise-linear sample of the (a,b,chroma) target at lightness l, clamping at
/// the end zones. Mirrors SixFour.Spec.ZoneProfile.sampleZoneTargetQ16.
private func sampleZoneTarget(
    _ meanA: UnsafePointer<Int32>,
    _ meanB: UnsafePointer<Int32>,
    _ meanC: UnsafePointer<Int32>,
    _ nz: Int64,
    _ l: Int64
) -> (Int64, Int64, Int64) {
    if nz <= 1 || l <= zoneCenterL(nz, 0) {
        return (Int64(meanA[0]), Int64(meanB[0]), Int64(meanC[0]))
    }
    if l >= zoneCenterL(nz, nz - 1) {
        let last = Int(nz - 1)
        return (Int64(meanA[last]), Int64(meanB[last]), Int64(meanC[last]))
    }
    var z: Int64 = 0
    while z < nz - 2 && l >= zoneCenterL(nz, z + 1) { z += 1 }
    let q16 = q16One64
    let lo = zoneCenterL(nz, z)
    let hi = zoneCenterL(nz, z + 1)
    let frac: Int64 = hi > lo ? ((l - lo) * q16) / (hi - lo) : 0
    @inline(__always)
    func lerp(_ v0: Int64, _ v1: Int64, _ fr: Int64) -> Int64 {
        return v0 + ((v1 - v0) * fr) / q16One64
    }
    let zi = Int(z)
    return (
        lerp(Int64(meanA[zi]), Int64(meanA[zi + 1]), frac),
        lerp(Int64(meanB[zi]), Int64(meanB[zi + 1]), frac),
        lerp(Int64(meanC[zi]), Int64(meanC[zi + 1]), frac)
    )
}

/// The chrominance-only look transform on one OKLab Q16 colour. KEEPS l. Mirrors
/// SixFour.Spec.LookTransfer.transferOklabQ16 byte-for-byte.
private func transferOklab(
    _ l: Int64,
    _ a: Int64,
    _ b: Int64,
    _ meanA: UnsafePointer<Int32>,
    _ meanB: UnsafePointer<Int32>,
    _ meanC: UnsafePointer<Int32>,
    _ nz: Int64,
    _ strength: Int64,
    _ chromaMin: Int64,
    _ chromaMax: Int64,
    _ polarity: Int64,
    _ chromaEps: Int64
) -> (Int64, Int64, Int64) {
    let q16 = q16One64
    let t = sampleZoneTarget(meanA, meanB, meanC, nz, l)
    let targetC = t.2
    let ta = (t.0 * polarity) / q16
    let tb = (t.1 * polarity) / q16
    let aOut0 = (a * (q16 - strength) + ta * strength) / q16
    let bOut0 = (b * (q16 - strength) + tb * strength) / q16
    let curC = chromaQ16Native(aOut0, bOut0)
    let inC = chromaQ16Native(a, b)
    let cTargetBlended = (inC * (q16 - strength) + targetC * strength) / q16
    if curC < chromaEps {
        let dirC = chromaQ16Native(ta, tb)
        let safeDir = max(1, dirC)
        return (l, (ta * cTargetBlended) / safeDir, (tb * cTargetBlended) / safeDir)
    }
    let safeC = max(1, curC)
    let rawScale = (cTargetBlended * q16) / safeC
    let cScale = max(chromaMin, min(chromaMax, rawScale))
    return (l, (aOut0 * cScale) / q16, (bOut0 * cScale) / q16)
}

@inline(__always)
private func gridCoord(_ i: Int64, _ n: Int64) -> Int64 {
    if n <= 1 { return 0 }
    return (i * q16One64) / (n - 1)
}

/// One cube voxel: grid coord → RED front-end → OKLab → look transfer → linear →
/// black lift → gamut compress → sRGB-encode (Q16). Mirrors
/// SixFour.Spec.CubeLut.cubeVoxelQ16.
private func cubeVoxel(
    _ ri: Int64,
    _ gi: Int64,
    _ bi: Int64,
    _ n: Int64,
    _ meanA: UnsafePointer<Int32>,
    _ meanB: UnsafePointer<Int32>,
    _ meanC: UnsafePointer<Int32>,
    _ nz: Int64,
    _ strength: Int64,
    _ chromaMin: Int64,
    _ chromaMax: Int64,
    _ polarity: Int64,
    _ chromaEps: Int64
) -> (Int64, Int64, Int64) {
    let lin = redDecodeToLinear(gridCoord(ri, n), gridCoord(gi, n), gridCoord(bi, n))
    let oklab = linToOklab1(lin.0, lin.1, lin.2)
    let graded = transferOklab(oklab.0, oklab.1, oklab.2, meanA, meanB, meanC, nz, strength, chromaMin, chromaMax, polarity, chromaEps)
    let linOut = oklabToLin1(graded.0, graded.1, graded.2)
    let comp = gamutCompress(applyBlackLift(linOut))
    return (srgbEncodeSample(comp.0), srgbEncodeSample(comp.1), srgbEncodeSample(comp.2))
}

// ── Exported kernels ─────────────────────────────────────────────────────────

/// Fixed-point linear-sRGB Q16 → OKLab Q16. Integer-only; truncating-toward-zero
/// division (Swift `/` == Zig @divTrunc == Haskell `quot`); exact floor cube
/// root. Mirrors SixFour.Spec.ColorFixed.linearToOklabQ16 byte-for-byte.
@_cdecl("s4_linear_to_oklab_q16")
public func s4_linear_to_oklab_q16(
    _ lin_q16: UnsafePointer<Int32>?,
    _ p: Int32,
    _ out_oklab_q16: UnsafeMutablePointer<Int32>?
) -> Int32 {
    guard let lin = lin_q16, let out = out_oklab_q16 else { return rcNullPtr }
    if p <= 0 { return rcBadShape }
    let q16 = q16One64
    let n = Int(p)
    var i = 0
    while i < n {
        let r: Int64 = max(0, Int64(lin[i * 3 + 0]))
        let g: Int64 = max(0, Int64(lin[i * 3 + 1]))
        let b: Int64 = max(0, Int64(lin[i * 3 + 2]))
        let l = clampPosOklab((m1Q16[0] * r + m1Q16[1] * g + m1Q16[2] * b) / q16)
        let m = clampPosOklab((m1Q16[3] * r + m1Q16[4] * g + m1Q16[5] * b) / q16)
        let s = clampPosOklab((m1Q16[6] * r + m1Q16[7] * g + m1Q16[8] * b) / q16)
        let lc = icbrtQ16(l)
        let mc = icbrtQ16(m)
        let sc = icbrtQ16(s)
        let bigL = (m2Q16[0] * lc + m2Q16[1] * mc + m2Q16[2] * sc) / q16
        let aOut = (m2Q16[3] * lc + m2Q16[4] * mc + m2Q16[5] * sc) / q16
        let bOut = (m2Q16[6] * lc + m2Q16[7] * mc + m2Q16[8] * sc) / q16
        out[i * 3 + 0] = Int32(bigL)
        out[i * 3 + 1] = Int32(aOut)
        out[i * 3 + 2] = Int32(bOut)
        i += 1
    }
    return rcOK
}

/// OKLab Q16 centroids → sRGB8 palette: M2⁻¹ matmul, exact integer cube, M1⁻¹
/// matmul, clamp, gamma LUT. Mirrors SixFour.Spec.ColorFixed.oklabToSrgb8Q16
/// byte-for-byte. `scratch` is unused (pure per-entry map).
@_cdecl("s4_palette_oklab_to_srgb8")
public func s4_palette_oklab_to_srgb8(
    _ centroids_q16: UnsafePointer<Int32>?,
    _ k: Int32,
    _ out_rgb: UnsafeMutablePointer<UInt8>?,
    _ scratch: UnsafeMutableRawPointer?,
    _ scratch_cap: Int
) -> Int32 {
    _ = scratch
    _ = scratch_cap
    guard let centroids = centroids_q16, let out = out_rgb else { return rcNullPtr }
    if k <= 0 { return rcBadShape }
    let q16 = q16One64
    let n = Int(k)
    var i = 0
    while i < n {
        let bigL: Int64 = Int64(centroids[i * 3 + 0])
        let a: Int64 = Int64(centroids[i * 3 + 1])
        let b: Int64 = Int64(centroids[i * 3 + 2])
        let l_ = (q16 * bigL + m2iLA * a + m2iLB * b) / q16
        let m_ = (q16 * bigL + m2iMA * a + m2iMB * b) / q16
        let s_ = (q16 * bigL + m2iSA * a + m2iSB * b) / q16
        let l = cubeQ16(l_)
        let m = cubeQ16(m_)
        let s = cubeQ16(s_)
        let r = (m1InvQ16[0] * l + m1InvQ16[1] * m + m1InvQ16[2] * s) / q16
        let g = (m1InvQ16[3] * l + m1InvQ16[4] * m + m1InvQ16[5] * s) / q16
        let bl = (m1InvQ16[6] * l + m1InvQ16[7] * m + m1InvQ16[8] * s) / q16
        out[i * 3 + 0] = gammaByte(r)
        out[i * 3 + 1] = gammaByte(g)
        out[i * 3 + 2] = gammaByte(bl)
        i += 1
    }
    s4log("palette   k=\(k) OKLab->sRGB8 (gamma LUT)")
    return rcOK
}

/// k sRGB8 triples → k OKLab Q16 triples. Decodes a GIF colour table back into the
/// OKLab the quantiser/token builder consume. Lossy inverse (OKLab→sRGB8 already
/// rounded): exact at the byte level only. `out` may alias `rgb`-derived storage.
@_cdecl("s4_srgb8_to_oklab_q16")
public func s4_srgb8_to_oklab_q16(
    _ rgb: UnsafePointer<UInt8>?,
    _ k: Int32,
    _ out_oklab_q16: UnsafeMutablePointer<Int32>?
) -> Int32 {
    guard let rgbPtr = rgb, let out = out_oklab_q16 else { return rcNullPtr }
    if k <= 0 { return rcBadShape }
    let n = Int(k)
    var i = 0
    while i < n {
        out[i * 3 + 0] = srgbLinLut(rgbPtr[i * 3 + 0])
        out[i * 3 + 1] = srgbLinLut(rgbPtr[i * 3 + 1])
        out[i * 3 + 2] = srgbLinLut(rgbPtr[i * 3 + 2])
        i += 1
    }
    // In-place linear→OKLab: s4_linear_to_oklab_q16 reads each triple before writing it.
    return s4_linear_to_oklab_q16(UnsafePointer(out), k, out)
}

/// Analyze a P-entry OKLab Q16 palette into a luminance-zone chroma profile:
/// per-zone mean (a,b,chroma) (sum-then-divide; empty zones fall back to global
/// mean) + the global means. Mirrors SixFour.Spec.ZoneProfile.analyzeZoneProfileQ16.
/// num_zones ≤ 64. out_mean_* each hold num_zones i32; out_global holds 3 i32.
@_cdecl("s4_zone_profile_q16")
public func s4_zone_profile_q16(
    _ palette_oklab_q16: UnsafePointer<Int32>?,
    _ p: Int32,
    _ num_zones: Int32,
    _ out_mean_a: UnsafeMutablePointer<Int32>?,
    _ out_mean_b: UnsafeMutablePointer<Int32>?,
    _ out_mean_c: UnsafeMutablePointer<Int32>?,
    _ out_global: UnsafeMutablePointer<Int32>?
) -> Int32 {
    guard let palette = palette_oklab_q16,
          let outA = out_mean_a,
          let outB = out_mean_b,
          let outC = out_mean_c,
          let outGlobal = out_global
    else { return rcNullPtr }
    if p < 0 || num_zones <= 0 || num_zones > 64 { return rcBadShape }
    let q16 = q16One64
    let nz = Int64(num_zones)
    let nzu = Int(num_zones)
    var sumA = [Int64](repeating: 0, count: 64)
    var sumB = [Int64](repeating: 0, count: 64)
    var sumC = [Int64](repeating: 0, count: 64)
    var count = [Int64](repeating: 0, count: 64)
    var gA: Int64 = 0
    var gB: Int64 = 0
    var gC: Int64 = 0
    var gN: Int64 = 0
    let np = Int(p)
    var i = 0
    while i < np {
        let a: Int64 = Int64(palette[i * 3 + 1])
        let b: Int64 = Int64(palette[i * 3 + 2])
        let c = chromaQ16Native(a, b)
        var z: Int64 = (Int64(palette[i * 3 + 0]) * nz) / q16
        if z < 0 { z = 0 }
        if z > nz - 1 { z = nz - 1 }
        let zu = Int(z)
        sumA[zu] += a
        sumB[zu] += b
        sumC[zu] += c
        count[zu] += 1
        gA += a
        gB += b
        gC += c
        gN += 1
        i += 1
    }
    let globalA: Int64 = gN > 0 ? gA / gN : 0
    let globalB: Int64 = gN > 0 ? gB / gN : 0
    let globalC: Int64 = gN > 0 ? gC / gN : 0
    var z = 0
    while z < nzu {
        let n = count[z]
        outA[z] = Int32(n >= minZonePop ? sumA[z] / n : globalA)
        outB[z] = Int32(n >= minZonePop ? sumB[z] / n : globalB)
        outC[z] = Int32(n >= minZonePop ? sumC[z] / n : globalC)
        z += 1
    }
    outGlobal[0] = Int32(globalA)
    outGlobal[1] = Int32(globalB)
    outGlobal[2] = Int32(globalC)
    s4log("zone_profile p=\(p) nz=\(num_zones)")
    return rcOK
}

/// Map K OKLab Q16 colours through the look transform (the live PREVIEW look).
/// `out_oklab_q16` may alias `in_oklab_q16`. Mirrors
/// SixFour.Spec.LookTransfer.transferPaletteQ16.
@_cdecl("s4_look_transfer_q16")
public func s4_look_transfer_q16(
    _ in_oklab_q16: UnsafePointer<Int32>?,
    _ k: Int32,
    _ mean_a: UnsafePointer<Int32>?,
    _ mean_b: UnsafePointer<Int32>?,
    _ mean_c: UnsafePointer<Int32>?,
    _ num_zones: Int32,
    _ strength_q16: Int32,
    _ chroma_min_q16: Int32,
    _ chroma_max_q16: Int32,
    _ polarity_q16: Int32,
    _ chroma_eps_q16: Int32,
    _ out_oklab_q16: UnsafeMutablePointer<Int32>?
) -> Int32 {
    guard let input = in_oklab_q16,
          let out = out_oklab_q16,
          let meanA = mean_a,
          let meanB = mean_b,
          let meanC = mean_c
    else { return rcNullPtr }
    if k <= 0 || num_zones <= 0 || num_zones > 64 { return rcBadShape }
    let nk = Int(k)
    var i = 0
    while i < nk {
        let o = transferOklab(
            Int64(input[i * 3 + 0]),
            Int64(input[i * 3 + 1]),
            Int64(input[i * 3 + 2]),
            meanA,
            meanB,
            meanC,
            Int64(num_zones),
            Int64(strength_q16),
            Int64(chroma_min_q16),
            Int64(chroma_max_q16),
            Int64(polarity_q16),
            Int64(chroma_eps_q16)
        )
        out[i * 3 + 0] = Int32(o.0)
        out[i * 3 + 1] = Int32(o.1)
        out[i * 3 + 2] = Int32(o.2)
        i += 1
    }
    return rcOK
}

/// Build the N³ .cube as Q16 sRGB-encoded triples in .cube order (R fastest,
/// then G, then B). `out_q16` holds `out_cap` i32; needs cube_size³·3. Mirrors
/// SixFour.Spec.CubeLut.buildCubeQ16. cube_size ∈ [2, 65].
@_cdecl("s4_build_cube_q16")
public func s4_build_cube_q16(
    _ cube_size: Int32,
    _ mean_a: UnsafePointer<Int32>?,
    _ mean_b: UnsafePointer<Int32>?,
    _ mean_c: UnsafePointer<Int32>?,
    _ num_zones: Int32,
    _ strength_q16: Int32,
    _ chroma_min_q16: Int32,
    _ chroma_max_q16: Int32,
    _ polarity_q16: Int32,
    _ chroma_eps_q16: Int32,
    _ out_q16: UnsafeMutablePointer<Int32>?,
    _ out_cap: Int
) -> Int32 {
    guard let out = out_q16, let meanA = mean_a, let meanB = mean_b, let meanC = mean_c else {
        return rcNullPtr
    }
    if cube_size < 2 || cube_size > 65 || num_zones <= 0 || num_zones > 64 { return rcBadShape }
    let n = Int64(cube_size)
    let need = Int(n * n * n * 3)
    if out_cap < need { return rcOutputTooSmall }
    var bi: Int64 = 0
    while bi < n {
        var gi: Int64 = 0
        while gi < n {
            var ri: Int64 = 0
            while ri < n {
                let v = cubeVoxel(
                    ri, gi, bi, n,
                    meanA, meanB, meanC,
                    Int64(num_zones),
                    Int64(strength_q16),
                    Int64(chroma_min_q16),
                    Int64(chroma_max_q16),
                    Int64(polarity_q16),
                    Int64(chroma_eps_q16)
                )
                let base = Int((bi * n * n + gi * n + ri) * 3)
                out[base + 0] = Int32(v.0)
                out[base + 1] = Int32(v.1)
                out[base + 2] = Int32(v.2)
                ri += 1
            }
            gi += 1
        }
        bi += 1
    }
    s4log("build_cube n=\(cube_size) nz=\(num_zones)")
    return rcOK
}
