{- |
Module      : SixFour.Codegen.Burn
Description : Emit the look-NN dimensional contract + golden vectors to the Rust burn crate.

The Haskell→burn bridge. Mirrors 'SixFour.Codegen.Shapes' / 'SixFour.Codegen.Swift':
a pure @Text@ built from the spec constants, written by @app/Spec.hs@ to
@studio/look-nn-baseline/src/generated/contract.rs@. It emits two things:

  * **The dimensional contract** — @T,H,W,K@, the Haar @DOF = 768@, the GMM token width,
    the free dims (@MODEL_DIM@, @MAX_PONDER_DEPTH@), and the encoder/core/decoder IO
    shapes — so the burn trainer inherits its shapes from the spec instead of
    hand-copying them.

  * **Golden cross-check vectors** — values computed *here* by the Haskell reference
    functions ('SixFour.Spec.GMM' / 'SixFour.Spec.Bures') on fixed fixtures. The Rust
    @gmm.rs@ / @bures.rs@ ports must reproduce them to tolerance (Phase 5's conformance
    gate), exactly like the existing Swift/analysis-core golden cross-checks.
-}
module SixFour.Codegen.Burn
  ( emitBurnContract
  ) where

import qualified Data.Text as T
import           Data.Text (Text)

import SixFour.Spec.Color    (OKLab(..))
import SixFour.Spec.Shape
import SixFour.Spec.Net      (NetIO(..))
import SixFour.Spec.LookNet  (gmmTokenDim, modelDim, maxPonderDepth, encoderIO, coreIO, decoderIO)
import SixFour.Spec.PairTree (degreesOfFreedom, levelDof, paletteDepth)
import SixFour.Spec.GMM      (Gaussian(..), GMM, pointMassGMM, mixtureMean, mixtureCovariance)
import SixFour.Spec.Bures    (buresDistanceSq, buresBarycenterCov)

emitBurnContract :: Text
emitBurnContract = T.unlines $
  [ "// GENERATED by sixfour-spec / Codegen.Burn — do not edit by hand."
  , "// Source of truth: spec/src/SixFour/Spec/{Shape,LookNet,PairTree,GMM,Bures}.hs"
  , "// Regenerate with: cabal run spec-codegen"
  , "//"
  , "//! The look-NN dimensional contract + Haskell golden cross-check vectors."
  , "//! The continuous (Gaussian-mixture) substrate; no categories, no [4,2,1] metric."
  , "#![allow(dead_code)]"
  , ""
  , "// ---- Pinned dimensions (T,H,W,K and the Haar identity 768 = 3·256) ----"
  , "pub const T: usize = " <> tshow tVal <> ";"
  , "pub const H: usize = " <> tshow hVal <> ";"
  , "pub const W: usize = " <> tshow wVal <> ";"
  , "pub const K: usize = " <> tshow kVal <> ";"
  , "pub const PIXELS_PER_FRAME: usize = " <> tshow pixelsPerFrame <> ";"
  , "pub const PIXELS_PER_GIF: usize = "   <> tshow pixelsPerGIF <> ";"
  , "pub const DOF: usize = " <> tshow degreesOfFreedom <> ";        // 3·256 Haar coeffs"
  , "pub const LEVEL_DOF: [usize; " <> tshow paletteDepth <> "] = " <> usizeArray levelDof <> ";"
  , ""
  , "// ---- Free structural dimensions (the only knobs) ----"
  , "pub const GMM_TOKEN_DIM: usize = " <> tshow gmmTokenDim <> ";   // μ3 + Σ6 + w1"
  , "pub const MODEL_DIM: usize = "      <> tshow modelDim <> ";"
  , "pub const MAX_PONDER_DEPTH: usize = " <> tshow maxPonderDepth <> ";  // = Haar levels"
  , ""
  , "// ---- Learnable-layer IO shapes (L3 encoder, L4 core, L5 decoder) ----"
  , "pub struct LayerIo { pub in_dim: usize, pub out_dim: usize, pub desc: &'static str }"
  , layerIo "ENCODER_IO" encoderIO
  , layerIo "CORE_IO"    coreIO
  , layerIo "DECODER_IO" decoderIO
  , ""
  , "/// Golden cross-check vectors — computed by the Haskell reference (Spec.GMM /"
  , "/// Spec.Bures). The Rust gmm.rs / bures.rs ports MUST reproduce these to 1e-6."
  , "pub mod golden {"
  , "    // GMM fixture: two point-mass components (μ, w) ="
  , "    //   (0.20, 0.05, -0.10; w=1) and (0.80, -0.10, 0.10; w=2)."
  , "    pub const GMM_MIX_MEAN: [f64; 3] = " <> okArray gMean3 <> ";"
  , "    pub const GMM_MIX_COV:  [f64; 6] = " <> f64Array6 gCov6 <> ";"
  , "    // Bures fixture: g1 = (μ=0.3, Σ=diag(0.02,0.01,0.01)),"
  , "    //               g2 = (μ=0.7, Σ=diag(0.03,0.02,0.015))."
  , "    pub const BURES_DIST_SQ: f64 = " <> tshowF buresDistSq <> ";"
  , "    pub const BURES_BARY_COV: [f64; 6] = " <> f64Array6 baryCov6 <> ";"
  , "}"
  ]

-- ---------------------------------------------------------------------------
-- Golden fixtures (evaluated by the Haskell reference functions at codegen time)
-- ---------------------------------------------------------------------------

gmmFixture :: GMM
gmmFixture = pointMassGMM [ (OKLab 0.20 0.05 (-0.10), 1), (OKLab 0.80 (-0.10) 0.10, 2) ]

gMean3 :: OKLab
gMean3 = mixtureMean gmmFixture

gCov6 :: (Double, Double, Double, Double, Double, Double)
gCov6 = mixtureCovariance gmmFixture

buresG1, buresG2 :: Gaussian
buresG1 = Gaussian (OKLab 0.3 0 0) (0.02, 0, 0, 0.01, 0, 0.01)  1
buresG2 = Gaussian (OKLab 0.7 0 0) (0.03, 0, 0, 0.02, 0, 0.015) 1

buresDistSq :: Double
buresDistSq = buresDistanceSq buresG1 buresG2

baryCov6 :: (Double, Double, Double, Double, Double, Double)
baryCov6 = buresBarycenterCov [(0.5, gCov buresG1), (0.5, gCov buresG2)]

-- ---------------------------------------------------------------------------
-- Formatting helpers
-- ---------------------------------------------------------------------------

layerIo :: Text -> NetIO -> Text
layerIo nm io = T.concat
  [ "pub const ", nm, ": LayerIo = LayerIo { in_dim: ", tshow (netInputDim io)
  , ", out_dim: ", tshow (netOutputDim io), ", desc: \"", T.pack (netDescription io), "\" };" ]

okArray :: OKLab -> Text
okArray (OKLab l a b) = "[" <> T.intercalate ", " (map tshowF [l, a, b]) <> "]"

f64Array6 :: (Double, Double, Double, Double, Double, Double) -> Text
f64Array6 (a, b, c, d, e, f) = "[" <> T.intercalate ", " (map tshowF [a, b, c, d, e, f]) <> "]"

usizeArray :: [Int] -> Text
usizeArray xs = "[" <> T.intercalate ", " (map tshow xs) <> "]"

tshow :: Show a => a -> Text
tshow = T.pack . show

tshowF :: Double -> Text
tshowF = T.pack . show
