{- |
Module      : SixFour.Codegen.CaptureFormat
Description : Emit the ONE capture-format contract to Swift + Python — the app's exported GIF IS the encoder input.

Mirrors "SixFour.Spec.CaptureFormat". Emits two files from the SAME spec constants so the hermetic-codegen
gate diffs both against a fresh @cabal run spec-codegen@ and fails on drift:

  * @SixFour/Generated/CaptureFormatContract.swift@ — the device/app side: @decimate4x@ (the 256²→64² import
    reduction, exact inverse of @SixFourExport.replicate4x@) + the capture/wire dims + the sRGB8 per-frame
    palette constants + a @selfCheck()@ re-asserting the Haskell golden.
  * @trainer/generated/capture_format.py@ — the trainer side: the same @decimate4x@ + constants, so the
    Python importer that turns a real 256²×64 app GIF into a 64³ capture defers to spec values.

The keystone theorem is "SixFour.Spec.Export" @lawDecimateInvertsReplicate@ / "SixFour.Spec.CaptureFormat"
@lawExportImportRoundTripsIndices@: @decimate2D ∘ replicate2D == id@ in the index domain. The TIME axis is
never scaled at the wire (256²×64, NOT @upscale256@'s 256³). The palette is sRGB8 + index canonical; OKLab
Q16 is the model's internal working space and is NOT recoverable across the GIF
("SixFour.Spec.CaptureFormat" @contractQ16NotRecoverableAcrossGif@).
-}
module SixFour.Codegen.CaptureFormat
  ( emitCaptureFormatContract
  , emitCaptureFormatPy
  ) where

import qualified Data.Text as T
import           Data.Text (Text)

import SixFour.Spec.CaptureFormat
  ( captureSide, captureFrames, wireSide, wireFrames
  , capturePaletteEntries, captureColorDepthBits
  , captureControlGridSide, captureCellSpan )
import SixFour.Spec.Export (upscaleFactor)

tshow :: Show a => a -> Text
tshow = T.pack . show

-- | Generate @CaptureFormatContract.swift@: the capture/wire dims, the per-frame sRGB8 palette constants,
-- and @decimate4x@ — the exact inverse of @SixFourExport.replicate4x@ that re-imports a shipped 256² frame
-- to the logical 64² index plane. @selfCheck()@ re-asserts the round-trip golden (Properties.CaptureFormat).
emitCaptureFormatContract :: Text
emitCaptureFormatContract = T.unlines
  [ "// GENERATED by sixfour-spec / Codegen.CaptureFormat — do not edit by hand."
  , "// Source of truth: ~/SixFour/spec/src/SixFour/Spec/CaptureFormat.hs"
  , "// Regenerate with: cabal run spec-codegen"
  , ""
  , "import Foundation"
  , ""
  , "/// The ONE canonical capture format: the app's exported GIF IS the encoder's input."
  , "///"
  , "/// The capture is logically 64³ (64×64 × 64 frames, per-frame 256-entry sRGB8 palette). The shipped"
  , "/// GIF is its SPATIAL-ONLY 4× replication (`SixFourExport.replicate4x`): 64²→256² in the index"
  , "/// domain, frame count UNCHANGED (256×256×64). Import reverses it by exact decimation (`decimate4x`):"
  , "/// 256²→64², byte-exact in the index domain. The TIME axis is never scaled at the wire — that is"
  , "/// `upscale256` (the model OUTPUT, 256³), NOT the capture wire. Port of `SixFour.Spec.CaptureFormat`."
  , "public enum SixFourCaptureFormat {"
  , "    /// The logical capture spatial side (64)."
  , "    public static let captureSide: Int = " <> tshow captureSide
  , "    /// The capture frame count (64) — NEVER scaled at the wire."
  , "    public static let captureFrames: Int = " <> tshow captureFrames
  , "    /// The shipped GIF spatial side (256 = captureSide × upscaleFactor)."
  , "    public static let wireSide: Int = " <> tshow wireSide
  , "    /// The shipped GIF frame count (64 = captureFrames)."
  , "    public static let wireFrames: Int = " <> tshow wireFrames
  , "    /// The spatial upscale factor at export (4)."
  , "    public static let upscaleFactor: Int = " <> tshow upscaleFactor
  , "    /// Per-frame palette entries (256, a GIF Local Color Table)."
  , "    public static let paletteEntries: Int = " <> tshow capturePaletteEntries
  , "    /// Palette colour depth on the wire: 8 bits/channel (sRGB8 — the most a GIF can carry)."
  , "    public static let colorDepthBits: Int = " <> tshow captureColorDepthBits
  , "    /// The nudge control-grid side (16); one cell governs `cellSpan`³ capture voxels."
  , "    public static let controlGridSide: Int = " <> tshow captureControlGridSide
  , "    /// Capture voxels per axis governed by one nudge cell (4 = captureSide / controlGridSide)."
  , "    public static let cellSpan: Int = " <> tshow captureCellSpan
  , ""
  , "    /// Import reduction: decimate a `bigSide×bigSide` row-major index frame to"
  , "    /// `(bigSide/factor)²` by keeping each `factor×factor` block's TOP-LEFT cell. On a"
  , "    /// `replicate4x` output every block is constant, so this recovers the source index byte-exact"
  , "    /// — the exact left inverse of `SixFourExport.replicate`."
  , "    public static func decimate(_ cells: [UInt8], bigSide: Int, factor: Int) -> [UInt8] {"
  , "        let outSide = bigSide / factor"
  , "        var out = [UInt8](repeating: 0, count: outSide * outSide)"
  , "        for by in 0 ..< outSide {"
  , "            for bx in 0 ..< outSide {"
  , "                out[by * outSide + bx] = cells[(by * factor) * bigSide + (bx * factor)]"
  , "            }"
  , "        }"
  , "        return out"
  , "    }"
  , ""
  , "    /// The shipping 4× decimation (256 → 64): re-import a shipped frame to the logical index plane."
  , "    public static func decimate4x(_ frame: [UInt8]) -> [UInt8] {"
  , "        decimate(frame, bigSide: wireSide, factor: upscaleFactor)"
  , "    }"
  , ""
  , "    /// Re-asserts the Haskell golden (Properties.CaptureFormat): decimate ∘ replicate == id."
  , "    public static func selfCheck() -> Bool {"
  , "        let plane: [UInt8] = [10, 20, 30, 40]"
  , "        let wire = SixFourExport.replicate(plane, side: 2, factor: 2)"
  , "        let back = decimate(wire, bigSide: 4, factor: 2)"
  , "        return back == plane"
  , "            && captureSide == 64 && captureFrames == 64"
  , "            && wireSide == 256 && wireFrames == 64 && cellSpan == 4"
  , "            && colorDepthBits == 8 && paletteEntries == 256"
  , "    }"
  , "}"
  ]

-- | Generate @trainer/generated/capture_format.py@: the same dims + @decimate4x@ for the Python importer
-- that turns a real 256²×64 app GIF into a 64³ capture. Spec-derived constants, hermetic-gated.
emitCaptureFormatPy :: Text
emitCaptureFormatPy = T.unlines
  [ "# GENERATED by sixfour-spec / Codegen.CaptureFormat — do not edit by hand."
  , "# Source of truth: ~/SixFour/spec/src/SixFour/Spec/CaptureFormat.hs"
  , "# Regenerate with: cabal run spec-codegen"
  , "\"\"\"The ONE canonical capture format: the app's exported GIF IS the encoder input."
  , ""
  , "Capture is logically 64^3 (64x64 x 64 frames, per-frame 256-entry sRGB8 palette). The shipped GIF is"
  , "its SPATIAL-ONLY 4x replication (256x256x64); import reverses it by exact decimation (decimate4x):"
  , "256->64 per frame, byte-exact in the index domain. Time is NEVER scaled at the wire (that is"
  , "upscale256, the model OUTPUT). Palette is sRGB8 + index canonical; OKLab Q16 is internal-only and is"
  , "NOT recoverable across the GIF.\"\"\""
  , "from __future__ import annotations"
  , ""
  , "CAPTURE_SIDE = " <> tshow captureSide
  , "CAPTURE_FRAMES = " <> tshow captureFrames
  , "WIRE_SIDE = " <> tshow wireSide
  , "WIRE_FRAMES = " <> tshow wireFrames
  , "UPSCALE_FACTOR = " <> tshow upscaleFactor
  , "PALETTE_ENTRIES = " <> tshow capturePaletteEntries
  , "COLOR_DEPTH_BITS = " <> tshow captureColorDepthBits
  , "CONTROL_GRID_SIDE = " <> tshow captureControlGridSide
  , "CELL_SPAN = " <> tshow captureCellSpan
  , ""
  , ""
  , "def decimate(cells, big_side, factor=UPSCALE_FACTOR):"
  , "    \"\"\"Decimate a big_side x big_side row-major index frame to (big_side/factor)^2 by keeping each"
  , "    factor x factor block's TOP-LEFT cell. Exact left inverse of SixFourExport.replicate on a"
  , "    constant-block (replicated) input.\"\"\""
  , "    out_side = big_side // factor"
  , "    return [cells[(by * factor) * big_side + (bx * factor)]"
  , "            for by in range(out_side) for bx in range(out_side)]"
  , ""
  , ""
  , "def decimate4x(frame):"
  , "    \"\"\"The shipping 256 -> 64 import: re-import a shipped frame to the logical index plane.\"\"\""
  , "    return decimate(frame, WIRE_SIDE, UPSCALE_FACTOR)"
  , ""
  , ""
  , "def replicate(cells, side, factor=UPSCALE_FACTOR):"
  , "    \"\"\"Replicate a side x side row-major index frame into (factor*side)^2 by copying each source cell"
  , "    into a factor x factor block (index-domain nearest, the app's export upscale; palette untouched).\"\"\""
  , "    out_side = factor * side"
  , "    return [cells[(oy // factor) * side + (ox // factor)]"
  , "            for oy in range(out_side) for ox in range(out_side)]"
  , ""
  , ""
  , "def replicate4x(frame):"
  , "    \"\"\"The shipping 64 -> 256 export: spatial 4x replication of one logical index plane.\"\"\""
  , "    return replicate(frame, CAPTURE_SIDE, UPSCALE_FACTOR)"
  , ""
  , ""
  , "def _self_check():"
  , "    plane = [10, 20, 30, 40]"
  , "    assert decimate(replicate(plane, 2, 2), 4, 2) == plane, \"decimate . replicate != id\""
  , "    assert (CAPTURE_SIDE, CAPTURE_FRAMES, WIRE_SIDE, WIRE_FRAMES, CELL_SPAN) == (64, 64, 256, 64, 4)"
  , "    assert (COLOR_DEPTH_BITS, PALETTE_ENTRIES) == (8, 256)"
  , "    print('capture_format: PASS')"
  , ""
  , ""
  , "if __name__ == '__main__':"
  , "    _self_check()"
  ]
