{- |
Module      : SixFour.Codegen.CloudProjection
Description : Emit CloudProjectionGolden.swift — the distance-honest OKLab→world pin.

The Review screen's @PaletteCloudView@ ports 'SixFour.Spec.CloudProjection.oklabToWorld'
BY HAND (a fixed canonical centre @(0.5,0,0)@ and a SINGLE isotropic scale @s=2@,
mapping @a→x, L→y, b→z@). That hand-port previously carried a @TODO(spec-pin)@ and
no gate, so it could silently drift from the spec and break the @lawWorldIsometry@
guarantee (world distance = OKLab distance up to the constant @s@).

This emits the centre/scale constants plus a fixed OKLab fixture and its expected
world coordinates. @CloudProjectionGoldenTests.swift@ runs the Swift port against
them. Float math ⇒ tolerance gate (the Swift port is @Float@, the spec is @Double@).
-}
module SixFour.Codegen.CloudProjection
  ( emitCloudProjectionGolden
  ) where

import qualified Data.Text as T
import           Data.Text (Text)

import SixFour.Spec.Color          (OKLab(..))
import SixFour.Spec.CloudProjection (Vec3(..), oklabToWorld, canonicalCentre, canonicalScale)

-- | A deterministic OKLab fixture spanning L∈[0,1], a,b∈[-0.4,0.4] (distinct seed).
cloudGoldenColors :: [OKLab]
cloudGoldenColors = take 12 (gen 0xc10ad)
  where
    gen :: Int -> [OKLab]
    gen s =
      let s1 = step s; s2 = step s1; s3 = step s2
          l = fromIntegral (s1 `mod` 1001) / 1000
          a = fromIntegral (s2 `mod` 801)  / 1000 - 0.4
          b = fromIntegral (s3 `mod` 801)  / 1000 - 0.4
      in OKLab l a b : gen s3
    step s = (s * 1103515245 + 12345) `mod` 2147483648

-- | Emit the Swift golden for the distance-true OKLab→world map.
emitCloudProjectionGolden :: Text
emitCloudProjectionGolden = T.unlines
  [ "// GENERATED by sixfour-spec / Codegen.CloudProjection — do not edit by hand."
  , "// Regenerate with: cabal run spec-codegen."
  , "//"
  , "// Distance-honest pin for the P4 cloud's OKLab→world map"
  , "// (SixFour.Spec.CloudProjection.oklabToWorld): fixed centre + ONE isotropic"
  , "// scale, so world distance == OKLab distance up to the constant scale."
  , "// The Swift port (Float) must reproduce these (Double) within tolerance."
  , "import simd"
  , ""
  , "enum CloudProjectionGolden {"
  , "    /// Canonical OKLab centre (Lᶜ, aᶜ, bᶜ) — NOT data-derived."
  , "    static let centre: SIMD3<Double> = " <> simd3d canonicalCentre
  , ""
  , "    /// The single isotropic world scale s."
  , "    static let scale: Double = " <> dbl canonicalScale
  , ""
  , "    /// Input OKLab fixture (L, a, b)."
  , "    static let colors: [SIMD3<Double>] = " <> simd3dArr cloudGoldenColors
  , ""
  , "    /// Expected world coordinates (x, y, z) = oklabToWorld(color)."
  , "    static let world: [SIMD3<Double>] = " <> vec3Arr (map oklabToWorld cloudGoldenColors)
  , "}"
  ]

dbl :: Double -> Text
dbl = T.pack . show

simd3d :: OKLab -> Text
simd3d (OKLab l a b) = "SIMD3<Double>(" <> T.intercalate ", " (map dbl [l, a, b]) <> ")"

simd3dArr :: [OKLab] -> Text
simd3dArr xs = "[" <> T.intercalate ", " (map simd3d xs) <> "]"

vec3 :: Vec3 -> Text
vec3 (Vec3 x y z) = "SIMD3<Double>(" <> T.intercalate ", " (map dbl [x, y, z]) <> ")"

vec3Arr :: [Vec3] -> Text
vec3Arr xs = "[" <> T.intercalate ", " (map vec3 xs) <> "]"
