{- |
Module      : SixFour.Codegen.Collapse
Description : Emit CollapseGolden.swift — the byte-exact gate for the Q16 collapse.

The shipped per-frame → global palette collapse (GIFA → GIFB) is
'SixFour.Spec.Collapse.globalCollapseQ16': maximin farthest-point selection over
the pooled per-frame palettes, in Q16 integers. Because it is integer-exact (and
reuses the Zig-mirrored 'farthestPointSeedsQ16'), the golden is emitted as plain
Swift integer literals — no IEEE-754 hex transport, no tolerance — and the Swift
port ('FarthestPointCollapse') must reproduce every value EXACTLY.

Emitted as a Swift source (not JSON) to match the @*Contract.swift@ codegen
pattern: it rides the same drift gate, needs no runtime bundle lookup, and never
ships a stray resource in the app bundle.

Fixture: the deterministic cross-language Q16 inputs ('goldenLinearInputsQ16',
64 linear-sRGB points) mapped through 'linearToOklabQ16' and chunked into 8
"frames" of 8 colours; @k = 16@ leaves. Small but exercises pooling (64 → 16) and
re-index (64 colours → nearest of 16).
-}
module SixFour.Codegen.Collapse
  ( emitCollapseGolden
  ) where

import qualified Data.Text as T
import           Data.Text (Text)
import           Data.List (foldl')

import SixFour.Spec.ColorFixed (linearToOklabQ16, goldenLinearInputsQ16)
import SixFour.Spec.Collapse
  ( PxQ16, pooledCandidatesQ16, globalCollapseQ16, globalCollapseIndicesQ16
  , reindexFrameQ16 )

-- | @k@ leaves the fixture collapses to.
collapseGoldenK :: Int
collapseGoldenK = 16

-- | The deterministic fixture: 64 cross-language Q16 OKLab colours, in 8 frames
-- of 8. (Reuses 'goldenLinearInputsQ16' so the inputs match the colour golden.)
goldenFramesQ16 :: [[PxQ16]]
goldenFramesQ16 = chunk 8 (map linearToOklabQ16 goldenLinearInputsQ16)
  where
    chunk _ [] = []
    chunk n xs = take n xs : chunk n (drop n xs)

emitCollapseGolden :: Text
emitCollapseGolden = T.unlines
  [ "// GENERATED by sixfour-spec / Codegen.Collapse — do not edit by hand."
  , "// Regenerate with: cabal run spec-codegen."
  , "//"
  , "// Byte-exact golden for the Q16 global-palette collapse (GIFA → GIFB):"
  , "// maximin farthest-point selection over the pooled per-frame palettes"
  , "// (SixFour.Spec.Collapse.globalCollapseQ16, reusing the Zig-mirrored"
  , "// farthestPointSeedsQ16) + nearest-centroid re-index. Every value is a Q16"
  , "// OKLab integer (scale 2^16); the Swift FarthestPointCollapse must reproduce"
  , "// them EXACTLY (no tolerance)."
  , "import simd"
  , ""
  , "enum CollapseGolden {"
  , "    /// Number of collapsed global leaves."
  , "    static let k: Int = " <> tshow collapseGoldenK
  , ""
  , "    /// The " <> tshow (length goldenFramesQ16) <> " input per-frame palettes (Q16 OKLab)."
  , "    static let frames: [[SIMD3<Int32>]] = " <> framesLit goldenFramesQ16
  , ""
  , "    /// Pooled candidate count (= sum of frame palette sizes)."
  , "    static let pooledCount: Int = " <> tshow (length pooled)
  , ""
  , "    /// Integer cloud mean (first-seed reference)."
  , "    static let pooledMean: SIMD3<Int32> = " <> simd3 mean
  , ""
  , "    /// Index of the first seed (farthest pooled colour from the mean)."
  , "    static let firstIndex: Int = " <> tshow firstIdx
  , ""
  , "    /// Full chosen-index sequence into the pooled cloud (length k)."
  , "    static let chosenIndices: [Int] = " <> intArr idxs
  , ""
  , "    /// The k collapsed global leaves (Q16 OKLab) = pooled[chosenIndices]."
  , "    static let leaves: [SIMD3<Int32>] = " <> simd3Arr leaves
  , ""
  , "    /// Each frame's colours re-indexed against `leaves` (nearest leaf)."
  , "    static let reindexedFrames: [[Int]] = " <> nestedIntLit reindexed
  , "}"
  ]
  where
    pooled   = pooledCandidatesQ16 goldenFramesQ16
    n        = length pooled
    (sl, sa, sb) =
      foldl' (\(al, aa, ab) (l, a, b) -> (al + l, aa + a, ab + b)) (0, 0, 0) pooled
    mean     = (sl `quot` n, sa `quot` n, sb `quot` n)
    idxs     = globalCollapseIndicesQ16 collapseGoldenK goldenFramesQ16
    firstIdx = head idxs
    leaves   = globalCollapseQ16 collapseGoldenK goldenFramesQ16
    reindexed = map (reindexFrameQ16 leaves) goldenFramesQ16

-- ---------------------------------------------------------------------------
-- Swift-literal emitters
-- ---------------------------------------------------------------------------

tshow :: Show a => a -> Text
tshow = T.pack . show

simd3 :: PxQ16 -> Text
simd3 (a, b, c) = "SIMD3<Int32>(" <> T.intercalate ", " (map tshow [a, b, c]) <> ")"

simd3Arr :: [PxQ16] -> Text
simd3Arr ts = "[" <> T.intercalate ", " (map simd3 ts) <> "]"

intArr :: [Int] -> Text
intArr xs = "[" <> T.intercalate ", " (map tshow xs) <> "]"

-- | A list of frames (each a list of Q16 triples), one frame per indented line.
framesLit :: [[PxQ16]] -> Text
framesLit fs =
  "[\n" <> T.intercalate ",\n" [ "        " <> simd3Arr f | f <- fs ] <> "\n    ]"

-- | A list of index maps, one per indented line.
nestedIntLit :: [[Int]] -> Text
nestedIntLit xs =
  "[\n" <> T.intercalate ",\n" [ "        " <> intArr m | m <- xs ] <> "\n    ]"
