{- |
Module      : SixFour.Codegen.DerivationLog
Description : Emit DerivationLogGolden.swift — the byte-exact gate for the genealogy-fold Swift port.

The hand-written Swift genealogy fold must mirror 'SixFour.Spec.DerivationLog': each event's id is
the "SixFour.Spec.GeneHash" content-address of @(payload, parents)@ (self-verifying), and
'genealogyOf' is the order-INDEPENDENT fold (group by id, keep the canonical tag per id — earliest
@(epoch, creator)@) that gives Strong Eventual Consistency. This golden pins a small log, its exact
event ids, and the genealogy folded from BOTH the log and a shuffled copy (they must match — the
convergence property). @DerivationLogGoldenTests@ on device must reproduce every event id and the
same genealogy regardless of delivery order.
-}
module SixFour.Codegen.DerivationLog
  ( emitDerivationLogGolden
  ) where

import qualified Data.Text as T
import           Data.Text (Text)

import SixFour.Spec.DerivationLog (DerivationEvent(..), eventId, genealogyOf)
import SixFour.Spec.Lineage       (GeneTag(..))
import SixFour.Spec.Trade         (CreatorId(..), GeneId(..))

-- A tiny log: two origins, a two-parent child (parents by ABSOLUTE address), and a duplicate
-- re-mint of an origin by a LATER creator (must dedup to the earliest tag — the canonical-key rule).
originA, originB :: DerivationEvent
originA = DerivationEvent [1000, -2000, 65536] []          (CreatorId 1) 0
originB = DerivationEvent [7, 7, 7]           []           (CreatorId 1) 0

child :: DerivationEvent
child = DerivationEvent [42] [eventId originA, eventId originB] (CreatorId 2) 1

-- A re-mint of originB's exact content+parents by a different, later creator — same id, must NOT
-- create a second genealogy node (dedup to the earliest (epoch, creator)).
originBRemint :: DerivationEvent
originBRemint = DerivationEvent [7, 7, 7] [] (CreatorId 9) 5

theLog :: [DerivationEvent]
theLog = [originA, originB, child, originBRemint]

-- A different delivery order (reversed + the remint moved early) — genealogyOf MUST be identical.
shuffledLog :: [DerivationEvent]
shuffledLog = [originBRemint, child, originB, originA]

emitDerivationLogGolden :: Text
emitDerivationLogGolden = T.unlines $
  [ "// GENERATED by sixfour-spec / Codegen.DerivationLog — do not edit by hand."
  , "// Regenerate with: cabal run spec-codegen."
  , "//"
  , "// Byte-exact golden for the genealogy fold (SixFour.Spec.DerivationLog). The Swift port must"
  , "// reproduce each event id (the GeneHash content-address) and fold BOTH the log and its"
  , "// shuffled copy to the SAME genealogy (Strong Eventual Consistency: order-independent, dedup)."
  , ""
  , "enum DerivationLogGolden {"
  , "    struct Event { let payload: [Int]; let parents: [Int]; let creator: Int; let epoch: Int; let id: Int }"
  , "    struct Tag { let gene: Int; let creator: Int; let parents: [Int]; let minted: Int }"
  , ""
  , "    /// The log in delivery order, each event carrying its self-derived id."
  , "    static let log: [Event] = ["
  ]
  ++ map eventLine theLog
  ++ [ "    ]"
     , ""
     , "    /// A DIFFERENT delivery order of the same event set (convergence input)."
     , "    static let shuffledLog: [Event] = ["
     ]
  ++ map eventLine shuffledLog
  ++ [ "    ]"
     , ""
     , "    /// The genealogy folded from the log — address-ordered, deduped, canonical tag per id."
     , "    /// The port must produce this from EITHER log (order-independence is the whole point)."
     , "    static let genealogy: [Tag] = ["
     ]
  ++ map tagLine (genealogyOf theLog)
  ++ [ "    ]"
     , ""
     , "    /// Asserted at spec-emit time: both orders fold to the same genealogy."
     , "    static let convergesUnderReorder = " <> boolLit (genealogyOf theLog == genealogyOf shuffledLog)
     , "}"
     ]
  where
    eventLine e =
      "        Event(payload: " <> intArr (dePayload e)
        <> ", parents: " <> intArr [ i | GeneId i <- deParents e ]
        <> ", creator: " <> (let CreatorId c = deCreator e in tshow c)
        <> ", epoch: " <> tshow (deEpoch e)
        <> ", id: " <> (let GeneId i = eventId e in tshow i) <> "),"
    tagLine t =
      "        Tag(gene: " <> (let GeneId i = gtGene t in tshow i)
        <> ", creator: " <> (let CreatorId c = gtCreator t in tshow c)
        <> ", parents: " <> intArr [ i | GeneId i <- gtParents t ]
        <> ", minted: " <> tshow (gtMinted t) <> "),"

tshow :: Show a => a -> Text
tshow = T.pack . show

boolLit :: Bool -> Text
boolLit b = if b then "true" else "false"

intArr :: [Int] -> Text
intArr xs = "[" <> T.intercalate ", " (map tshow xs) <> "]"
