{- |
Module      : SixFour.Codegen.DeviceTrain
Description : Emit @DeviceTrainGolden.swift@ — the device-alignment gate for the V3.0 ON-DEVICE per-capture training step (the "SixFour.Spec.DeviceTrainStep" fixture + its pinned post-commit bytes).

The V3.0 on-device trainer (MPSGraph first, Metal-4 tensor second) fine-tunes the
"SixFour.Spec.DetailPredictor" @f_θ@ on the supervision pair the capture itself
manufactures. This golden pins that whole loop to the spec: the Swift trainer must
(1) manufacture the SAME pair from @fineBlock@ via its lift, (2) descend with the SAME
η/steps, and (3) commit to EXACTLY the same integer detail bands (@committed@ —
BIT-EXACT, no tolerance). The float θ is emitted for tolerance comparison only:
float trajectories legitimately differ across backends (summation order, float32 on
the A19 neural accelerator); the committed bytes may not.

GHC-boot-only. Consumed by @app/Spec.hs@ (writes @SixFour/Generated/DeviceTrainGolden.swift@).
-}
module SixFour.Codegen.DeviceTrain
  ( emitDeviceTrainGolden
  ) where

import           Data.Text (Text)
import qualified Data.Text as T

import SixFour.Spec.OctreeCell      (V8(..), detailToList)
import SixFour.Spec.DetailPredictor (defaultPredictorShape, paramCount, predictDetail)
import SixFour.Spec.DeviceTrainStep
  ( deviceCoarse, deviceFineBlock, deviceTargetDetail
  , deviceEta, deviceTrainSteps, deviceTheta )

emitDeviceTrainGolden :: Text
emitDeviceTrainGolden = T.unlines
  [ "// GENERATED by sixfour-spec / Codegen.DeviceTrain — do not edit by hand."
  , "// Regenerate with: cabal run spec-codegen."
  , "//"
  , "// Device-alignment gate for the V3.0 ON-DEVICE per-capture training step"
  , "// (SixFour.Spec.DeviceTrainStep). The on-device trainer (MPSGraph / Metal 4)"
  , "// manufactures the pair from fineBlock via the octant lift, descends with the"
  , "// same eta/steps, and must commit to EXACTLY `committed` (BIT-EXACT, integers)."
  , "// `theta` is a tolerance reference only — float trajectories differ per backend;"
  , "// the post-commit bytes may not."
  , ""
  , "enum DeviceTrainGolden {"
  , "    static let eta = " <> showD deviceEta
  , "    static let steps = " <> tshow deviceTrainSteps
  , "    static let paramCount = " <> tshow (paramCount defaultPredictorShape)
  , ""
  , "    /// The captured fine 2×2×2 block (Morton lane order) — the trainer's ONLY input."
  , "    static let fineBlock: [Int] = [" <> ints (v8List deviceFineBlock) <> "]"
  , ""
  , "    /// What the on-device lift must manufacture from fineBlock (coarse, 7 bands)."
  , "    static let coarse = " <> tshow deviceCoarse
  , "    static let targetDetail: [Int] = [" <> ints (detailToList deviceTargetDetail) <> "]"
  , ""
  , "    /// The Haskell-descent θ (tolerance reference, NOT the gate)."
  , "    static let theta: [Double] = [" <> T.intercalate ", " (map showD deviceTheta) <> "]"
  , ""
  , "    /// THE GATE: the committed detail after training (BIT-EXACT, no tolerance)."
  , "    static let committed: [Int] = [" <> ints (detailToList golden) <> "]"
  , "}"
  ]
  where
    -- The COMPUTED committed bands (lawDeviceTrainedDetailIsGolden proves these equal
    -- the pinned goldenDeviceDetail — emitting the computation keeps the file honest).
    golden = predictDetail defaultPredictorShape deviceTheta deviceCoarse

    v8List (V8 a b c d e f g h) = [a, b, c, d, e, f, g, h]

    ints = T.intercalate ", " . map tshow

tshow :: Show a => a -> Text
tshow = T.pack . show

-- | Round-trippable decimal Double literal (Haskell @show@ ⟷ Swift @Double@, both IEEE-754).
showD :: Double -> Text
showD = T.pack . show
