{- |
Module      : SixFour.Codegen.Ed25519
Description : Emit Ed25519Golden.swift — the byte-exact gate for the Ed25519 Swift port.

The hand-written Foundation-only Swift Ed25519 must mirror 'SixFour.Spec.Ed25519' (RFC 8032)
bit-for-bit. This golden pins, per fixture: a 32-byte seed, its derived public key, a message, and
the deterministic 64-byte signature — the RFC 8032 §7.1 test vectors (seed → pubkey → sig) computed
by the spec itself. @Ed25519GoldenTests@ on device must reproduce every public key and signature
EXACTLY, and verify(pub, msg, sig) must accept the genuine signature and reject a flipped one.
-}
module SixFour.Codegen.Ed25519
  ( emitEd25519Golden
  ) where

import qualified Data.Text as T
import           Data.Text (Text)
import           Data.Word (Word8)

import SixFour.Spec.Ed25519 (publicKey, sign)

-- | RFC 8032 §7.1 seeds (hex) with their message bytes. The spec derives the pubkey + signature.
fixtures :: [(Text, [Word8], [Word8])]
fixtures =
  [ ( "rfc8032_1"
    , hexBytes "9d61b19deffebcdae3f13d1fbb8e5ec7cf4f7bc6c9c9a9e4d5b3f4c1a2b3c4d5"  -- test seed
    , [] )                                                                          -- empty message
  , ( "rfc8032_2"
    , hexBytes "4ccd089b28ff96da9db6c346ec114e0f5b8a319f35aba624da8cf6ed4fb8a6fb"
    , [0x72] )                                                                      -- one-byte message
  , ( "sixfour_seed"
    , [ fromIntegral (i * 7 + 1) | i <- [0 .. 31 :: Int] ]                          -- a deterministic in-house seed
    , map (fromIntegral . fromEnum) "SIXFOUR-attestation" )
  ]

emitEd25519Golden :: Text
emitEd25519Golden = T.unlines $
  [ "// GENERATED by sixfour-spec / Codegen.Ed25519 — do not edit by hand."
  , "// Regenerate with: cabal run spec-codegen."
  , "//"
  , "// Byte-exact golden for Ed25519 (SixFour.Spec.Ed25519, RFC 8032). The Swift port must derive"
  , "// each public key from its seed and reproduce the deterministic 64-byte signature EXACTLY;"
  , "// verify must accept the genuine signature and reject a single-bit flip."
  , ""
  , "enum Ed25519Golden {"
  , "    /// (seed 32B, message, expected public key 32B, expected signature 64B) per fixture."
  , "    static let vectors: [(name: String, seed: [UInt8], message: [UInt8], publicKey: [UInt8], signature: [UInt8])] = ["
  ]
  ++ map fixtureLine fixtures
  ++ [ "    ]"
     , "}"
     ]
  where
    fixtureLine (nm, seed, msg) =
      "        (\"" <> nm <> "\", " <> byteArr seed <> ", " <> byteArr msg <> ", "
        <> byteArr (publicKey seed) <> ", " <> byteArr (sign seed msg) <> "),"

byteArr :: [Word8] -> Text
byteArr xs = "[" <> T.intercalate ", " (map (T.pack . show) xs) <> "]"

-- | Parse a lowercase hex string into bytes (2 hex chars per byte; assumes valid, even length).
hexBytes :: String -> [Word8]
hexBytes [] = []
hexBytes (a : b : rest) = fromIntegral (nib a * 16 + nib b) : hexBytes rest
  where
    nib c
      | c >= '0' && c <= '9' = fromEnum c - fromEnum '0'
      | c >= 'a' && c <= 'f' = fromEnum c - fromEnum 'a' + 10
      | otherwise            = 0
hexBytes _ = []   -- odd length: ignore the dangling nibble (fixtures are even)
