{- |
Module      : SixFour.Codegen.GeneHash
Description : Emit GeneHashGolden.swift — the byte-exact gate for the gene content-address Swift port.

The hand-written Swift port of the gene content-address must mirror 'SixFour.Spec.GeneHash': the
length-prefixed little-endian 'SixFour.Spec.GeneHash.canonicalBytes' and the FNV-1a
'SixFour.Spec.GeneHash.geneHash' over them. This golden is a set of FIXED preimages with their exact
canonical bytes and resulting address; @GeneHashGoldenTests@ on device must reproduce every
@canonicalBytes@ / @geneId@ EXACTLY.

The fixtures pin two load-bearing facts into the wire contract:

  * NEGATIVE payload values (two's-complement → @UInt64@ bit pattern → LE bytes): the Swift port must
    reinterpret @Int64@ bits, not clamp.
  * PARENT ORDER IS SIGNIFICANT: @child@ and @childSwapped@ carry the same parent SET in opposite
    order and therefore hash DIFFERENTLY. This is the committed decision — a graft is order-sensitive,
    parents are NOT canonicalised to a sorted set — and the golden enforces it so the port cannot
    silently sort.
-}
module SixFour.Codegen.GeneHash
  ( emitGeneHashGolden
  ) where

import qualified Data.Text as T
import           Data.Text (Text)
import           Data.Word (Word8)

import SixFour.Spec.GeneHash (GenePreimage(..), canonicalBytes, fnv1a64, geneHash)
import SixFour.Spec.Trade    (GeneId(..))

-- | The integer content-address of a preimage (the @GeneId@'s reinterpreted 64-bit value).
gid :: GenePreimage -> Int
gid p = let GeneId i = geneHash p in i

-- Fixtures. Parents reference EARLIER fixtures' real addresses, so the chain exercises genuine
-- ancestry commitment (a child's bytes contain its parents' hashes).
originA, originB, child, childSwapped, grandchild :: GenePreimage
originA      = GenePreimage [1000, -2000, 65536, 0] []                                   -- origin, negatives
originB      = GenePreimage [7, 7, 7] []                                                 -- origin
child        = GenePreimage [42] [GeneId (gid originA), GeneId (gid originB)]            -- two parents, ordered
childSwapped = GenePreimage [42] [GeneId (gid originB), GeneId (gid originA)]            -- same set, reversed
grandchild   = GenePreimage [-1] [GeneId (gid child)]                                    -- depth-2 chain

fixtures :: [(Text, GenePreimage)]
fixtures =
  [ ("originA",      originA)
  , ("originB",      originB)
  , ("child",        child)
  , ("childSwapped", childSwapped)
  , ("grandchild",   grandchild)
  ]

emitGeneHashGolden :: Text
emitGeneHashGolden = T.unlines $
  [ "// GENERATED by sixfour-spec / Codegen.GeneHash — do not edit by hand."
  , "// Regenerate with: cabal run spec-codegen."
  , "//"
  , "// Byte-exact golden for the gene content-address (SixFour.Spec.GeneHash)."
  , "// The Swift port must reproduce each `canonicalBytes` (length-prefixed LE) and `geneId`"
  , "// (FNV-1a over those bytes) EXACTLY. Parent order IS significant: `child` and `childSwapped`"
  , "// share a parent set but differ in order and MUST hash differently."
  , ""
  , "enum GeneHashGolden {"
  , "    /// FNV-1a (64-bit) constants: geneId = Int64(bitPattern: fnv1a64(canonicalBytes))."
  , "    static let fnvOffsetBasis: UInt64 = 14695981039346656037"
  , "    static let fnvPrime: UInt64 = 1099511628211"
  , ""
  , "    struct Case {"
  , "        let name: String"
  , "        let payload: [Int]        // canonical Q16 weight bytes"
  , "        let parents: [Int]        // parent GeneIds (Int64 bit-reinterpreted hashes)"
  , "        let canonicalBytes: [UInt8]"
  , "        let fnv1a64: UInt64       // the raw hash"
  , "        let geneId: Int           // = Int64(bitPattern: fnv1a64) — the GeneId"
  , "    }"
  , ""
  , "    static let cases: [Case] = ["
  ]
  ++ map emitCase fixtures ++
  [ "    ]"
  , ""
  , "    /// Convenience: address of each named fixture (order matches `cases`)."
  , "    static let ids: [String: Int] = ["
  , T.intercalate ",\n"
      [ "        " <> tshow nm <> ": " <> tshow (gid p) | (nm, p) <- fixtures ]
  , "    ]"
  , ""
  , "    /// Load-bearing invariant: parent order is significant, so these two differ."
  , "    static let parentOrderIsSignificant: Bool = " <> boolLit (gid child /= gid childSwapped)
  , "}"
  ]

emitCase :: (Text, GenePreimage) -> Text
emitCase (nm, p) = T.intercalate "\n"
  [ "        Case(name: " <> tshow nm <> ","
  , "             payload: " <> intArr (gpPayload p) <> ","
  , "             parents: " <> intArr [ i | GeneId i <- gpParents p ] <> ","
  , "             canonicalBytes: " <> byteArr (canonicalBytes p) <> ","
  , "             fnv1a64: " <> tshow (fnv1a64 (canonicalBytes p)) <> ","
  , "             geneId: " <> tshow (gid p) <> "),"
  ]

intArr :: [Int] -> Text
intArr xs = "[" <> T.intercalate ", " (map tshow xs) <> "]"

byteArr :: [Word8] -> Text
byteArr xs = "[" <> T.intercalate ", " (map tshow xs) <> "]"

tshow :: Show a => a -> Text
tshow = T.pack . show

boolLit :: Bool -> Text
boolLit True  = "true"
boolLit False = "false"
