{- |
Module      : SixFour.Codegen.GenomeFixed
Description : Emit GenomeFixedGolden.swift — the BYTE-EXACT integer gate for the radix genomes.

Where 'SixFour.Codegen.Genome' emits the FLOAT genome projections (tolerance-gated),
this emits the OWNED INTEGER (Q16) projections — exact, no tolerance:
  * 16² → Flat: identity.
  * 4⁴  → 'SixFour.Spec.Quad4Fixed.quad4ProjectFixed' (exact ÷4 opponent-quadrant).
  * 2⁸  → 'SixFour.Spec.SigmaPairFixed' (reconstructPaired ∘ analyzePaired over the
          integer Haar) — the SAME lifting the owned Zig @s4_haar@ runs.

Integers transport exactly as Swift literals; `BranchedPalette.projectQ16` must
reproduce these EXACTLY (`==`), keeping the GIFB global colour table byte-exact
cross-device for every radix.
-}
module SixFour.Codegen.GenomeFixed
  ( emitGenomeFixedGolden
  ) where

import qualified Data.Text as T
import           Data.Text (Text)

import SixFour.Spec.PairTreeFixed  (OKLabI)
import SixFour.Spec.Quad4Fixed     (quad4ProjectFixed)
import SixFour.Spec.SigmaPairFixed (analyzePairedFixed, reconstructPairedFixed)

-- | A deterministic 256-leaf Q16 OKLab fixture (L ∈ [0,2^16], a,b ∈ [±0.4·2^16]).
genomeFixedLeaves :: [OKLabI]
genomeFixedLeaves = take 256 (gen 0x5eed1234)
  where
    gen :: Int -> [OKLabI]
    gen s =
      let s1 = step s; s2 = step s1; s3 = step s2
          l = s1 `mod` 65537
          a = (s2 `mod` 52429) - 26214
          b = (s3 `mod` 52429) - 26214
      in (l, a, b) : gen s3
    step s = (s * 1103515245 + 12345) `mod` 2147483648

emitGenomeFixedGolden :: Text
emitGenomeFixedGolden = T.unlines
  [ "// GENERATED by sixfour-spec / Codegen.GenomeFixed — do not edit by hand."
  , "// Regenerate with: cabal run spec-codegen."
  , "//"
  , "// BYTE-EXACT integer (Q16) gate for the three radix genome projections."
  , "// 16²→Flat (identity) / 4⁴→Quad4Fixed / 2⁸→SigmaPairFixed. All exact integers;"
  , "// BranchedPalette.projectQ16 must reproduce them EXACTLY (no tolerance)."
  , "import simd"
  , ""
  , "enum GenomeFixedGolden {"
  , "    /// The 256-leaf Q16 OKLab fixture."
  , "    static let leaves: [SIMD3<Int32>] = " <> arr leaves
  , ""
  , "    /// 16² → Flat: identity (== leaves)."
  , "    static let flat: [SIMD3<Int32>] = " <> arr leaves
  , ""
  , "    /// 4⁴ → Quad4Fixed.quad4ProjectFixed (exact ÷4 opponent-quadrant projection)."
  , "    static let quad4: [SIMD3<Int32>] = " <> arr quad4Leaves
  , ""
  , "    /// 2⁸ → SigmaPairFixed (integer Haar + exact σ-reflect interleave)."
  , "    static let sigmaPair: [SIMD3<Int32>] = " <> arr sigmaPairLeaves
  , "}"
  ]
  where
    leaves          = genomeFixedLeaves
    quad4Leaves     = quad4ProjectFixed leaves
    sigmaPairLeaves = reconstructPairedFixed (analyzePairedFixed leaves)

simd3 :: OKLabI -> Text
simd3 (l, a, b) = "SIMD3<Int32>(" <> T.intercalate ", " (map (T.pack . show) [l, a, b]) <> ")"

arr :: [OKLabI] -> Text
arr xs = "[" <> T.intercalate ", " (map simd3 xs) <> "]"
