{- |
Module      : SixFour.Codegen.Genome
Description : Emit GenomeGolden.swift — the tolerance gate for the three radix genomes.

The 16²/4⁴/2⁸ controls select the NN GENOME the global palette is projected onto:
  * 16² → Flat (768): identity, the 256 leaves unchanged.
  * 4⁴  → Quad4 (513): the opponent-quadrant projection 'reconstruct ∘ quad4Analyze'.
  * 2⁸  → σ-pair (384): 'reconstructPaired ∘ analyzePaired'.

For the deterministic collapse, what matters at the GIF colour table is each
genome's PROJECTED 256 leaves (the colours the radix selects). This golden pins
those projected leaves for a fixed 256-leaf fixture; the Swift `BranchedPalette.project`
must reproduce them within tolerance (float genome math cannot be bit-exact). Flat
is exact (identity); Quad4 and σ-pair are LOSSY projections that shift colours —
the intentional inductive bias of the 4⁴ / 2⁸ branchings.
-}
module SixFour.Codegen.Genome
  ( emitGenomeGolden
  ) where

import qualified Data.Text as T
import           Data.Text (Text)

import SixFour.Spec.Color        (OKLab(..))
import           SixFour.Spec.Quad4 (quad4Analyze)
import qualified SixFour.Spec.Quad4 as Q4
import SixFour.Spec.SigmaPairHead (analyzePaired, reconstructPaired)

-- | A deterministic 256-leaf OKLab fixture (the genome transforms are size-pinned
-- to 256: Quad4 depth-4 4-ary, σ-pair 128 even leaves → depth-7).
genomeGoldenLeaves :: [OKLab]
genomeGoldenLeaves = take 256 (gen 0x5eed1234)
  where
    gen :: Int -> [OKLab]
    gen s =
      let s1 = step s; s2 = step s1; s3 = step s2
          l = fromIntegral (s1 `mod` 1001) / 1000
          a = fromIntegral (s2 `mod` 801)  / 1000 - 0.4
          b = fromIntegral (s3 `mod` 801)  / 1000 - 0.4
      in OKLab l a b : gen s3
    step s = (s * 1103515245 + 12345) `mod` 2147483648

-- | Emit the Swift golden for the (floating-point) genome projections.
emitGenomeGolden :: Text
emitGenomeGolden = T.unlines
  [ "// GENERATED by sixfour-spec / Codegen.Genome — do not edit by hand."
  , "// Regenerate with: cabal run spec-codegen."
  , "//"
  , "// Tolerance gate for the three radix GENOME projections (16²→Flat / 4⁴→Quad4 /"
  , "// 2⁸→σ-pair). Each is reconstruct(analyze(leaves)) on the σ-pair / Quad4 / flat"
  , "// subspace; BranchedPalette.project must reproduce these within tolerance. Flat"
  , "// is exact (identity); Quad4 + σ-pair are LOSSY projections (the radix bias)."
  , "import simd"
  , ""
  , "enum GenomeGolden {"
  , "    /// The 256-leaf input fixture (OKLab)."
  , "    static let leaves: [SIMD3<Double>] = " <> arr leaves
  , ""
  , "    /// 16² → Flat: identity (== leaves)."
  , "    static let flat: [SIMD3<Double>] = " <> arr leaves
  , ""
  , "    /// 4⁴ → Quad4: reconstruct(quad4Analyze(leaves)) — opponent-quadrant projection."
  , "    static let quad4: [SIMD3<Double>] = " <> arr quad4Leaves
  , ""
  , "    /// 2⁸ → σ-pair: reconstructPaired(analyzePaired(leaves)) — σ-mirror projection."
  , "    static let sigmaPair: [SIMD3<Double>] = " <> arr sigmaPairLeaves
  , "}"
  ]
  where
    leaves         = genomeGoldenLeaves
    quad4Leaves     = Q4.reconstruct (quad4Analyze leaves)
    sigmaPairLeaves = reconstructPaired (analyzePaired leaves)

dbl :: Double -> Text
dbl = T.pack . show

simd3d :: OKLab -> Text
simd3d (OKLab l a b) = "SIMD3<Double>(" <> T.intercalate ", " (map dbl [l, a, b]) <> ")"

arr :: [OKLab] -> Text
arr xs = "[" <> T.intercalate ", " (map simd3d xs) <> "]"
