{- |
Module      : SixFour.Codegen.GenomeCarrier
Description : Emit GenomeCarrierGolden.swift — the byte-exact gate for the GenomeCarrier Swift port.

The hand-written Swift port @GenomeCarrier@ mirrors 'SixFour.Spec.GenomeCarrier' (the S4GN
genome-in-GIF codec: Int32 LE Q16 + CRC32 in a GIF89a Application-Extension). The golden is the
encoded byte stream of a FIXED canonical payload; @GenomeCarrierGoldenTests@ must reproduce it
EXACTLY and round-trip back to the payload.
-}
module SixFour.Codegen.GenomeCarrier
  ( emitGenomeCarrierGolden
  ) where

import qualified Data.Text as T
import           Data.Text (Text)
import           Data.Word (Word8)

import SixFour.Spec.GenomeCarrier (S4GNHeader(..), GenomePayload(..), encodeGenomeBlock)

-- | A fixed canonical 384-DOF payload (major 1, minor 0, dof 384) with a deterministic coefficient
-- pattern spanning negatives — the int16-truncation trap.
goldenPayload :: GenomePayload
goldenPayload = GenomePayload
  (S4GNHeader 1 0 0 384 0 0 0)
  [ (i * 433 - 70000) | i <- [0 .. 383] ]

emitGenomeCarrierGolden :: Text
emitGenomeCarrierGolden = T.unlines
  [ "// GENERATED by sixfour-spec / Codegen.GenomeCarrier — do not edit by hand."
  , "// Regenerate with: cabal run spec-codegen."
  , "//"
  , "// Byte-exact golden for the S4GN genome-in-GIF codec (SixFour.Spec.GenomeCarrier)."
  , "// The Swift GenomeCarrier.encode must reproduce `encoded` EXACTLY and extract back to it."
  , ""
  , "enum GenomeCarrierGolden {"
  , "    /// header fields: major, minor, flags, dof, radix, deviceIdHash, btCompares."
  , "    static let header: [Int] = [1, 0, 0, 384, 0, 0, 0]"
  , ""
  , "    /// the Int32 Q16 coefficients (384)."
  , "    static let coeffs: [Int] = " <> intArr (gpCoeffs goldenPayload)
  , ""
  , "    /// the full GIF89a Application-Extension byte stream."
  , "    static let encoded: [UInt8] = " <> byteArr (encodeGenomeBlock goldenPayload)
  , "}"
  ]

intArr :: [Int] -> Text
intArr xs = "[" <> T.intercalate ", " (map (T.pack . show) xs) <> "]"

byteArr :: [Word8] -> Text
byteArr xs = "[" <> T.intercalate ", " (map (T.pack . show) xs) <> "]"
