{- |
Module      : SixFour.Codegen.GenomePair
Description : Emit GenomePairGolden.swift — the byte-exact gate for the GenomePair Swift port.

The hand-written Swift port @GenomePair@ mirrors 'SixFour.Spec.GenomePair.sampleOrthogonalPair'
(two distinct, σ-valid, EXACTLY-orthogonal candidate displacements by disjoint generator bands).
Because the construction is pure integer (Q16) list ops, the golden is plain Swift @Int@ literals —
no tolerance — and @GenomePairGoldenTests@ must reproduce @(δ_A, δ_B)@ EXACTLY, then check the
orthogonality (@genomeInner == 0@) and band-disjointness hold on the Swift side.

Fixture: a fixed depth-7 genome (128 generators), proposed via the COLD-START path (empty ranking),
matching what the A/B screen shows on a day-1 capture before θ is trained.
-}
module SixFour.Codegen.GenomePair
  ( emitGenomePairGolden
  ) where

import qualified Data.Text as T
import           Data.Text (Text)

import SixFour.Spec.PairTreeFixed (analyzeFixed, reconstructFixed)
import SixFour.Spec.GenomePair    (sampleOrthogonalPair)

-- | A fixed 128-generator genome (depth-7 σ-pair Haar tree) from a deterministic Q16 pixel list.
goldenPixels :: [(Int, Int, Int)]
goldenPixels =
  [ ( (i * 263 + 11) `mod` 60000
    , (i * 131 + 7 ) `mod` 50000 - 25000
    , (i * 197 + 5 ) `mod` 50000 - 25000 )
  | i <- [0 .. 127] ]

-- | Emit the Swift golden-vector fixture for the orthogonal A/B pair.
emitGenomePairGolden :: Text
emitGenomePairGolden = T.unlines
  [ "// GENERATED by sixfour-spec / Codegen.GenomePair — do not edit by hand."
  , "// Regenerate with: cabal run spec-codegen."
  , "//"
  , "// Byte-exact golden for the orthogonal A/B pair (SixFour.Spec.GenomePair). Q16 integers, no"
  , "// tolerance; the Swift GenomePair.sampleOrthogonalPair must reproduce (δ_A, δ_B) EXACTLY."
  , ""
  , "enum GenomePairGolden {"
  , "    /// The fixed 128-generator base genome (reconstructFixed g0), flattened (l,a,b)."
  , "    static let generators: [Int] = " <> intArr (flat gens)
  , ""
  , "    /// sampleOrthogonalPair g0 [] (cold start): candidate A displacement, flattened."
  , "    static let deltaA: [Int] = " <> intArr (flat da)
  , ""
  , "    /// sampleOrthogonalPair g0 [] (cold start): candidate B displacement, flattened."
  , "    static let deltaB: [Int] = " <> intArr (flat db)
  , "}"
  ]
  where
    g0       = analyzeFixed goldenPixels
    gens     = reconstructFixed g0
    (da, db) = sampleOrthogonalPair g0 []
    flat ts  = concatMap (\(a, b, c) -> [a, b, c]) ts

intArr :: [Int] -> Text
intArr xs = "[" <> T.intercalate ", " (map (T.pack . show) xs) <> "]"
