{- |
Module      : SixFour.Codegen.Golden
Description : Emit look_net_golden.json — the bit-exact forward correctness gate.

A hand-rolled JSON artifact (no new dep; mirrors @app/Gen.hs@'s hand-rolled
manifest) holding the deterministic test weights + a few fixed input fixtures +
the Haskell-computed reference outputs ('SixFour.Spec.LookNetEval.forward'). Any
port (MLX trainer, PyTorch fallback, future hand-written Swift forward) loads it
and must reproduce the outputs to tolerance.

== Floats are transported as IEEE-754 HEX, not decimals

To make weight/input transport provably exact REGARDLESS of any JSON decoder's
decimal-float handling (Swift @JSONDecoder@ has a documented precision history;
see the plan), every @Double@ is emitted as its 16-hex-digit big-endian IEEE-754
bit pattern (@castDoubleToWord64@). Decode by reinterpreting the bits
(@int(s,16)@+@struct@ in Python; @Double(bitPattern: UInt64(s, radix: 16))@ in
Swift) — never by parsing a decimal. Outputs are then compared within a
TOLERANCE (the @meta.tolerance@ field, 1e-6) because cross-language matmul
summation order diverges at the ULP level; bit-equal outputs are not achievable.
-}
module SixFour.Codegen.Golden
  ( emitLookNetGolden
  , hexDouble
  ) where

import qualified Data.Text           as T
import           Data.Text           (Text)
import qualified Data.Vector.Unboxed as U
import           Data.Word           (Word64)
import           GHC.Float           (castDoubleToWord64)
import           Numeric             (showHex)

import SixFour.Spec.Color    (OKLab(..))
import SixFour.Spec.GMM
  ( GMM, Gaussian(..), normalizeGMM, mixtureMean, mixtureCovariance )
import SixFour.Spec.Tensor   (Tensor1(..))
import SixFour.Spec.LookNet   (modelDim, gmmTokenDim)
import SixFour.Spec.LookNetR  (coreDepth)
import SixFour.Spec.LookNetD  (decoderLevelDims, decoderOutputDim, DecoderOutput(..), reconstructSigmaPair)
import SixFour.Spec.Loss
  ( defaultLossWeights, fidelityLossLeaves, coverageLossLeaves
  , beautyLossLeaves, lookNetLossLeaves )
import SixFour.Spec.LookNetEval

-- =============================================================================
-- Hex (IEEE-754 bit pattern) formatting
-- =============================================================================

-- | A @Double@ as its 16-hex-digit big-endian IEEE-754 bit pattern (no @0x@
-- prefix, zero-padded). Exact and decoder-agnostic.
hexDouble :: Double -> Text
hexDouble d =
  let w   = castDoubleToWord64 d :: Word64
      hx  = T.pack (showHex w "")
      pad = T.replicate (16 - T.length hx) "0"
  in pad <> hx

-- a JSON array of quoted hex strings
hexArr :: [Double] -> Text
hexArr xs = "[" <> T.intercalate ", " (map (quote . hexDouble) xs) <> "]"

hexArrV :: U.Vector Double -> Text
hexArrV = hexArr . U.toList

intArr :: [Int] -> Text
intArr xs = "[" <> T.intercalate ", " (map (T.pack . show) xs) <> "]"

quote :: Text -> Text
quote t = "\"" <> t <> "\""

-- a {"shape": [..], "hex": [..]} tensor object
tensorObj :: [Int] -> [Double] -> Text
tensorObj shp vals =
  "{ \"shape\": " <> intArr shp <> ", \"hex\": " <> hexArr vals <> " }"

-- =============================================================================
-- The emitter
-- =============================================================================

emitLookNetGolden :: Text
emitLookNetGolden = T.unlines $
  [ "{"
  , "  \"_comment\": \"GENERATED by sixfour-spec / Codegen.Golden — do not edit by hand. Regenerate with: cabal run spec-codegen.\","
  , "  \"meta\": {"
  , "    \"encoding\": \"ieee754-hex-word64-be\","
  , "    \"encoding_note\": \"every float is the 16-hex-digit IEEE-754 double bit pattern; decode via bit pattern (int(s,16)+struct / Double(bitPattern:)), NOT decimal parsing.\","
  , "    \"tolerance\": 1e-6,"
  , "    \"tolerance_note\": \"weights+inputs transport bit-exact; OUTPUTS compared within tolerance — cross-language matmul summation order differs at the ULP level.\","
  , "    \"model_dim\": " <> tshow modelDim <> ","
  , "    \"core_depth\": " <> tshow coreDepth <> ","
  , "    \"gmm_token_dim\": " <> tshow gmmTokenDim <> ","
  , "    \"decoder_out_dim\": " <> tshow decoderOutputDim <> ","
  , "    \"decoder_level_dims\": " <> intArr decoderLevelDims <> ","
  , "    \"loss_weights\": { \"fidelity\": 1.0, \"coverage\": 1.0, \"beauty\": 1.0 },"
  , "    \"loss_note\": \"per-case loss = lookNetLossLeaves defaultLossWeights (reconstructSigmaPair output) inputGmm; fidelity = Bures-W^2 to input_gmm moments, coverage = 1 - gamut fraction, beauty = -sum Ou-Luo over adjacent sigma-pairs. Reproduce within meta.tolerance.\","
  , "    \"weight_layout\": \"row-major (out, in) — the PyTorch/MLX nn.Linear.weight layout; weights are RAW (pre-σ-mask), each port applies the mask in its forward.\""
  , "  },"
  , "  \"weights\": {"
  , "    \"phi\": "    <> tensorObj [64, 10] (U.toList (wPhi w))   <> ","
  , "    \"w1\": "     <> tensorObj [64, 64] (U.toList (wW1 w))    <> ","
  , "    \"w2\": "     <> tensorObj [64, 64] (U.toList (wW2 w))    <> ","
  , "    \"halt_w\": " <> tensorObj [1, 2]   (U.toList (wHaltW w)) <> ","
  , "    \"halt_b\": " <> tensorObj [1]      [wHaltB w]            <> ","
  , "    \"heads\": [ " <> T.intercalate ", " headObjs <> " ]"
  , "  },"
  , "  \"cases\": [ " <> T.intercalate ", " caseObjs <> " ]"
  , "}"
  ]
  where
    w = deterministicTestWeights

    headObjs =
      [ tensorObj [dk, 64] (U.toList hv)
      | ((dk, _), hv) <- zip headShapes (wHeads w) ]

    caseObjs = map caseObj testCases
    caseObj (name, toks) =
      let tr      = forward w toks
          n       = length toks
          tokFlat = concat [ U.toList t | Tensor1 t <- toks ]
          -- The loss reference: the forward output (384 SigmaPairTree coeffs) →
          -- 256-leaf σ-pair palette → the three component losses + total, against
          -- the case's input GMM (the tokens, moment-matched). Computed with the
          -- SAME spec functions the MLX port mirrors (Spec.Loss leaf cores).
          inGmm   = gmmFromTokens toks
          leaves  = reconstructSigmaPair (DecoderOutput (Tensor1 (U.fromList (ftOutput tr))))
          lFid    = fidelityLossLeaves leaves inGmm
          lCov    = coverageLossLeaves leaves
          lBeauty = beautyLossLeaves   leaves
          lTotal  = lookNetLossLeaves  defaultLossWeights leaves inGmm
          -- The moment-matched input Gaussian (mean + 6 upper-tri cov), so the
          -- port computes Bures fidelity without reimplementing the pooling/total-
          -- covariance math (it can verify against these moments directly).
          OKLab gmL gmA gmB = mixtureMean inGmm
          (cLL,cLa,cLb,cAA,cAB,cBB) = mixtureCovariance inGmm
      in T.concat
         [ "{ \"name\": ", quote (T.pack name)
         , ", \"tokens\": ", tensorObj [n, 10] tokFlat
         , ", \"context\": ", hexArr (ftContext tr)
         , ", \"halts\": ",   hexArr (ftHalts tr)
         , ", \"output\": ",  hexArr (ftOutput tr)
         , ", \"input_gmm_mean\": ", hexArr [gmL, gmA, gmB]
         , ", \"input_gmm_cov\": ",  hexArr [cLL, cLa, cLb, cAA, cAB, cBB]
         , ", \"loss\": { \"fidelity\": ", quote (hexDouble lFid)
         , ", \"coverage\": ", quote (hexDouble lCov)
         , ", \"beauty\": ",   quote (hexDouble lBeauty)
         , ", \"total\": ",    quote (hexDouble lTotal), " }"
         , " }" ]

-- | Build the input GMM for a golden case from its 10-D tokens. Each token
-- @[μL,μa,μb, ΣLL,ΣLa,ΣLb,Σaa,Σab,Σbb, w]@ is one mixture component; the mixture
-- is renormalised (matching 'SixFour.Spec.LookNet.poolToGMM' on a single-frame
-- stack, sans the per-frame split). This is the loss's fidelity target.
gmmFromTokens :: [Tensor1 10 Double] -> GMM
gmmFromTokens toks =
  normalizeGMM
    [ Gaussian (OKLab (v U.! 0) (v U.! 1) (v U.! 2))
               (v U.! 3, v U.! 4, v U.! 5, v U.! 6, v U.! 7, v U.! 8)
               (v U.! 9)
    | Tensor1 v <- toks ]

tshow :: Show a => a -> Text
tshow = T.pack . show
