{- |
Module      : SixFour.Codegen.Governance
Description : Emit GovernanceContract.swift — pin the DERIVED social-body sizes and the constitution ranking for a fixed roster. Integer/enum-exact, so the hand-written Swift port is gated behavior-exact with no floating point, no identity binding, no persistence.

This is the ONLY port-ready slice of the swap-economy spec: "SixFour.Spec.GuildScale" (pure @Int@
sizes) and the "SixFour.Spec.Governance" 'govern' ordering over ints/'Grade' enum. Everything else —
the content-address 'SixFour.Spec.Trade.GeneId' (needs a real hash), 'SixFour.Spec.Trade.CreatorId'
(needs a Game Center player-id binding), 'SixFour.Spec.Role' (float over the real 384-DOF genome), and
the CloudKit schema for the ledger folds — is deliberately NOT emitted here; it is not ready.

The golden is a fixed 'Member' roster and its expected 'govern' order under each constitution, so a
hand-written Swift @Governance.govern@ can be verified list-exact. Grades emit as @0=Reject … 4=Excellent@.
-}
module SixFour.Codegen.Governance
  ( emitGovernanceContract
  ) where

import           Data.Text (Text)
import qualified Data.Text as T

import           SixFour.Spec.GuildScale (councilSize, dunbarLayers, guildCap, quorum)
import           SixFour.Spec.Governance
                   (Constitution(..), Grade(..), Member(..), govern)
import           SixFour.Spec.Trade      (CreatorId(..))

-- | A fixed golden roster — deliberately full of near-ties so the tie-break and the majority-judgment
-- order are actually exercised (ids 1&2 share prestige; grades vary).
goldenRoster :: [Member]
goldenRoster =
  [ Member (CreatorId 0) 5  3 1.0 [Good, Good, Fair]
  , Member (CreatorId 1) 5  9 0.5 [Excellent, Reject]
  , Member (CreatorId 2) 9  1 0.9 [Fair, Fair, Fair]
  , Member (CreatorId 3) 2 12 1.0 [Poor, Good]
  , Member (CreatorId 4) 9  4 0.7 [Excellent, Good, Good]
  ]

idOf :: Member -> Int
idOf (Member (CreatorId i) _ _ _ _) = i

rankedIds :: Constitution -> [Int]
rankedIds c = map idOf (govern c goldenRoster)

-- | Emit the governance contract: the derived sizes + the golden roster and its expected orderings.
emitGovernanceContract :: Text
emitGovernanceContract = T.unlines
  [ "// GENERATED by sixfour-spec / Codegen.Governance — do not edit by hand."
  , "// Regenerate with: cabal run spec-codegen."
  , "//"
  , "// Pins the DERIVED sizes (SixFour.Spec.GuildScale) and the constitution ranking"
  , "// (SixFour.Spec.Governance.govern) for a fixed roster. Integer/enum-exact — no float,"
  , "// no identity binding, no persistence. The hand-written Swift Governance is gated here."
  , ""
  , "enum GovernanceContract {"
  , "    // ── Derived social-body sizes (SixFour.Spec.GuildScale) ──"
  , "    static let councilSize: Int = " <> tshow councilSize
  , "    static let quorum: Int = " <> tshow quorum
  , "    static let guildCap: Int = " <> tshow guildCap
  , "    static let dunbarLayers: [Int] = " <> intArr (dunbarLayers 6)
  , ""
  , "    // ── Golden roster (leader-first orderings below verify govern) ──"
  , "    // grades: 0=Reject 1=Poor 2=Fair 3=Good 4=Excellent"
  , "    static let rosterIds: [Int] = " <> intArr (map idOf goldenRoster)
  , "    static let rosterPrestige: [Int] = " <> intArr [ p | Member _ p _ _ _ <- goldenRoster ]
  , "    static let rosterTenure: [Int] = " <> intArr [ t | Member _ _ t _ _ <- goldenRoster ]
  , "    static let rosterGrades: [[Int]] = " <> intGrid [ map fromEnum gs | Member _ _ _ _ gs <- goldenRoster ]
  , ""
  , "    // ── Expected govern(...) orderings, most-authority-first ──"
  , "    static let rankMeritocracy: [Int] = " <> intArr (rankedIds Meritocracy)
  , "    static let rankGerontocracy: [Int] = " <> intArr (rankedIds Gerontocracy)
  , "    static let rankMajorityJudgment: [Int] = " <> intArr (rankedIds MajorityJudgment)
  , "}"
  ]

tshow :: Show a => a -> Text
tshow = T.pack . show

intArr :: [Int] -> Text
intArr xs = "[" <> T.intercalate ", " (map tshow xs) <> "]"

intGrid :: [[Int]] -> Text
intGrid rows = "[" <> T.intercalate ", " (map intArr rows) <> "]"
