{- |
Module      : SixFour.Codegen.GridAxis
Description : Emit GridAxisGolden.swift — pin the 2-axis palette layout + GridScript surface.

The Review screen's @PaletteGridView@ hand-ports 'SixFour.Spec.GridAxis.gridLayout' as
@GridLayout.swift@'s @GridAxis.layout@ (rank-sort placement with the @(scalar, index)@
tie-break), then turns the @[[Int]]@ grid into an @Order@ ('Order.fromGrid') that
@GridScript.surfaceColors@ permutes the palette by. Only @Order.fromGrid@ was
golden-pinned; the LAYOUT step and the end-to-end surface were not.

This emits one golden that pins the whole chain for a fixed fixture and the @L@×@a@
axis pair: the expected @gridLayout@ grid and the expected @surfaceBitmap@ over an
identity palette (= the screen-rank→slot sequence).

__Precision-independence by construction.__ The spec sorts on @Double@ keys, the Swift
port on @Float@; a byte-exact @[[Int]]@ golden must not depend on which. The fixture
uses __dyadic__ coordinates (@i\/256@, @j\/256 − ½@ with @j = 97·i mod 256@): each is
exactly representable in both @Float@ and @Double@, and the coprime stride makes every
per-axis sort key distinct and well-separated, so the placement is identical in either
precision. No ties, no rounding flips.
-}
module SixFour.Codegen.GridAxis
  ( emitGridAxisGolden
  ) where

import qualified Data.Text as T
import           Data.Text (Text)

import SixFour.Spec.Color     (OKLab(..))
import SixFour.Spec.GridAxis  (GridAxis(..), IndexedColor(..), gridSide, gridCells, gridLayout)
import SixFour.Spec.GridScript (reviewAxisScript, surfaceBitmap)

-- | 256 colours with dyadic, well-separated coordinates (see the module note). Index
-- is the array position; @L = i\/256@, @a = (97·i mod 256)\/256 − ½@, @b@ similarly.
gridGoldenColors :: [IndexedColor]
gridGoldenColors =
  [ IndexedColor i (OKLab (fromIntegral i / 256)
                          (fromIntegral ((i * 97) `mod` 256) / 256 - 0.5)
                          (fromIntegral ((i * 53) `mod` 256) / 256 - 0.5))
  | i <- [0 .. gridCells - 1] ]

-- | Emit the Swift golden for the 2-axis layout (x = L, y = a) + GridScript surface.
emitGridAxisGolden :: Text
emitGridAxisGolden = T.unlines
  [ "// GENERATED by sixfour-spec / Codegen.GridAxis — do not edit by hand."
  , "// Regenerate with: cabal run spec-codegen."
  , "//"
  , "// Pins GridAxis.layout (SixFour.Spec.GridAxis.gridLayout) and the GridScript"
  , "// surface (SixFour.Spec.GridScript.surfaceBitmap over the derived Order) for a"
  , "// fixed dyadic fixture + the L×a axis pair. Integer-exact (precision-independent)."
  , "import simd"
  , ""
  , "enum GridAxisGolden {"
  , "    static let side: Int = " <> T.pack (show gridSide)
  , "    static let xAxis: String = \"L\""
  , "    static let yAxis: String = \"a\""
  , ""
  , "    /// Input fixture in slot-index order (L, a, b); index = array position."
  , "    static let colors: [SIMD3<Double>] = " <> simd3dArr (map icOKLab gridGoldenColors)
  , ""
  , "    /// Expected gridLayout(L, a, colors) — result[row][col] -> slot."
  , "    static let gridLayout: [[Int]] = " <> intGrid layout
  , ""
  , "    /// Expected surface: surfaceBitmap over identity palette = screen-rank -> slot."
  , "    static let surface: [Int] = " <> intArr surface
  , "}"
  ]
  where
    layout  = gridLayout AxisL AxisA gridGoldenColors
    surface = surfaceBitmap (reviewAxisScript gridSide AxisL AxisA gridGoldenColors)
                            [0 .. gridCells - 1]

icOKLab :: IndexedColor -> OKLab
icOKLab (IndexedColor _ lab) = lab

dbl :: Double -> Text
dbl = T.pack . show

simd3d :: OKLab -> Text
simd3d (OKLab l a b) = "SIMD3<Double>(" <> T.intercalate ", " (map dbl [l, a, b]) <> ")"

simd3dArr :: [OKLab] -> Text
simd3dArr xs = "[" <> T.intercalate ", " (map simd3d xs) <> "]"

intArr :: [Int] -> Text
intArr xs = "[" <> T.intercalate ", " (map (T.pack . show) xs) <> "]"

intGrid :: [[Int]] -> Text
intGrid rows = "[" <> T.intercalate ", " (map intArr rows) <> "]"
