{- |
Module      : SixFour.Codegen.LookCategory
Description : Emit LookCategoryContract.swift — the look taxonomy for the Review screen.

The north-star taxonomy ('SixFour.Spec.LookCategory') made consumable on device: the
category NAMES and their fixed OKLab PROTOTYPES, plus golden (descriptor → category)
cases. The Swift port @SFLookCategory@ does nearest-prototype 'classify' against these
constants and is pinned by @LookCategoryGoldenTests@. The Review screen labels the
rendered palette's look with @SFLookCategory.name@ — the first visible surface of the
personalization spine (the learned per-user step lands once the look-net forward pass
is wired).
-}
module SixFour.Codegen.LookCategory
  ( emitLookCategoryContract
  ) where

import qualified Data.Text as T
import           Data.Text (Text)

import SixFour.Spec.Color        (OKLab(..))
import SixFour.Spec.LookCategory (allLookCategories, categoryPrototype, classify, lookDescriptor)

-- | Golden descriptors: each prototype and a tiny diagonal offset of it. The
-- prototypes are well-separated (> 0.1 apart), so an offset of 0.01 still classifies
-- to the same category in BOTH Double (spec) and Float (Swift) — precision-safe.
goldenDescs :: [OKLab]
goldenDescs = protos ++ map nudge protos
  where
    protos = map categoryPrototype allLookCategories
    nudge (OKLab l a b) = lookDescriptor [OKLab (l + 0.01) (a + 0.01) (b + 0.01)]

emitLookCategoryContract :: Text
emitLookCategoryContract = T.unlines
  [ "// GENERATED by sixfour-spec / Codegen.LookCategory — do not edit by hand."
  , "// Regenerate with: cabal run spec-codegen."
  , "//"
  , "// Look taxonomy for the Review screen (SixFour.Spec.LookCategory): category names +"
  , "// fixed OKLab prototypes + golden (descriptor → category) cases. The Swift port"
  , "// SFLookCategory classifies against these and is pinned by LookCategoryGoldenTests."
  , "import simd"
  , ""
  , "enum LookCategoryContract {"
  , "    /// Category names, in classify tie-break order."
  , "    static let names: [String] = " <> strArr (map show allLookCategories)
  , ""
  , "    /// Fixed OKLab prototypes (L, a, b) — the nearest-prototype anchors."
  , "    static let prototypes: [SIMD3<Double>] = " <> oklabArr (map categoryPrototype allLookCategories)
  , ""
  , "    /// Golden descriptors (L, a, b)."
  , "    static let goldenDescriptors: [SIMD3<Double>] = " <> oklabArr goldenDescs
  , ""
  , "    /// classify(goldenDescriptors[i]) — the expected category index."
  , "    static let goldenCategories: [Int] = " <> intArr (map (fromEnum . classify) goldenDescs)
  , "}"
  ]

dbl :: Double -> Text
dbl = T.pack . show

oklab :: OKLab -> Text
oklab (OKLab l a b) = "SIMD3<Double>(" <> T.intercalate ", " (map dbl [l, a, b]) <> ")"

oklabArr :: [OKLab] -> Text
oklabArr xs = "[" <> T.intercalate ", " (map oklab xs) <> "]"

strArr :: [String] -> Text
strArr xs = "[" <> T.intercalate ", " [ "\"" <> T.pack s <> "\"" | s <- xs ] <> "]"

intArr :: [Int] -> Text
intArr xs = "[" <> T.intercalate ", " (map (T.pack . show) xs) <> "]"
