{- |
Module      : SixFour.Codegen.LookNetSwift
Description : Emit LookNetGolden.swift — tolerance gate for the Swift look-NN forward.

The MLX trainer, the PyTorch fallback, and the hand-written on-device Swift
forward must all reproduce 'SixFour.Spec.LookNetEval.forward' (the spec oracle).
The JSON golden ("SixFour.Codegen.Golden") gates the Python ports; THIS module
emits the same fixture as a Swift file so @SixFourTests@ can gate the
hand-written Swift forward against the very same oracle.

Same deterministic RAW weights ('deterministicTestWeights'), same three token
cases ('testCases'). Every 'Double' is its 16-hex-digit big-endian IEEE-754 bit
pattern, concatenated per tensor — the Swift side decodes with
@Double(bitPattern:)@, so weights and inputs transfer bit-exact. The forward is
float matmul whose summation order diverges across languages, so the OUTPUTS
(pooled context, per-step halts, 384-D SigmaPairTree coefficients) are gated
within @1e-6@, matching the JSON golden's tolerance.
-}
module SixFour.Codegen.LookNetSwift
  ( emitLookNetSwiftGolden
  ) where

import qualified Data.Text as T
import           Data.Text (Text)
import qualified Data.Vector.Unboxed as U
import           Numeric (showHex)
import           Data.Word (Word64)
import           GHC.Float (castDoubleToWord64)

import SixFour.Spec.Tensor    (Tensor1(..))
import SixFour.Spec.LookNet   (modelDim, gmmTokenDim)
import SixFour.Spec.LookNetR  (coreDepth)
import SixFour.Spec.LookNetD  (decoderLevelDims, decoderOutputDim)
import SixFour.Spec.LookNetEval
  ( LookNetWeights(..), deterministicTestWeights
  , ForwardTrace(..), forward, testCases )

emitLookNetSwiftGolden :: Text
emitLookNetSwiftGolden = T.unlines (header ++ caseLines ++ footer)
  where
    w = deterministicTestWeights

    header =
      [ "// GENERATED by sixfour-spec / Codegen.LookNetSwift — do not edit by hand."
      , "// Regenerate with: cabal run spec-codegen."
      , "//"
      , "// Tolerance gate for the hand-written Swift look-NN forward pass"
      , "// (LookNetForward) against the spec oracle (SixFour.Spec.LookNetEval.forward)."
      , "// Same deterministic RAW weights, same 3 token cases. Each Double is its"
      , "// 16-hex-digit big-endian IEEE-754 bit pattern, concatenated per tensor;"
      , "// Swift decodes via Double(bitPattern:). Float matmul order diverges across"
      , "// languages, so the outputs are gated within `tolerance`."
      , ""
      , "enum LookNetGolden {"
      , "    static let modelDim = " <> tshow modelDim
      , "    static let gmmTokenDim = " <> tshow gmmTokenDim
      , "    static let coreDepth = " <> tshow coreDepth
      , "    static let decoderOutputDim = " <> tshow decoderOutputDim
      , "    static let tolerance = 1e-6"
      , "    static let decoderLevelDims: [Int] = " <> intArr decoderLevelDims
      , ""
      , "    // --- RAW weights (row-major (out, in)), IEEE-754 hex ---"
      , "    static let phiHex = " <> q (hexCatV (wPhi w))
      , "    static let w1Hex = " <> q (hexCatV (wW1 w))
      , "    static let w2Hex = " <> q (hexCatV (wW2 w))
      , "    static let haltWHex = " <> q (hexCatV (wHaltW w))
      , "    static let haltBHex = " <> q (hexDouble (wHaltB w))
      , "    static let headHex: [String] = ["
          <> T.intercalate ", " [ q (hexCatV h) | h <- wHeads w ] <> "]"
      , ""
      , "    struct Case {"
      , "        let name: String"
      , "        let tokenCount: Int"
      , "        let tokensHex: String   // tokenCount * gmmTokenDim doubles"
      , "        let contextHex: String  // modelDim doubles"
      , "        let haltsHex: String    // coreDepth doubles"
      , "        let outputHex: String   // decoderOutputDim doubles"
      , "    }"
      , ""
      , "    static let cases: [Case] = ["
      ]

    caseLines = map caseLit testCases

    footer =
      [ "    ]"
      , "}"
      ]

caseLit :: (String, [Tensor1 10 Double]) -> Text
caseLit (name, tokens) =
  let tr   = forward deterministicTestWeights tokens
      toks = concat [ U.toList v | Tensor1 v <- tokens ]
  in T.concat
       [ "        Case(name: ", q (T.pack name)
       , ", tokenCount: ", tshow (length tokens)
       , ", tokensHex: ", q (hexCat toks)
       , ", contextHex: ", q (hexCat (ftContext tr))
       , ", haltsHex: ", q (hexCat (ftHalts tr))
       , ", outputHex: ", q (hexCat (ftOutput tr))
       , "),"
       ]

-- ---------------------------------------------------------------------------
-- Emitters
-- ---------------------------------------------------------------------------

tshow :: Show a => a -> Text
tshow = T.pack . show

q :: Text -> Text
q t = "\"" <> t <> "\""

intArr :: [Int] -> Text
intArr xs = "[" <> T.intercalate ", " (map tshow xs) <> "]"

-- | A 'Double' as its 16-hex-digit big-endian IEEE-754 bit pattern (zero-padded).
hexDouble :: Double -> Text
hexDouble d =
  let wd = castDoubleToWord64 d :: Word64
      hx = T.pack (showHex wd "")
  in T.replicate (16 - T.length hx) "0" <> hx

hexCat :: [Double] -> Text
hexCat = T.concat . map hexDouble

hexCatV :: U.Vector Double -> Text
hexCatV = hexCat . U.toList
