{- |
Module      : SixFour.Codegen.MaskedBand
Description : Emit @MaskedBandGolden.swift@ — the device-alignment gate for the JEPA encoder's learned forward (the 9-D @featuresB@ map + the 63-param @theta_B@ predictor).

The current JEPA encoder is the FROZEN reversible lift (zero params) plus the ONLY
learned object, the 63-param @theta_B@ masked-band predictor
("SixFour.Spec.MaskedBandPrediction"). There is NO Core AI in this chain: @theta_B@
is a hand-written Swift\/Accelerate dot product. This golden pins that hand-written
forward to the Haskell spec: the committed Q16 byte ('predictMaskedBand') must match
EXACTLY (integer, no tolerance) and the Mac-side @rawMaskedBand@ within tolerance
(float summation order diverges at the ULP level, the same convention
"SixFour.Codegen.PaletteValue" uses).

A fixed deterministic @theta_B@ (length 'paramCountB' = 63) plus a handful of
@(coarse, detail, maskedBand)@ cases chosen away from half-quantum boundaries, so the
byte is genuinely bit-exact. Doubles are emitted as round-trippable decimal literals
(Haskell @show@ ⟷ Swift @Double@ literal both use correct IEEE-754 rounding).

GHC-boot-only. Consumed by @app/Spec.hs@ (writes @SixFour/Generated/MaskedBandGolden.swift@).
-}
module SixFour.Codegen.MaskedBand
  ( emitMaskedBandGolden
  , goldenTheta
  ) where

import           Data.Text (Text)
import qualified Data.Text as T

import SixFour.Spec.OctreeCell        (Detail)
import SixFour.Spec.MaskedBandPrediction
  ( paramCountB, numBands, featureCountB
  , rawMaskedBand, predictMaskedBand )

-- | A fixed, deterministic @theta_B@ (63 params, one 9-wide row per band): a small
-- varied affine pattern, NOT all-zero (so the gate exercises real coefficients).
goldenTheta :: [Double]
goldenTheta = [ fromIntegral ((i * 37) `mod` 13 - 6) * 0.03 | i <- [0 .. paramCountB - 1] ]

-- | The @(coarse, full 7-band detail, maskedBand)@ cases. Coarse + sibling magnitudes
-- are moderate (well inside the Q16 domain) and chosen so @rawMaskedBand * 65536@ is not
-- near a half-integer, making the committed byte bit-exact across Haskell and Swift.
goldenCases :: [(Int, Detail, Int)]
goldenCases =
  [ (0,      (0, 0, 0, 0, 0, 0, 0),            0)   -- floor-ish: raw = theta row . [1,0..]
  , (4000,   (0, 100, 0, 0, 0, 0, 0),          0)   -- one visible sibling
  , (20000,  (3000, 500, -200, 100, 0, 0, 0),  1)   -- mixed siblings, band 1 masked
  , (60000,  (-1000, 2000, -3000, 0, 0, 0, 0), 3)   -- near top of range, band 3
  , (-5000,  (100, -100, 200, -200, 0, 0, 0),  2)   -- NEGATIVE coarse (sign path), band 2
  ]

emitMaskedBandGolden :: Text
emitMaskedBandGolden = T.unlines $
  [ "// GENERATED by sixfour-spec / Codegen.MaskedBand — do not edit by hand."
  , "// Regenerate with: cabal run spec-codegen."
  , "//"
  , "// Device-alignment gate for the JEPA encoder's learned forward: the 9-D featuresB"
  , "// map + the 63-param theta_B predictor (SixFour.Spec.MaskedBandPrediction). The"
  , "// hand-written Swift forward must reproduce the committed Q16 byte EXACTLY (integer,"
  , "// no tolerance); rawMaskedBand is compared within tolerance (float order). NO Core AI."
  , ""
  , "enum MaskedBandGolden {"
  , "    static let featureCount = " <> tshow featureCountB
  , "    static let numBands = " <> tshow numBands
  , ""
  , "    /// The fixed deterministic theta_B (paramCountB = " <> tshow paramCountB <> " params)."
  , "    static let theta: [Double] = [" <> T.intercalate ", " (map showD goldenTheta) <> "]"
  , ""
  , "    struct Case {"
  , "        let coarse: Int"
  , "        let detail: [Int]      // the 7-band ground-truth detail"
  , "        let masked: Int        // which band is masked (the regressed target)"
  , "        let raw: Double        // rawMaskedBand (tolerance)"
  , "        let byte: Int          // predictMaskedBand = quantizeQ16(raw) (BIT-EXACT)"
  , "    }"
  , ""
  , "    static let cases: [Case] = ["
  ] ++ map emitCase goldenCases ++
  [ "    ]"
  , "}"
  ]
  where
    emitCase :: (Int, Detail, Int) -> Text
    emitCase ex@(v, det, m) =
      "        Case(coarse: " <> tshow v
        <> ", detail: [" <> T.intercalate ", " (map tshow (detList det)) <> "]"
        <> ", masked: " <> tshow m
        <> ", raw: " <> showD (rawMaskedBand goldenTheta ex)
        <> ", byte: " <> tshow (predictMaskedBand goldenTheta ex) <> "),"

    detList :: Detail -> [Int]
    detList (a, b, c, d, e, f, g) = [a, b, c, d, e, f, g]

tshow :: Show a => a -> Text
tshow = T.pack . show

-- | Round-trippable decimal Double literal (Haskell @show@; Swift parses identically).
showD :: Double -> Text
showD = T.pack . show
