{- |
Module      : SixFour.Codegen.MLX
Description : Emit Python shape constants to @trainer/generated/@.

Produces two files:

  * @stages.py@    — shape constants and an @assert_surjective(I)@
    runtime check the trainer can call on every batch.
  * @net_shape.py@ — NN slot dimensions used by the MLX training loop.
    Currently only the @METRIC@ slot exists (the only one with a trainer).
-}
module SixFour.Codegen.MLX
  ( emitStagesPy
  , emitNetShapePy
  ) where

import qualified Data.Text  as T
import           Data.Text  (Text)

import SixFour.Spec.Color  (m1, m2)
import SixFour.Spec.Shape
import SixFour.Spec.Net

emitStagesPy :: Text
emitStagesPy = T.unlines
  [ "# GENERATED by sixfour-spec / Codegen.MLX — do not edit by hand."
  , "# Source of truth: ~/SixFour/spec/src/SixFour/Spec/Shape.hs +"
  , "#                  ~/SixFour/spec/src/SixFour/Spec/Color.hs"
  , "# Regenerate with: cabal run spec-codegen"
  , ""
  , "from __future__ import annotations"
  , "import numpy as np"
  , ""
  , "# Compile-time SixFour shape constants."
  , "T = " <> tshow tVal
  , "H = " <> tshow hVal
  , "W = " <> tshow wVal
  , "K = " <> tshow kVal
  , "PIXELS_PER_FRAME = " <> tshow pixelsPerFrame
  , "PIXELS_PER_GIF   = " <> tshow pixelsPerGIF
  , "CANDIDATES_AFTER_STAGE_A = " <> tshow candidatesAfterStageA
  , ""
  , "# Björn Ottosson's OKLab matrices."
  , "M1 = np.array(" <> matrixLit m1 <> ", dtype=np.float64)"
  , "M2 = np.array(" <> matrixLit m2 <> ", dtype=np.float64)"
  , ""
  , "def assert_surjective(indices: np.ndarray) -> None:"
  , "    \"\"\"Raise if ``indices`` does not use every value 0..K-1.\"\"\""
  , "    flat = np.asarray(indices).reshape(-1)"
  , "    seen = np.unique(flat)"
  , "    if seen.size != K or int(seen.min()) != 0 or int(seen.max()) != K - 1:"
  , "        raise ValueError("
  , "            f\"Surjective256 violated: {seen.size} unique values, range [{int(seen.min())}, {int(seen.max())}]\""
  , "        )"
  , ""
  , "def assert_constants_match() -> None:"
  , "    \"\"\"Sanity-check: T*H*W == PIXELS_PER_GIF, etc.\"\"\""
  , "    assert T * H * W == PIXELS_PER_GIF, (T, H, W, PIXELS_PER_GIF)"
  , "    assert H * W     == PIXELS_PER_FRAME"
  , "    assert T * K     == CANDIDATES_AFTER_STAGE_A"
  , "    assert M1.shape == (3, 3) and M2.shape == (3, 3)"
  ]

emitNetShapePy :: Text
emitNetShapePy = T.unlines
  [ "# GENERATED by sixfour-spec / Codegen.MLX — do not edit by hand."
  , "# Source of truth: ~/SixFour/spec/src/SixFour/Spec/Net.hs"
  , "# Regenerate with: cabal run spec-codegen"
  , ""
  , "from __future__ import annotations"
  , "from dataclasses import dataclass"
  , "from enum import Enum"
  , ""
  , "class NetSlot(str, Enum):"
  , "    METRIC = \"metric\""
  , ""
  , "@dataclass(frozen=True)"
  , "class NetIOSpec:"
  , "    input_dim: int"
  , "    output_dim: int"
  , "    description: str"
  , ""
  , "METRIC_PSD_UPPER_TRIANGLE_COUNT = " <> tshow metricPSDUpperTriangleCount
  , ""
  , slotSpec "METRIC" slotMetricDims
  , ""
  , "ALL_SLOTS = {"
  , "    NetSlot.METRIC: METRIC,"
  , "}"
  , ""
  , "def assert_constants_match() -> None:"
  , "    # The metric file is a vector of 6 floats — the upper triangle"
  , "    # of the 3x3 PSD matrix M = L Lᵀ produced by train_metric.py."
  , "    assert METRIC.input_dim == METRIC_PSD_UPPER_TRIANGLE_COUNT, METRIC.input_dim"
  ]

slotSpec :: Text -> NetIO -> Text
slotSpec nm io = T.unlines
  [ nm <> " = NetIOSpec("
  , "    input_dim=" <> tshow (netInputDim io) <> ","
  , "    output_dim=" <> tshow (netOutputDim io) <> ","
  , "    description=\"" <> T.pack (netDescription io) <> "\","
  , ")"
  ]

matrixLit
  :: ((Double, Double, Double), (Double, Double, Double), (Double, Double, Double))
  -> Text
matrixLit ((a, b, c), (d, e, f), (g, h, i)) = T.concat
  [ "["
  , "[", tshowF a, ", ", tshowF b, ", ", tshowF c, "],"
  , "[", tshowF d, ", ", tshowF e, ", ", tshowF f, "],"
  , "[", tshowF g, ", ", tshowF h, ", ", tshowF i, "]"
  , "]"
  ]

tshow :: Show a => a -> Text
tshow = T.pack . show

tshowF :: Double -> Text
tshowF = T.pack . show
