{- |
Module      : SixFour.Codegen.ModelIO
Description : Emit @SixFourModelIO.swift@ — the wireable model I/O boundary the iOS app paints into and renders out of. Mirrors "SixFour.Spec.ModelIO" (the boundary types + floor) and "SixFour.Spec.ModelForward" (the nudge-conditioned frame), pinning the control-grid dims, the 9 paint channels, the φ6 gauge, the A_7 detail-band count, and the byte-exact floor margin so the hand-written Swift paint tool (W2.2) and render surface (W2.1) defer to spec constants.

String-templated like the rest of "SixFour.Codegen.Swift" (read, diffed, reviewed by humans). The
generated constants come from the spec values, so the hermetic-codegen gate step diffs this file against
a fresh @cabal run spec-codegen@ and fails on drift. This emitter does NOT emit the learned forward (no
weights exist yet); it emits the boundary the forward and the UI both consume.
-}
module SixFour.Codegen.ModelIO
  ( emitModelIOContract
  ) where

import qualified Data.Text as T
import           Data.Text (Text)

import SixFour.Spec.CellNudge        (controlGridSide, superResSide, nPairs, cellSubtreeLeaves)
import SixFour.Spec.RootLatticeDetail (numDetailBands)
import SixFour.Spec.AboveFloorMargin (marginCoeffQ16)

tshow :: Show a => a -> Text
tshow = T.pack . show

-- | Generate @SixFourModelIO.swift@: the model boundary constants + the @ModelInput@/@ModelOutput@
-- struct mirrors + the @renderFrame@ contract. Zero paint ('neutralNudge') is the byte-exact floor
-- ("SixFour.Spec.ModelIO" @lawNeutralNudgeIsAllFloor@); one painted 16³ cell governs a
-- 'cellSubtreeLeaves'-leaf 256³ subtree ("SixFour.Spec.CellNudge" @lawCellGovernsSuperResSubtree@).
emitModelIOContract :: Text
emitModelIOContract = T.unlines
  [ "// GENERATED by sixfour-spec / Codegen.ModelIO — do not edit by hand."
  , "// Source of truth: ~/SixFour/spec/src/SixFour/Spec/ModelIO.hs + ModelForward.hs"
  , "// Regenerate with: cabal run spec-codegen"
  , ""
  , "import Foundation"
  , "import simd"
  , ""
  , "/// The model I/O boundary the UI paints into and renders out of — one boundary, four consumers"
  , "/// (UI paint, UI render, the 256³ builder, the trainer target). Mirrors `SixFour.Spec.ModelIO`"
  , "/// and the nudge-conditioned frame `SixFour.Spec.ModelForward`. INPUT = the 64³ capture +"
  , "/// the 16³ × 9-channel paint + the φ6 gauge; OUTPUT = the 256³ as GIF89a (per-frame palettes ="
  , "/// VALUE, index planes = CONTENT). Constants are spec-pinned and gated by `cabal test`."
  , "public enum SixFourModelIO {"
  , "    /// The coarse control-grid side the user paints on (the 64³ capture analysed two octant"
  , "    /// levels down to 16³). `SixFour.Spec.CellNudge.controlGridSide`."
  , "    public static let controlGridSide: Int = " <> tshow controlGridSide
  , ""
  , "    /// The invented output side, two octant-twiceness rungs above the grid (16 → 64 → 256)."
  , "    public static let superResSide: Int = " <> tshow superResSide
  , ""
  , "    /// The independently-paintable channels per cell: the nine ChannelProduct colour-by-space pairs."
  , "    public static let paintChannelsPerCell: Int = " <> tshow nPairs
  , ""
  , "    /// The 256³ leaves one painted 16³ cell governs: (256/16)³ = 4096 (`lawCellGovernsSuperResSubtree`)."
  , "    public static let cellSubtreeLeaves: Int = " <> tshow cellSubtreeLeaves
  , ""
  , "    /// The invented detail bands per octant = rank A_7 = 7 (`RootLatticeDetail.numDetailBands 8`)."
  , "    public static let detailBandsPerOctant: Int = " <> tshow (numDetailBands 8)
  , ""
  , "    /// The minimum invented-detail coefficient that survives the Q16 commit: one Q16 LSB"
  , "    /// (`SixFour.Spec.AboveFloorMargin.marginCoeffQ16`). Detail below ~half this snaps to the floor."
  , "    public static let marginCoeffQ16: Int = " <> tshow marginCoeffQ16
  , ""
  , "    /// The number of control cells in the 16³ grid (the painted budget has one row per cell)."
  , "    public static let controlCellCount: Int = controlGridSide * controlGridSide * controlGridSide"
  , ""
  , "    /// The neutral (unpainted) budget = zero everywhere = the byte-exact floor"
  , "    /// (`SixFour.Spec.ModelIO.lawNeutralNudgeIsAllFloor`)."
  , "    public static func neutralNudge() -> [[Int]] {"
  , "        Array(repeating: Array(repeating: 0, count: paintChannelsPerCell), count: controlCellCount)"
  , "    }"
  , ""
  , "    /// Re-derive the dependent constants and assert the self-similar relations hold — defense in"
  , "    /// depth against a hand-edit. Pinned bit-for-bit to the spec by `cabal test`."
  , "    public static func selfCheck() -> Bool {"
  , "        let span = superResSide / controlGridSide"
  , "        return cellSubtreeLeaves == span * span * span"
  , "            && cellSubtreeLeaves == 4096"
  , "            && controlGridSide * 16 == superResSide"
  , "            && paintChannelsPerCell == 9"
  , "            && detailBandsPerOctant == 7"
  , "            && marginCoeffQ16 >= 1"
  , "    }"
  , "}"
  , ""
  , "/// The model INPUT the UI assembles. Mirrors `SixFour.Spec.ModelIO.ModelInput`."
  , "public struct SixFourModelInput {"
  , "    /// The 64³ capture's super-res input (an opaque handle into the Upscale256 floor builder)."
  , "    public var captureHandle: Int"
  , "    /// The 16³ × 9-channel paint: `controlCellCount` rows, each `paintChannelsPerCell` budgets."
  , "    public var nudge: [[Int]]"
  , "    /// The φ6 gauge toggle (colour-by-space vs the dual)."
  , "    public var gauge: Bool"
  , ""
  , "    public init(captureHandle: Int, nudge: [[Int]], gauge: Bool) {"
  , "        self.captureHandle = captureHandle"
  , "        self.nudge = nudge"
  , "        self.gauge = gauge"
  , "    }"
  , "}"
  , ""
  , "/// The model OUTPUT = the renderable 256³ = GIF89a. Mirrors `SixFour.Spec.ModelIO.ModelOutput`"
  , "/// (= `Upscale256.UpscaleOutput`): per-frame palettes (VALUE) + per-frame index planes (CONTENT)."
  , "public struct SixFourModelOutput {"
  , "    /// Per-frame palettes, each a list of Q16 OKLab triples."
  , "    public var palettes: [[SIMD3<Int>]]"
  , "    /// Per-frame index planes, each an index into that frame's palette."
  , "    public var indexPlanes: [[Int]]"
  , ""
  , "    public init(palettes: [[SIMD3<Int>]], indexPlanes: [[Int]]) {"
  , "        self.palettes = palettes"
  , "        self.indexPlanes = indexPlanes"
  , "    }"
  , ""
  , "    /// Render frame `f`: the `(palette, indexPlane)` pair the UI draws as `palette[index]`"
  , "    /// (`SixFour.Spec.ModelIO.renderFrame`). Zero paint yields the byte-exact floor."
  , "    public func renderFrame(_ f: Int) -> ([SIMD3<Int>], [Int]) {"
  , "        (palettes[f], indexPlanes[f])"
  , "    }"
  , "}"
  ]
