{- |
Module      : SixFour.Codegen.PairTree
Description : Emit PairTreeGolden.swift — the tolerance gate for the Haar palette tree.

The global palette's native math form is a Haar pyramid ('SixFour.Spec.PairTree':
a root + 8 levels of @2^i@ offsets, 768 DOF). The search's reversible 'Move's
perturb one of these coefficients, so the Swift port ('PaletteHaarTree') must agree
with the spec's 'analyze' / 'reconstruct'.

Unlike the Q16 collapse, the Haar transform is FLOAT math ((x±y)/2), so it cannot
be bit-exact across languages (summation/rounding diverge at the ULP). This golden
therefore gates within a TOLERANCE (1e-9): a fixed 16-leaf OKLab fixture and its
'analyze' output (root + 4 levels of 1/2/4/8 offsets). The Swift test reproduces
'analyze' to tolerance, self-checks the round-trip at the production depth (256
leaves), and pins @degreesOfFreedom == 768@.

Doubles are emitted as full-precision decimal literals ('show' round-trips a
'Double'); the comparison tolerance (≫ 1 ULP) absorbs any decimal re-rounding.
-}
module SixFour.Codegen.PairTree
  ( emitPairTreeGolden
  ) where

import qualified Data.Text as T
import           Data.Text (Text)

import SixFour.Spec.Color    (OKLab(..))
import SixFour.Spec.PairTree (HaarPalette(..), analyze, degreesOfFreedom)

-- | A deterministic 16-leaf OKLab fixture (depth 4), in gamut. Generated by a
-- tiny LCG so it is reproducible and exercises 4 Haar levels.
pairTreeGoldenLeaves :: [OKLab]
pairTreeGoldenLeaves = take 16 (gen 0x51ed2701)
  where
    gen :: Int -> [OKLab]
    gen s =
      let s1 = step s; s2 = step s1; s3 = step s2
          l = fromIntegral (s1 `mod` 1001) / 1000              -- [0, 1]
          a = fromIntegral (s2 `mod` 801)  / 1000 - 0.4        -- [-0.4, 0.4]
          b = fromIntegral (s3 `mod` 801)  / 1000 - 0.4
      in OKLab l a b : gen s3
    step s = (s * 1103515245 + 12345) `mod` 2147483648

emitPairTreeGolden :: Text
emitPairTreeGolden = T.unlines
  [ "// GENERATED by sixfour-spec / Codegen.PairTree — do not edit by hand."
  , "// Regenerate with: cabal run spec-codegen."
  , "//"
  , "// Tolerance gate for the Haar palette tree (SixFour.Spec.PairTree). A fixed"
  , "// 16-leaf OKLab fixture and its `analyze` output (root + 4 levels). The Swift"
  , "// PaletteHaarTree must reproduce `analyze` within tolerance; float Haar math"
  , "// cannot be bit-exact across languages."
  , "import simd"
  , ""
  , "enum PairTreeGolden {"
  , "    /// Production palette DOF (3 · 2^8) — PaletteHaarTree.degreesOfFreedom must equal this."
  , "    static let degreesOfFreedom: Int = " <> tshow degreesOfFreedom
  , ""
  , "    /// The 16-leaf input fixture (OKLab)."
  , "    static let leaves: [SIMD3<Double>] = " <> simd3dArr leaves
  , ""
  , "    /// Expected `analyze(leaves)` root (the DC/mean colour)."
  , "    static let root: SIMD3<Double> = " <> simd3d (root hp)
  , ""
  , "    /// Expected `analyze(leaves)` offsets, top-down: level i has 2^i entries."
  , "    static let levels: [[SIMD3<Double>]] = " <> levelsLit (levels hp)
  , "}"
  ]
  where
    leaves = pairTreeGoldenLeaves
    hp     = analyze leaves

-- ---------------------------------------------------------------------------
-- Swift-literal emitters
-- ---------------------------------------------------------------------------

tshow :: Show a => a -> Text
tshow = T.pack . show

-- | A Double as a full-precision Swift literal ('show' round-trips a Double;
-- Swift accepts both plain and scientific forms).
dbl :: Double -> Text
dbl = T.pack . show

simd3d :: OKLab -> Text
simd3d (OKLab l a b) = "SIMD3<Double>(" <> T.intercalate ", " (map dbl [l, a, b]) <> ")"

simd3dArr :: [OKLab] -> Text
simd3dArr xs = "[" <> T.intercalate ", " (map simd3d xs) <> "]"

-- | The levels as a Swift nested array, one level per indented line.
levelsLit :: [[OKLab]] -> Text
levelsLit lvls =
  "[\n" <> T.intercalate ",\n" [ "        " <> simd3dArr l | l <- lvls ] <> "\n    ]"
