{- |
Module      : SixFour.Codegen.PaletteValue
Description : Emit PaletteValueGolden.swift — the tolerance gate for the search value head.

The search's value head ('SixFour.Spec.PaletteOracle.paletteReward') is a
DETERMINISTIC aesthetic objective — Ou-Luo pair harmony ('Loss.beautyLossLeaves',
negated) + OKLab Gaussian colour entropy ('Diversity.gaussianColorEntropy') over a
candidate palette's reconstructed leaves. It is the ground truth the look-NN's value
head is trained to approximate, so it is golden-testable today (before any training).

Float math ⇒ tolerance gate (decimal literals + 1e-9 compare). Fixture = a fixed
16-leaf OKLab palette; the golden carries the three derived numbers the Swift
`PaletteValue` must reproduce on the SAME analyze→reconstruct path.
-}
module SixFour.Codegen.PaletteValue
  ( emitPaletteValueGolden
  ) where

import qualified Data.Text as T
import           Data.Text (Text)

import SixFour.Spec.Color        (OKLab(..))
import SixFour.Spec.PairTree     (analyze, reconstruct)
import SixFour.Spec.Loss         (beautyLossLeaves)
import SixFour.Spec.Diversity    (gaussianColorEntropy)
import SixFour.Spec.PaletteOracle (paletteReward, defaultWeights, RewardWeights(..))

-- | A deterministic 16-leaf OKLab fixture (distinct seed from the PairTree golden).
valueGoldenLeaves :: [OKLab]
valueGoldenLeaves = take 16 (gen 0x0ddba11)
  where
    gen :: Int -> [OKLab]
    gen s =
      let s1 = step s; s2 = step s1; s3 = step s2
          l = fromIntegral (s1 `mod` 1001) / 1000
          a = fromIntegral (s2 `mod` 801)  / 1000 - 0.4
          b = fromIntegral (s3 `mod` 801)  / 1000 - 0.4
      in OKLab l a b : gen s3
    step s = (s * 1103515245 + 12345) `mod` 2147483648

-- | Emit the Swift golden for the 'PaletteValue' reward head (beauty + entropy scorer parity pin).
emitPaletteValueGolden :: Text
emitPaletteValueGolden = T.unlines
  [ "// GENERATED by sixfour-spec / Codegen.PaletteValue — do not edit by hand."
  , "// Regenerate with: cabal run spec-codegen."
  , "//"
  , "// Tolerance gate for the search value head (SixFour.Spec.PaletteOracle.paletteReward"
  , "// = Ou-Luo beauty + OKLab Gaussian entropy). Computed on reconstruct(analyze(leaves));"
  , "// the Swift PaletteValue must reproduce within tolerance (float math)."
  , "import simd"
  , ""
  , "enum PaletteValueGolden {"
  , "    /// The 16-leaf input fixture (OKLab)."
  , "    static let leaves: [SIMD3<Double>] = " <> simd3dArr valueGoldenLeaves
  , ""
  , "    /// Reward weights (beauty, diversity)."
  , "    static let beautyWeight: Double = " <> dbl (rwBeauty defaultWeights)
  , "    static let diversityWeight: Double = " <> dbl (rwDiversity defaultWeights)
  , ""
  , "    /// beautyLossLeaves(reconstruct(analyze(leaves)))."
  , "    static let beautyLoss: Double = " <> dbl beauty
  , ""
  , "    /// gaussianColorEntropy(reconstruct(analyze(leaves)), uniform)."
  , "    static let entropy: Double = " <> dbl entropy
  , ""
  , "    /// paletteReward(defaultWeights, analyze(leaves))."
  , "    static let reward: Double = " <> dbl reward
  , "}"
  ]
  where
    leaves  = valueGoldenLeaves
    hp      = analyze leaves
    leaves' = reconstruct hp
    n       = length leaves'
    ws      = replicate n (if n == 0 then 0 else 1 / fromIntegral n)
    beauty  = beautyLossLeaves leaves'
    entropy = gaussianColorEntropy leaves' ws
    reward  = paletteReward defaultWeights hp

dbl :: Double -> Text
dbl = T.pack . show

simd3d :: OKLab -> Text
simd3d (OKLab l a b) = "SIMD3<Double>(" <> T.intercalate ", " (map dbl [l, a, b]) <> ")"

simd3dArr :: [OKLab] -> Text
simd3dArr xs = "[" <> T.intercalate ", " (map simd3d xs) <> "]"
