{- |
Module      : SixFour.Codegen.QuartetDelta
Description : Emit QuartetDeltaGolden.swift — the tolerance gate for the Act II quartet motion outline.

Act II of the palette story ('SixFour.Spec.QuartetDelta'): the user picks 4 frames,
each palette slot becomes a 4-sample OKLab trajectory, and the readouts split the
quartet into a static __core__ (low-displacement slots = structural colour) and the
__motion outline__ (per-slot displacement = how far each colour travels). This is the
residual that the global collapse ('SixFour.Spec.Collapse') throws away.

The Swift port ('SixFour.Palette.QuartetDelta') must agree with the spec's
'slotDisplacement' / 'slotMean' / 'quartetCore' / 'coreColors'. Like the Haar tree
('Codegen.PairTree'), the math is FLOAT (OKLab Euclidean @sqrt@), so it cannot be
bit-exact across languages; this golden therefore gates within a TOLERANCE (1e-9):
a fixed 4×16 OKLab quartet fixture and its readouts. The threshold is pinned at the
fixture's median displacement so 'coreColors' exercises both the in- and out-of-core
branches.

Doubles are emitted as full-precision decimal literals ('show' round-trips a
'Double'); the comparison tolerance (≫ 1 ULP) absorbs any decimal re-rounding.
-}
module SixFour.Codegen.QuartetDelta
  ( emitQuartetDeltaGolden
  ) where

import qualified Data.Text as T
import           Data.Text (Text)

import SixFour.Spec.Color       (OKLab(..))
import SixFour.Spec.QuartetDelta
  ( toSlots, slotMean, slotDisplacement, quartetCore, coreColors
  , medianDisplacementThreshold )

-- | A deterministic 4×16 OKLab quartet fixture: four 16-slot palettes, one per
-- frame, each from its own LCG seed so the slots genuinely move (non-zero
-- displacement). Generated like 'Codegen.PairTree''s fixture (same LCG style).
quartetGoldenPalettes :: [[OKLab]]
quartetGoldenPalettes = map (take 16 . gen) [0x51ed2701, 0x13579bdf, 0x2468ace0, 0x7f4a9c15]
  where
    gen :: Int -> [OKLab]
    gen s =
      let s1 = step s; s2 = step s1; s3 = step s2
          l = fromIntegral (s1 `mod` 1001) / 1000              -- [0, 1]
          a = fromIntegral (s2 `mod` 801)  / 1000 - 0.4        -- [-0.4, 0.4]
          b = fromIntegral (s3 `mod` 801)  / 1000 - 0.4
      in OKLab l a b : gen s3
    step s = (s * 1103515245 + 12345) `mod` 2147483648

-- | Emit the Swift golden for the Act II quartet readouts (motion-outline parity pin).
emitQuartetDeltaGolden :: Text
emitQuartetDeltaGolden = T.unlines
  [ "// GENERATED by sixfour-spec / Codegen.QuartetDelta — do not edit by hand."
  , "// Regenerate with: cabal run spec-codegen."
  , "//"
  , "// Tolerance gate for the Act II quartet motion outline (SixFour.Spec.QuartetDelta)."
  , "// A fixed 4x16 OKLab quartet fixture and its readouts (slot means, per-slot"
  , "// displacement, the quartet core, and the core-colour set at the median"
  , "// threshold). The Swift QuartetDelta must reproduce these within tolerance;"
  , "// float OKLab Euclidean math cannot be bit-exact across languages."
  , "import simd"
  , ""
  , "enum QuartetDeltaGolden {"
  , "    /// Comparison tolerance (float OKLab sqrt can't be bit-exact cross-language)."
  , "    static let tol: Double = 1e-9"
  , ""
  , "    /// The 4-frame quartet fixture: 4 palettes (one per frame), each 16 slots (OKLab)."
  , "    static let palettes: [[SIMD3<Double>]] = " <> palettesLit palettes
  , ""
  , "    /// Expected per-slot mean colour (the slot's piece of the barycenter), one per slot."
  , "    static let slotMeans: [SIMD3<Double>] = " <> simd3dArr (map slotMean slots)
  , ""
  , "    /// Expected per-slot displacement (total OKLab path length = motion magnitude), one per slot."
  , "    static let slotDisplacements: [Double] = " <> dblArr (map slotDisplacement slots)
  , ""
  , "    /// Expected quartet core — the mean of all slot means (\"the core of the whole\")."
  , "    static let quartetCore: SIMD3<Double> = " <> simd3d (quartetCore slots)
  , ""
  , "    /// The threshold (fixture's median displacement) at which `coreColors` is pinned."
  , "    static let coreThreshold: Double = " <> dbl thr
  , ""
  , "    /// Expected core-colour set: slot indices with displacement <= coreThreshold."
  , "    static let coreColors: [Int] = " <> intArr (coreColors thr slots)
  , "}"
  ]
  where
    palettes = quartetGoldenPalettes
    slots    = toSlots palettes
    -- the relative core/motion cut, owned by Spec.QuartetDelta (the Swift port shares it);
    -- median displacement guarantees coreColors splits the slots (some in, some out).
    thr      = medianDisplacementThreshold slots

-- ---------------------------------------------------------------------------
-- Swift-literal emitters (same forms as Codegen.PairTree)
-- ---------------------------------------------------------------------------

-- | A Double as a full-precision Swift literal ('show' round-trips a Double).
dbl :: Double -> Text
dbl = T.pack . show

simd3d :: OKLab -> Text
simd3d (OKLab l a b) = "SIMD3<Double>(" <> T.intercalate ", " (map dbl [l, a, b]) <> ")"

simd3dArr :: [OKLab] -> Text
simd3dArr xs = "[" <> T.intercalate ", " (map simd3d xs) <> "]"

dblArr :: [Double] -> Text
dblArr xs = "[" <> T.intercalate ", " (map dbl xs) <> "]"

intArr :: [Int] -> Text
intArr xs = "[" <> T.intercalate ", " (map (T.pack . show) xs) <> "]"

-- | The 4 palettes as a Swift nested array, one palette per indented line.
palettesLit :: [[OKLab]] -> Text
palettesLit ps =
  "[\n" <> T.intercalate ",\n" [ "        " <> simd3dArr p | p <- ps ] <> "\n    ]"
