{- |
Module      : SixFour.Codegen.RGBT4D
Description : Emit RGBT4DGolden.swift — the byte-exact gate for the RGBT-4D Swift port.

The hand-written Swift port @RGBT4DLift@ mirrors 'SixFour.Spec.RGBTLift' +
'SixFour.Spec.CubeLadder'. Because the lifting is integer-exact (Q16, floor
division), the golden is emitted as plain Swift @Int@ literals — no tolerance —
and @RGBT4DGoldenTests@ must reproduce every value EXACTLY. This replaces the
previously hand-written test constants so the Swift port rides the same
@spec-codegen@ drift gate as @CollapseGolden@ / @QuartetDeltaGolden@.

Fixture: the same fixed 8×8 grid the spec's @Properties.CubeLadder@ pins, run
through 'liftQuad', @distill 2 8@ (the 64²→16² ×4 down step, here at side 8), and
@synthBeyond 8 1@ (the nearest-neighbour upscale floor).
-}
module SixFour.Codegen.RGBT4D
  ( emitRGBT4DGolden
  ) where

import qualified Data.Text as T
import           Data.Text (Text)

import SixFour.Spec.RGBTLift   (liftQuad)
import SixFour.Spec.CubeLadder (distill, synthBeyond)

-- | The fixed 8×8 grid — identical to @Properties.CubeLadder.goldenGrid@.
goldenGrid :: [Int]
goldenGrid = [ ((i * 37 + 11) `mod` 251) - 125 | i <- [0 .. 63] ]

-- | Emit the Swift golden-vector fixture for the RGBT-4D lift + cube ladder.
emitRGBT4DGolden :: Text
emitRGBT4DGolden = T.unlines
  [ "// GENERATED by sixfour-spec / Codegen.RGBT4D — do not edit by hand."
  , "// Regenerate with: cabal run spec-codegen."
  , "//"
  , "// Byte-exact golden for the RGBT-4D integer lift + cube ladder"
  , "// (SixFour.Spec.RGBTLift + SixFour.Spec.CubeLadder). Q16 integers, no"
  , "// tolerance; the Swift RGBT4DLift port must reproduce them EXACTLY."
  , ""
  , "enum RGBT4DGolden {"
  , "    /// The fixed 8x8 source grid (row-major)."
  , "    static let grid: [Int] = " <> intArr goldenGrid
  , ""
  , "    /// liftQuad(10,20,30,44) = (R,G,B,T) sub-bands."
  , "    static let liftQuad_10_20_30_44: [Int] = " <> intArr [lr, lg, lb, lt]
  , ""
  , "    /// distill 2 8 grid: the coarse (2x2) plane after the x4 down step."
  , "    static let distillCoarse: [Int] = " <> intArr coarse
  , ""
  , "    /// distill 2 8 grid: the detail planes, flattened (finest first, R/G/B per triple)."
  , "    static let distillDetailsFlat: [Int] = " <> intArr detailsFlat
  , ""
  , "    /// synthBeyond 8 1 grid: the x2 nearest-neighbour upscale floor (16x16)."
  , "    static let synthBeyond_8_1: [Int] = " <> intArr beyond
  , "}"
  ]
  where
    (lr, lg, lb, lt) = liftQuad (10, 20, 30, 44)
    (coarse, dets)   = distill 2 8 goldenGrid
    detailsFlat      = concatMap (concatMap (\(a, b, c) -> [a, b, c])) dets
    beyond           = synthBeyond 8 1 goldenGrid

intArr :: [Int] -> Text
intArr xs = "[" <> T.intercalate ", " (map (T.pack . show) xs) <> "]"
