{- |
Module      : SixFour.Codegen.Sha512
Description : Emit Sha512Golden.swift — the byte-exact gate for the SHA-512 Swift port.

The hand-written Foundation-only Swift SHA-512 must mirror 'SixFour.Spec.Sha512' (FIPS 180-4)
bit-for-bit. This golden pins the two canonical NIST test vectors (the empty string and @"abc"@)
plus a longer multi-block message, so the Swift port's padding, block compression, and big-endian
digest emission are all gated. @Sha512GoldenTests@ on device must reproduce every digest EXACTLY.
-}
module SixFour.Codegen.Sha512
  ( emitSha512Golden
  ) where

import qualified Data.Text as T
import           Data.Text (Text)
import           Data.Word (Word8)

import SixFour.Spec.Sha512 (sha512)

-- | The message bytes for each fixture (name, ASCII payload).
fixtures :: [(Text, String)]
fixtures =
  [ ("empty", "")
  , ("abc",   "abc")
  , ("millionA_1000", replicate 1000 'a')   -- multi-block (>128 B): exercises >1 compression round
  ]

asciiBytes :: String -> [Word8]
asciiBytes = map (fromIntegral . fromEnum)

emitSha512Golden :: Text
emitSha512Golden = T.unlines $
  [ "// GENERATED by sixfour-spec / Codegen.Sha512 — do not edit by hand."
  , "// Regenerate with: cabal run spec-codegen."
  , "//"
  , "// Byte-exact golden for SHA-512 (SixFour.Spec.Sha512, FIPS 180-4). The Swift port must"
  , "// reproduce each 64-byte digest EXACTLY (empty + \"abc\" are the canonical NIST vectors;"
  , "// the 1000-'a' case exercises multi-block padding)."
  , ""
  , "enum Sha512Golden {"
  , "    /// (message bytes, expected 64-byte digest) per fixture."
  , "    static let vectors: [(name: String, message: [UInt8], digest: [UInt8])] = ["
  ]
  ++ map fixtureLine fixtures
  ++ [ "    ]"
     , "}"
     ]
  where
    fixtureLine (nm, s) =
      let msg = asciiBytes s
      in "        (\"" <> nm <> "\", " <> byteArr msg <> ", " <> byteArr (sha512 msg) <> "),"

byteArr :: [Word8] -> Text
byteArr xs = "[" <> T.intercalate ", " (map (T.pack . show) xs) <> "]"
