{- |
Module      : SixFour.Codegen.Shapes
Description : Emit Python shape + significance constants to @trainer/generated/@.

The dimensional / statistical contract the Mac-side trainer imports. Pure NumPy
constants and runtime assertions — NOT a trainable model. The H-JEPA trainer lives
hand-written in @trainer/mlx/@ and is gated by the spec-emitted goldens
("SixFour.Codegen.JepaHead" / "SixFour.Codegen.TemporalData"); this module only
emits the dimensional constants it shares.

Produces @stages.py@ — shape constants and an @assert_surjective(I)@ runtime check
the trainer can call on every batch. (@emitNetShape@ below is a dormant helper, not
wired into the codegen driver.)
-}
module SixFour.Codegen.Shapes
  ( emitStagesPy
  ) where

import qualified Data.Text  as T
import           Data.Text  (Text)

import SixFour.Spec.Color  (m1, m2)
import SixFour.Spec.Shape
import SixFour.Spec.Significance (confidenceZ, minPopulation, chiSquare3Critical)

-- | Emit the Python pipeline-stage shape constants for the trainer.
emitStagesPy :: Text
emitStagesPy = T.unlines
  [ "# GENERATED by sixfour-spec / Codegen.Shapes — do not edit by hand."
  , "# Source of truth: ~/SixFour/spec/src/SixFour/Spec/Shape.hs +"
  , "#                  ~/SixFour/spec/src/SixFour/Spec/Color.hs"
  , "# Regenerate with: cabal run spec-codegen"
  , ""
  , "from __future__ import annotations"
  , "import numpy as np"
  , ""
  , "# Compile-time SixFour shape constants."
  , "T = " <> tshow tVal
  , "H = " <> tshow hVal
  , "W = " <> tshow wVal
  , "K = " <> tshow kVal
  , "PIXELS_PER_FRAME = " <> tshow pixelsPerFrame
  , "PIXELS_PER_GIF   = " <> tshow pixelsPerGIF
  , "CANDIDATES_AFTER_STAGE_A = " <> tshow candidatesAfterStageA
  , ""
  , "# Björn Ottosson's OKLab matrices."
  , "M1 = np.array(" <> matrixLit m1 <> ", dtype=np.float64)"
  , "M2 = np.array(" <> matrixLit m2 <> ", dtype=np.float64)"
  , ""
  , "def assert_surjective(indices: np.ndarray) -> None:"
  , "    \"\"\"Raise if ``indices`` does not use every value 0..K-1.\"\"\""
  , "    flat = np.asarray(indices).reshape(-1)"
  , "    seen = np.unique(flat)"
  , "    if seen.size != K or int(seen.min()) != 0 or int(seen.max()) != K - 1:"
  , "        raise ValueError("
  , "            f\"Surjective256 violated: {seen.size} unique values, range [{int(seen.min())}, {int(seen.max())}]\""
  , "        )"
  , ""
  , "# Per-frame palette significance (SixFour.Spec.Significance)."
  , "# Significance is POPULATION: a palette slot is significant iff backed by"
  , "# >= N_MIN pixels — never a donated single-pixel outlier. Each slot owns"
  , "# the OKLab range  mean +/- Z_ALPHA * sigma  (the \"range for each bin\")."
  , "Z_ALPHA = " <> tshowF confidenceZ
  , "N_MIN = " <> tshow minPopulation
  , "# chi^2_3 right-tail critical values P(chi2_3 > v) = alpha."
  , "CHI2_3 = {"
  , "    0.001: " <> tshowF (chiSquare3Critical 0.001) <> ","
  , "    0.01: "  <> tshowF (chiSquare3Critical 0.01)  <> ","
  , "    0.025: " <> tshowF (chiSquare3Critical 0.025) <> ","
  , "    0.05: "  <> tshowF (chiSquare3Critical 0.05)  <> ","
  , "    0.10: "  <> tshowF (chiSquare3Critical 0.10)  <> ","
  , "}"
  , ""
  , "def assert_significant(counts: np.ndarray) -> None:"
  , "    \"\"\"Raise unless every one of the K palette slots is backed by >= N_MIN"
  , "    pixels (no outlier) and the counts conserve mass (sum == PIXELS_PER_FRAME)."
  , "    `counts` is the per-slot population for a single frame.\"\"\""
  , "    c = np.asarray(counts).reshape(-1)"
  , "    if c.size != K:"
  , "        raise ValueError(f\"Significance: expected {K} slot counts, got {c.size}\")"
  , "    if int(c.min()) < N_MIN:"
  , "        raise ValueError(f\"Significance violated: a slot has {int(c.min())} < N_MIN={N_MIN} pixels (outlier)\")"
  , "    if int(c.sum()) != PIXELS_PER_FRAME:"
  , "        raise ValueError(f\"Mass not conserved: sum(counts)={int(c.sum())} != {PIXELS_PER_FRAME}\")"
  , ""
  , "def assert_constants_match() -> None:"
  , "    \"\"\"Sanity-check: T*H*W == PIXELS_PER_GIF, etc.\"\"\""
  , "    assert T * H * W == PIXELS_PER_GIF, (T, H, W, PIXELS_PER_GIF)"
  , "    assert H * W     == PIXELS_PER_FRAME"
  , "    assert T * K     == CANDIDATES_AFTER_STAGE_A"
  , "    assert M1.shape == (3, 3) and M2.shape == (3, 3)"
  , "    # The all-significant guarantee is feasible iff a frame has room for"
  , "    # N_MIN pixels in each of the K slots."
  , "    assert N_MIN * K <= PIXELS_PER_FRAME, (N_MIN, K, PIXELS_PER_FRAME)"
  ]

-- | Emit the Python network-shape constants (@net_shape.py@) — the io dims / depth the trainer mirrors.
matrixLit
  :: ((Double, Double, Double), (Double, Double, Double), (Double, Double, Double))
  -> Text
matrixLit ((a, b, c), (d, e, f), (g, h, i)) = T.concat
  [ "["
  , "[", tshowF a, ", ", tshowF b, ", ", tshowF c, "],"
  , "[", tshowF d, ", ", tshowF e, ", ", tshowF f, "],"
  , "[", tshowF g, ", ", tshowF h, ", ", tshowF i, "]"
  , "]"
  ]

tshow :: Show a => a -> Text
tshow = T.pack . show

tshowF :: Double -> Text
tshowF = T.pack . show
