{- |
Module      : SixFour.Codegen.Shapes
Description : Emit Python shape + significance constants to @trainer/generated/@.

The dimensional / statistical contract the Mac-side trainer imports. Pure NumPy
constants and runtime assertions — NOT an @mlx.nn@ model (the trainable look-NN
model is emitted by "SixFour.Codegen.CoreML", and a native @mlx.nn@ emitter is
planned to reclaim the @Codegen.MLX@ name once the MLX training path is built).

Produces two files:

  * @stages.py@    — shape constants and an @assert_surjective(I)@
    runtime check the trainer can call on every batch.
  * @net_shape.py@ — NN slot dimensions used by the trainer.
    Currently only the @METRIC@ slot exists (the only one with a trainer).
-}
module SixFour.Codegen.Shapes
  ( emitStagesPy
  , emitNetShapePy
  ) where

import qualified Data.Text  as T
import           Data.Text  (Text)

import SixFour.Spec.Color  (m1, m2)
import SixFour.Spec.Shape
import SixFour.Spec.Significance (confidenceZ, minPopulation, chiSquare3Critical)
import SixFour.Spec.Net

-- | Emit the Python pipeline-stage shape constants for the trainer.
emitStagesPy :: Text
emitStagesPy = T.unlines
  [ "# GENERATED by sixfour-spec / Codegen.Shapes — do not edit by hand."
  , "# Source of truth: ~/SixFour/spec/src/SixFour/Spec/Shape.hs +"
  , "#                  ~/SixFour/spec/src/SixFour/Spec/Color.hs"
  , "# Regenerate with: cabal run spec-codegen"
  , ""
  , "from __future__ import annotations"
  , "import numpy as np"
  , ""
  , "# Compile-time SixFour shape constants."
  , "T = " <> tshow tVal
  , "H = " <> tshow hVal
  , "W = " <> tshow wVal
  , "K = " <> tshow kVal
  , "PIXELS_PER_FRAME = " <> tshow pixelsPerFrame
  , "PIXELS_PER_GIF   = " <> tshow pixelsPerGIF
  , "CANDIDATES_AFTER_STAGE_A = " <> tshow candidatesAfterStageA
  , ""
  , "# Björn Ottosson's OKLab matrices."
  , "M1 = np.array(" <> matrixLit m1 <> ", dtype=np.float64)"
  , "M2 = np.array(" <> matrixLit m2 <> ", dtype=np.float64)"
  , ""
  , "def assert_surjective(indices: np.ndarray) -> None:"
  , "    \"\"\"Raise if ``indices`` does not use every value 0..K-1.\"\"\""
  , "    flat = np.asarray(indices).reshape(-1)"
  , "    seen = np.unique(flat)"
  , "    if seen.size != K or int(seen.min()) != 0 or int(seen.max()) != K - 1:"
  , "        raise ValueError("
  , "            f\"Surjective256 violated: {seen.size} unique values, range [{int(seen.min())}, {int(seen.max())}]\""
  , "        )"
  , ""
  , "# Per-frame palette significance (SixFour.Spec.Significance)."
  , "# Significance is POPULATION: a palette slot is significant iff backed by"
  , "# >= N_MIN pixels — never a donated single-pixel outlier. Each slot owns"
  , "# the OKLab range  mean +/- Z_ALPHA * sigma  (the \"range for each bin\")."
  , "Z_ALPHA = " <> tshowF confidenceZ
  , "N_MIN = " <> tshow minPopulation
  , "# chi^2_3 right-tail critical values P(chi2_3 > v) = alpha."
  , "CHI2_3 = {"
  , "    0.001: " <> tshowF (chiSquare3Critical 0.001) <> ","
  , "    0.01: "  <> tshowF (chiSquare3Critical 0.01)  <> ","
  , "    0.025: " <> tshowF (chiSquare3Critical 0.025) <> ","
  , "    0.05: "  <> tshowF (chiSquare3Critical 0.05)  <> ","
  , "    0.10: "  <> tshowF (chiSquare3Critical 0.10)  <> ","
  , "}"
  , ""
  , "def assert_significant(counts: np.ndarray) -> None:"
  , "    \"\"\"Raise unless every one of the K palette slots is backed by >= N_MIN"
  , "    pixels (no outlier) and the counts conserve mass (sum == PIXELS_PER_FRAME)."
  , "    `counts` is the per-slot population for a single frame.\"\"\""
  , "    c = np.asarray(counts).reshape(-1)"
  , "    if c.size != K:"
  , "        raise ValueError(f\"Significance: expected {K} slot counts, got {c.size}\")"
  , "    if int(c.min()) < N_MIN:"
  , "        raise ValueError(f\"Significance violated: a slot has {int(c.min())} < N_MIN={N_MIN} pixels (outlier)\")"
  , "    if int(c.sum()) != PIXELS_PER_FRAME:"
  , "        raise ValueError(f\"Mass not conserved: sum(counts)={int(c.sum())} != {PIXELS_PER_FRAME}\")"
  , ""
  , "def assert_constants_match() -> None:"
  , "    \"\"\"Sanity-check: T*H*W == PIXELS_PER_GIF, etc.\"\"\""
  , "    assert T * H * W == PIXELS_PER_GIF, (T, H, W, PIXELS_PER_GIF)"
  , "    assert H * W     == PIXELS_PER_FRAME"
  , "    assert T * K     == CANDIDATES_AFTER_STAGE_A"
  , "    assert M1.shape == (3, 3) and M2.shape == (3, 3)"
  , "    # The all-significant guarantee is feasible iff a frame has room for"
  , "    # N_MIN pixels in each of the K slots."
  , "    assert N_MIN * K <= PIXELS_PER_FRAME, (N_MIN, K, PIXELS_PER_FRAME)"
  ]

-- | Emit the Python network-shape constants (@net_shape.py@) — the io dims / depth the trainer mirrors.
emitNetShapePy :: Text
emitNetShapePy = T.unlines
  [ "# GENERATED by sixfour-spec / Codegen.Shapes — do not edit by hand."
  , "# Source of truth: ~/SixFour/spec/src/SixFour/Spec/Net.hs"
  , "# Regenerate with: cabal run spec-codegen"
  , ""
  , "from __future__ import annotations"
  , "from dataclasses import dataclass, field"
  , "from enum import Enum"
  , ""
  , "class NetSlot(str, Enum):"
  , "    METRIC = \"metric\""
  , "    LOOK = \"look\""
  , ""
  , "@dataclass(frozen=True)"
  , "class NetIOSpec:"
  , "    input_dim: int"
  , "    output_dim: int"
  , "    description: str"
  , "    # Extra named shape constants beyond (input, output) — e.g. the look-NN's"
  , "    # MODEL_DIM / CORE_DEPTH / SIGMA_PAIR_LEAVES / MAX_TOKENS. Empty for the"
  , "    # simple per-layer / metric signatures. Mirrors Net.netAuxDims (Haskell)."
  , "    aux_dims: dict = field(default_factory=dict)"
  , ""
  , "METRIC_PSD_UPPER_TRIANGLE_COUNT = " <> tshow metricPSDUpperTriangleCount
  , ""
  , slotSpec "METRIC" slotMetricDims
  , ""
  , slotSpec "LOOK" slotLookDims
  , ""
  , "ALL_SLOTS = {"
  , "    NetSlot.METRIC: METRIC,"
  , "    NetSlot.LOOK: LOOK,"
  , "}"
  , ""
  , "def assert_constants_match() -> None:"
  , "    # The metric file is a vector of 6 floats — the upper triangle"
  , "    # of the 3x3 PSD matrix M = L Lᵀ produced by train_metric.py."
  , "    assert METRIC.input_dim == METRIC_PSD_UPPER_TRIANGLE_COUNT, METRIC.input_dim"
  , "    # The look-NN: GMM_TOKEN_DIM=10 tokens -> SIGMA_PAIR_DOF=384 coeffs; the"
  , "    # aux dims pin the rest of the model shape the MLX trainer emits and the"
  , "    # hand-written on-device forward pass (export_look_net_blob.py) loads."
  , "    assert LOOK.input_dim == 10, LOOK.input_dim"
  , "    assert LOOK.output_dim == 384, LOOK.output_dim"
  , "    assert LOOK.aux_dims[\"MODEL_DIM\"] == 64, LOOK.aux_dims"
  , "    assert LOOK.aux_dims[\"CORE_DEPTH\"] == 8, LOOK.aux_dims"
  , "    assert LOOK.aux_dims[\"SIGMA_PAIR_LEAVES\"] == 256, LOOK.aux_dims"
  , "    assert LOOK.aux_dims[\"MAX_TOKENS\"] == 16384, LOOK.aux_dims"
  , "    # SIGMA_PAIR_LEAVES is the K-colour palette; 2*output/3 generators -> K leaves."
  , "    assert LOOK.aux_dims[\"SIGMA_PAIR_LEAVES\"] == 2 * (LOOK.output_dim // 3), LOOK.aux_dims"
  ]

slotSpec :: Text -> NetIO -> Text
slotSpec nm io = T.unlines
  [ nm <> " = NetIOSpec("
  , "    input_dim=" <> tshow (netInputDim io) <> ","
  , "    output_dim=" <> tshow (netOutputDim io) <> ","
  , "    description=\"" <> T.pack (netDescription io) <> "\","
  , "    aux_dims=" <> auxDimsLit (netAuxDims io) <> ","
  , ")"
  ]

auxDimsLit :: [(String, Int)] -> Text
auxDimsLit [] = "{}"
auxDimsLit kvs =
  "{" <> T.intercalate ", "
    [ "\"" <> T.pack k <> "\": " <> tshow v | (k, v) <- kvs ] <> "}"

matrixLit
  :: ((Double, Double, Double), (Double, Double, Double), (Double, Double, Double))
  -> Text
matrixLit ((a, b, c), (d, e, f), (g, h, i)) = T.concat
  [ "["
  , "[", tshowF a, ", ", tshowF b, ", ", tshowF c, "],"
  , "[", tshowF d, ", ", tshowF e, ", ", tshowF f, "],"
  , "[", tshowF g, ", ", tshowF h, ", ", tshowF i, "]"
  , "]"
  ]

tshow :: Show a => a -> Text
tshow = T.pack . show

tshowF :: Double -> Text
tshowF = T.pack . show
