{- |
Module      : SixFour.Codegen.SigChain
Description : Emit SigChainGolden.swift — the byte-exact gate for the creator-authorship sigchain Swift port.

The hand-written Swift sigchain must mirror 'SixFour.Spec.SigChain': a creator's append-only
Ed25519-signed authorship chain over the 'SixFour.Spec.Trade.GeneId's they minted, each link binding
its @seq · prev · attestation@ (so a re-signed interior splice is still caught by the successor's
back-pointer). This golden pins a genuine 3-link chain (its bytes, back-pointers, signatures, and
public key) plus a TAMPERED variant that must fail verification. @SigChainGoldenTests@ on device must
reproduce the chain bytes EXACTLY, verify the genuine chain, and reject the tampered one.
-}
module SixFour.Codegen.SigChain
  ( emitSigChainGolden
  ) where

import qualified Data.Text as T
import           Data.Text (Text)
import           Data.Word (Word8)

import SixFour.Spec.SigChain (KeyPair(..), Link(..), buildChain, contentBytes,
                              genesisPrev, keyFor, linkHash, verifyChain)
import SixFour.Spec.Trade    (GeneId(..))

-- | A creator (seed integer) and the three gene addresses they attest, in order.
creatorSeed :: Int
creatorSeed = 424242

attestations :: [GeneId]
attestations = [GeneId 111111, GeneId (-222222), GeneId 333333]

kp :: KeyPair
kp = keyFor creatorSeed

genuineChain :: [Link]
genuineChain = buildChain (kpSeed kp) attestations

-- | The chain with link 1's attestation swapped — verification MUST reject it (the signature no
-- longer covers the changed content, and the back-pointer chain breaks).
tamperedChain :: [Link]
tamperedChain = case genuineChain of
  (a : b : rest) -> a : b { lAtt = GeneId 999999 } : rest
  other          -> other

emitSigChainGolden :: Text
emitSigChainGolden = T.unlines $
  [ "// GENERATED by sixfour-spec / Codegen.SigChain — do not edit by hand."
  , "// Regenerate with: cabal run spec-codegen."
  , "//"
  , "// Byte-exact golden for the creator-authorship sigchain (SixFour.Spec.SigChain). The Swift"
  , "// port must reproduce the chain link bytes EXACTLY, verify(publicKey, genuineChain) == true,"
  , "// and verify(publicKey, tamperedChain) == false (a swapped attestation breaks sig + back-pointer)."
  , ""
  , "enum SigChainGolden {"
  , "    struct Link { let seq: Int; let prev: Int; let attestation: Int; let signature: [UInt8] }"
  , ""
  , "    static let creatorSeed = " <> tshow creatorSeed
  , "    static let publicKey: [UInt8] = " <> byteArr (kpPub kp)
  , "    static let seed: [UInt8] = " <> byteArr (kpSeed kp)
  , "    static let genesisPrev = " <> tshow genesisPrev
  , ""
  , "    /// The genuine 3-link chain — verifies under `publicKey`."
  , "    static let genuineChain: [Link] = ["
  ]
  ++ map linkLine genuineChain
  ++ [ "    ]"
     , ""
     , "    /// Link 1's attestation swapped — verification MUST reject this."
     , "    static let tamperedChain: [Link] = ["
     ]
  ++ map linkLine tamperedChain
  ++ [ "    ]"
     , ""
     , "    /// Sanity constants the port re-derives: each link's linkHash (the successor's back-pointer)."
     , "    static let linkHashes: [Int] = " <> intArr (map linkHash genuineChain)
     , "    /// The genuine chain verifies; the tampered one does not (asserted at spec-emit time)."
     , "    static let genuineVerifies = " <> boolLit (verifyChain (kpPub kp) genuineChain)
     , "    static let tamperedVerifies = " <> boolLit (verifyChain (kpPub kp) tamperedChain)
     , "}"
     ]
  where
    linkLine l =
      "        Link(seq: " <> tshow (lSeq l)
        <> ", prev: " <> tshow (lPrev l)
        <> ", attestation: " <> (let GeneId i = lAtt l in tshow i)
        <> ", signature: " <> byteArr (lSig l) <> "),   // content " <> byteArr (contentBytes l)

tshow :: Show a => a -> Text
tshow = T.pack . show

boolLit :: Bool -> Text
boolLit b = if b then "true" else "false"

byteArr :: [Word8] -> Text
byteArr xs = "[" <> T.intercalate ", " (map tshow xs) <> "]"

intArr :: [Int] -> Text
intArr xs = "[" <> T.intercalate ", " (map tshow xs) <> "]"
