{- |
Module      : SixFour.Codegen.SwapCarrier
Description : Emit SwapCarrierGolden.swift — the byte-exact gate for the SwapCarrier Swift port.

The hand-written Swift port @SwapCarrier@ mirrors 'SixFour.Spec.SwapCarrier' (the S4GX
gene-in-GIF codec: one tradeable gene + its lineage tag, Showcase\/Grant profiles, CRC32,
GIF89a Application-Extension framing). The golden pins BOTH profiles of a fixed canonical
@theta-up@ payload plus two negative vectors:

  * @encodedShowcase@ \/ @encodedGrant@ — the Swift encode must reproduce these EXACTLY and
    extract back to the pinned fields (the Showcase byte stream must contain ZERO weight
    words — the hybrid-model wire fact).
  * @corruptEncoded@ — the grant stream with one BODY byte flipped: extraction must refuse
    (CRC), never return the payload.
  * @versionMismatchEncoded@ — the same payload at MAJOR+1: extraction must report a
    version mismatch, never a partial parse.
-}
module SixFour.Codegen.SwapCarrier
  ( emitSwapCarrierGolden
  ) where

import qualified Data.Text as T
import           Data.Text (Text)
import           Data.Bits (xor)
import           Data.Word (Word8)

import SixFour.Spec.Lineage     (GeneTag (..))
import SixFour.Spec.SwapCarrier (SwapPayload (..), SwapProfile (..),
                                 encodeSwapBlock, encodeSwapBlockVersioned,
                                 swapMajor, swapMinor)
import SixFour.Spec.Trade       (CreatorId (..), GeneId (..))

-- | The fixed canonical payload: a @theta-up@ grant (21 Q16 words spanning
-- negatives — the sign-extension trap) with a two-parent lineage tag (the
-- remix-mint shape).
goldenGrant :: SwapPayload
goldenGrant = SwapPayload
  { spProfile  = Grant
  , spGeneName = "theta-up"
  , spTag      = GeneTag
      { gtGene    = GeneId 987654
      , gtCreator = CreatorId 4242
      , gtParents = [GeneId 111, GeneId (-222)]
      , gtMinted  = 77
      }
  , spWeights  = [ i * 6553 - 65536 | i <- [0 .. 20] ]
  }

-- | The same gene as its public face (the codec drops the weights on the wire).
goldenShowcase :: SwapPayload
goldenShowcase = goldenGrant { spProfile = Showcase }

-- | The grant stream with body byte 0 (the \"S\" of the S4GX magic, stream index
-- 15: marker 14 + length byte 1) flipped — the CRC must catch it.
corruptStream :: [Word8]
corruptStream =
  [ if i == (15 :: Int) then b `xor` 0x01 else b
  | (i, b) <- zip [0 ..] (encodeSwapBlock goldenGrant) ]

emitSwapCarrierGolden :: Text
emitSwapCarrierGolden = T.unlines
  [ "// GENERATED by sixfour-spec / Codegen.SwapCarrier — do not edit by hand."
  , "// Regenerate with: cabal run spec-codegen."
  , "//"
  , "// Byte-exact golden for the S4GX gene-in-GIF codec (SixFour.Spec.SwapCarrier)."
  , "// The Swift SwapCarrier.encode must reproduce `encodedShowcase`/`encodedGrant`"
  , "// EXACTLY and extract back to the pinned fields; the two negative vectors must"
  , "// refuse (corrupt via CRC, future-major via version check), never partially parse."
  , ""
  , "enum SwapCarrierGolden {"
  , "    /// wire versions: major, minor."
  , "    static let version: [Int] = [" <> tshow (fromIntegral swapMajor :: Int)
      <> ", " <> tshow (fromIntegral swapMinor :: Int) <> "]"
  , "    /// the registry gene name."
  , "    static let geneName = \"" <> T.pack (spGeneName goldenGrant) <> "\""
  , "    /// lineage tag: gene, creator, minted."
  , "    static let tag: [Int] = " <> intArr [gene, creator, gtMinted t]
  , "    /// lineage parents (remix shape: two parents, one negative)."
  , "    static let parents: [Int] = " <> intArr parents
  , "    /// the Int32 Q16 weight words (21 — the theta-up registry size)."
  , "    static let weights: [Int] = " <> intArr (spWeights goldenGrant)
  , ""
  , "    /// the SHOWCASE byte stream (same gene, ZERO weight words on the wire)."
  , "    static let encodedShowcase: [UInt8] = " <> byteArr (encodeSwapBlock goldenShowcase)
  , "    /// the GRANT byte stream (weights included)."
  , "    static let encodedGrant: [UInt8] = " <> byteArr (encodeSwapBlock goldenGrant)
  , ""
  , "    /// NEGATIVE: the grant with one body byte flipped — extraction must refuse (CRC)."
  , "    static let corruptEncoded: [UInt8] = " <> byteArr corruptStream
  , "    /// NEGATIVE: the same payload at MAJOR+1 — extraction must report a version mismatch."
  , "    static let versionMismatchEncoded: [UInt8] = "
      <> byteArr (encodeSwapBlockVersioned (swapMajor + 1) swapMinor goldenGrant)
  , "}"
  ]
  where
    t = spTag goldenGrant
    GeneId gene       = gtGene t
    CreatorId creator = gtCreator t
    parents           = [ g | GeneId g <- gtParents t ]

tshow :: Show a => a -> Text
tshow = T.pack . show

intArr :: [Int] -> Text
intArr xs = "[" <> T.intercalate ", " (map tshow xs) <> "]"

byteArr :: [Word8] -> Text
byteArr xs = "[" <> T.intercalate ", " (map tshow xs) <> "]"
