{- |
Module      : SixFour.Codegen.Swift
Description : Emit Swift contracts to @SixFour/Generated/@.

Produces two files:

  * @StageContract.swift@ — the Stage A quantizer contract and the
    @CompleteVoxelVolume@ brand type the iOS app uses to assert
    strict per-frame surjectivity at encode time.
  * @NetContract.swift@   — slot enum + input/output dimensions for the
    deferred NN slots (metric / merger / embedder).

The emitter is intentionally **string-templated** rather than using
any pretty-printer library: the generated code is read by humans,
diffed by humans, and reviewed by humans, so legibility wins over
combinator elegance.
-}
module SixFour.Codegen.Swift
  ( emitStageContract
  , emitNetContract
  , emitSTBN3DContract
  , emitSignificanceContract
  , emitGlobalVolumeContract
  , emitLatticeContract
  , emitCellShapesContract
  , emitSevenSegContract
  ) where

import qualified Data.Text    as T
import           Data.Text    (Text)

import SixFour.Spec.Color    (m1, m2)
import SixFour.Spec.Shape
import SixFour.Spec.Coverage (coverageBinsPerAxis)
import SixFour.Spec.Significance (confidenceZ, minPopulation, chiSquare3Critical)
import SixFour.Spec.Net
import qualified SixFour.Spec.Lattice as L
import qualified SixFour.Spec.CellShapes as CS
import qualified SixFour.Spec.SevenSeg as SS

-- | Generate @GlobalVolumeContract.swift@ — the whole-GIF brands for a single
-- global palette (GIFB). Mirrors 'SixFour.Spec.GlobalVolume'. The Swift logic
-- references 'SixFourShape' / 'SixFourSignificance' at runtime, so this emitter is
-- a fixed template (no Haskell-constant interpolation).
emitGlobalVolumeContract :: Text
emitGlobalVolumeContract = T.unlines
  [ "// GENERATED by sixfour-spec / Codegen.Swift — do not edit by hand."
  , "// Source of truth: ~/SixFour/spec/src/SixFour/Spec/GlobalVolume.hs"
  , "// Regenerate with: cabal run spec-codegen"
  , ""
  , "import Foundation"
  , ""
  , "/// `GlobalCompleteVolume` brand: a single-global-palette (GIFB) index volume is"
  , "/// complete iff exactly `SixFourShape.T` frames, each `pixelsPerFrame` long, and"
  , "/// the UNION over all frames is surjective onto all `SixFourShape.K` slots. A"
  , "/// single frame need NOT use all K — the per-frame `CompleteVoxelVolume`"
  , "/// requirement is RELAXED to the whole GIF (a global palette is shared, so one"
  , "/// frame may touch only some colours). Mirrors `SixFour.Spec.GlobalVolume`."
  , "/// Constructed only by `init?(checkingFrames:)`; the brand cannot be forged."
  , "public struct GlobalCompleteVolume: Sendable {"
  , "    public let frames: [[UInt8]]"
  , "    public init?(checkingFrames fs: [[UInt8]]) {"
  , "        guard fs.count == SixFourShape.T else { return nil }"
  , "        let perFrame = SixFourShape.pixelsPerFrame"
  , "        var seen = Set<UInt8>(); seen.reserveCapacity(SixFourShape.K)"
  , "        for f in fs {"
  , "            guard f.count == perFrame else { return nil }"
  , "            for x in f { seen.insert(x) }"
  , "        }"
  , "        guard seen.count == SixFourShape.K else { return nil }"
  , "        self.frames = fs"
  , "    }"
  , "}"
  , ""
  , "/// `GlobalSignificantVolume` brand: every global slot is backed by"
  , "/// `≥ SixFourSignificance.minPopulation` POOLED pixels (summed over the whole"
  , "/// GIF, not per frame), and the total mass is exactly `T · pixelsPerFrame`. So"
  , "/// \"no empty / donated-outlier slot ships\" survives at GIF scale (guaranteed by"
  , "/// the whole-GIF significance rescue). Mirrors `SixFour.Spec.GlobalVolume.globalSignificant`."
  , "public struct GlobalSignificantVolume: Sendable {"
  , "    public let complete: GlobalCompleteVolume"
  , "    /// `pooledCounts[j]` = total pixels assigned to global slot j across all frames."
  , "    public init?(complete: GlobalCompleteVolume, pooledCounts: [Int]) {"
  , "        guard pooledCounts.count == SixFourShape.K else { return nil }"
  , "        guard pooledCounts.reduce(0, +) == SixFourShape.T * SixFourShape.pixelsPerFrame else { return nil }"
  , "        for c in pooledCounts where c < SixFourSignificance.minPopulation { return nil }"
  , "        self.complete = complete"
  , "    }"
  , "}"
  ]

-- | Generate @LatticeContract.swift@ — the GRID capture-HUD lattice constants,
-- mirrored byte-for-byte from 'SixFour.Spec.Lattice'. This is the source of truth
-- the hand-written @GlobalLattice.swift@ facade references (Law #5); the pitch is
-- the gcd theorem (@cellPt = gcd 402 874@), not a literal. @selfCheck()@ re-asserts
-- the spec laws at runtime as defense-in-depth.
emitLatticeContract :: Text
emitLatticeContract = T.unlines
  [ "// GENERATED by sixfour-spec / Codegen.Swift — do not edit by hand."
  , "// Source of truth: ~/SixFour/spec/src/SixFour/Spec/Lattice.hs"
  , "// Regenerate with: cabal run spec-codegen"
  , ""
  , "import Foundation"
  , ""
  , "/// The GRID capture-HUD lattice — every governed chrome dimension, in cells."
  , "/// The 2 pt pitch is `gcd(402, 874)`, the unique value that tiles the iPhone 17"
  , "/// Pro portrait screen edge-to-edge (→ exactly 201×437 cells). `GlobalLattice`"
  , "/// is the typed `CGFloat` facade over these constants, NOT an independent"
  , "/// authority (GRID Law #5). Mirrors `SixFour.Spec.Lattice`; `cabal test` proves"
  , "/// the laws every CI run."
  , "public enum SixFourLattice {"
  , "    /// Reference anchor: iPhone 17 Pro portrait logical size + @3x scale."
  , "    public static let screenWidthPt: Int = "  <> tshow L.screenWidthPt
  , "    public static let screenHeightPt: Int = " <> tshow L.screenHeightPt
  , "    public static let scale: Int = "          <> tshow L.scale
  , ""
  , "    /// The one pitch: gcd(402,874) = 2 pt = 6 device-px @3x."
  , "    public static let cellPt: Int = " <> tshow L.cellPt
  , "    public static let cellPx: Int = " <> tshow L.cellPx
  , "    /// The full-screen lattice in cells (201 cols × 437 rows)."
  , "    public static let cols: Int = " <> tshow L.cols
  , "    public static let rows: Int = " <> tshow L.rows
  , ""
  , "    /// The φ-ratio size ladder; widgets grow by ladder steps, never by pitch."
  , "    public static let fibLadder: [Int] = " <> intListLiteral L.fibLadder
  , ""
  , "    /// Widget cell-counts (square blocks; grow by more cells, never bigger cells)."
  , "    public static let previewCells: Int = "   <> tshow L.previewCells
  , "    public static let touchFloorCells: Int = " <> tshow L.touchFloorCells
  , "    public static let controlCells: Int = "   <> tshow L.controlCells
  , "    public static let shutterCells: Int = "   <> tshow L.shutterCells
  , "    public static let ringCells: Int = "      <> tshow L.ringCells
  , "    public static let ringTicks: Int = "      <> tshow L.ringTicks
  , "    public static let wordmarkRows: Int = "   <> tshow L.wordmarkRows
  , "    public static let wordmarkCols: Int = "   <> tshow L.wordmarkCols
  , "    public static let segmentCells: Int = "   <> tshow L.segmentCells
  , "    public static let gutterCells: Int = "    <> tshow L.gutterCells
  , "    public static let shutterDiscRadiusCells: Int = "    <> tshow L.shutterDiscRadiusCells
  , "    public static let shutterRingThicknessCells: Int = " <> tshow L.shutterRingThicknessCells
  , ""
  , "    /// The golden vertical layout (preview anchor + above/below split, below/above ≈ φ)."
  , "    public static let previewStartRow: Int = " <> tshow L.previewStartRow
  , "    public static let previewEndRow: Int = "   <> tshow L.previewEndRow
  , "    public static let previewStartCol: Int = " <> tshow L.previewStartCol
  , "    public static let previewEndCol: Int = "   <> tshow L.previewEndCol
  , "    public static let aboveRows: Int = " <> tshow L.aboveRows
  , "    public static let belowRows: Int = " <> tshow L.belowRows
  , ""
  , "    /// Cells → points. The single place a cell count becomes a point size."
  , "    @inline(__always) public static func cellsToPt(_ cells: Int) -> Int { cells * cellPt }"
  , ""
  , "    /// Re-asserts the Haskell laws at runtime (defense-in-depth). True iff the"
  , "    /// emitted constants satisfy every GRID geometry invariant."
  , "    public static func selfCheck() -> Bool {"
  , "        cellPt == 2"
  , "        && cols * cellPt == screenWidthPt && rows * cellPt == screenHeightPt"
  , "        && cols == 201 && rows == 437"
  , "        && shutterDiscRadiusCells * 2 + shutterRingThicknessCells * 2 == shutterCells"
  , "        && shutterCells >= touchFloorCells && controlCells >= touchFloorCells"
  , "        && segmentCells >= touchFloorCells && cellsToPt(touchFloorCells) == 44"
  , "        && fibLadder.contains(shutterCells)"
  , "        && aboveRows + previewCells + belowRows == rows"
  , "        && (previewEndCol - previewStartCol + 1) == previewCells"
  , "        && (previewEndRow - previewStartRow + 1) == previewCells"
  , "        && previewStartCol % 2 == 0 && previewStartCol + previewEndCol == cols - 2"
  , "        && 7 * 16 + 6 * 2 == wordmarkCols"
  , "    }"
  , "}"
  ]

-- | A Swift @[Int]@ literal.
intListLiteral :: [Int] -> Text
intListLiteral xs = "[" <> T.intercalate ", " (map tshow xs) <> "]"

-- | Generate @CellShapesContract.swift@ — the golden 64-tick ring endpoint table
-- and the ring-tick radius, mirrored from 'SixFour.Spec.CellShapes'. The renderer
-- indexes this table instead of recomputing @atan2@ per cell. @selfCheck()@
-- recomputes the endpoints from @sin@/@cos@ and asserts equality — a live
-- Haskell↔Swift IEEE-754 parity gate (the table is portable because it uses
-- @floor@, not @round@).
emitCellShapesContract :: Text
emitCellShapesContract = T.unlines $
  [ "// GENERATED by sixfour-spec / Codegen.Swift — do not edit by hand."
  , "// Source of truth: ~/SixFour/spec/src/SixFour/Spec/CellShapes.hs"
  , "// Regenerate with: cabal run spec-codegen"
  , ""
  , "import Foundation"
  , "import simd"
  , ""
  , "/// Golden cell-mask geometry for the GRID HUD primitives. The diversity gauge's"
  , "/// 64 tick endpoints are precomputed here (one cell per tick, k=0 at top,"
  , "/// clockwise) so the renderer never recomputes `atan2` per cell. Mirrors"
  , "/// `SixFour.Spec.CellShapes`; the table is bit-portable because it uses `floor`"
  , "/// (identical IEEE-754 on both sides), not `round`."
  , "public enum SixFourCellShapes {"
  , "    /// The radius (in cells, from the sprite centre) at which a gauge tick ends."
  , "    public static let ringTickRadius: Double = " <> tshowF CS.ringTickRadius
  , ""
  , "    /// The 64 tick outer-endpoint cells, in tick order (k = 0 at top, clockwise)."
  , "    /// `x` = column, `y` = row, in the 60×60 gauge sprite."
  , "    public static let ringTickEndpoints: [SIMD2<Int>] = ["
  ]
  ++ [ "        SIMD2<Int>(" <> tshow c <> ", " <> tshow r <> ")," | (c, r) <- CS.ringTickEndpoints ]
  ++
  [ "    ]"
  , ""
  , "    /// Recomputes the endpoints from sin/cos and asserts equality with the table"
  , "    /// above — proving Swift's IEEE-754 floor matches the Haskell golden."
  , "    public static func selfCheck() -> Bool {"
  , "        let c0 = Double(SixFourLattice.ringCells) / 2"
  , "        let n  = SixFourLattice.ringTicks"
  , "        guard ringTickEndpoints.count == n else { return false }"
  , "        for k in 0..<n {"
  , "            let theta = 2 * Double.pi * Double(k) / Double(n)"
  , "            let px = c0 + ringTickRadius * sin(theta)"
  , "            let py = c0 - ringTickRadius * cos(theta)"
  , "            let want = SIMD2<Int>(Int(floor(px)), Int(floor(py)))"
  , "            if ringTickEndpoints[k] != want { return false }"
  , "        }"
  , "        return true"
  , "    }"
  , "}"
  ]

-- | A Swift @[SIMD2<Int>]@ cell-list literal.
cellListLiteral :: [(Int, Int)] -> Text
cellListLiteral cells =
  "[" <> T.intercalate ", " [ "SIMD2<Int>(" <> tshow c <> ", " <> tshow r <> ")" | (c, r) <- cells ] <> "]"

-- | Generate @SevenSegContract.swift@ — the 7-segment digit register, mirrored from
-- 'SixFour.Spec.SevenSeg'. Emits the ghost footprint (the full "8") and the lit cells
-- of each digit 0–9, so @CellDigits@ renders a fixed-width two-ink count that never
-- reflows (design language §6.9).
emitSevenSegContract :: Text
emitSevenSegContract = T.unlines $
  [ "// GENERATED by sixfour-spec / Codegen.Swift — do not edit by hand."
  , "// Source of truth: ~/SixFour/spec/src/SixFour/Spec/SevenSeg.hs"
  , "// Regenerate with: cabal run spec-codegen"
  , ""
  , "import Foundation"
  , "import simd"
  , ""
  , "/// The 7-segment digit register: golden cell masks for the GRID CountReadout."
  , "/// `allSegmentCells` is the full \"8\" footprint, drawn in ghost so every digit"
  , "/// (and a blanked leading digit) occupies the identical 96-cell box and never"
  , "/// reflows; `digitLitCells[d]` are the cells lit white for digit d. Mirrors"
  , "/// `SixFour.Spec.SevenSeg`; pinned by `cabal test`."
  , "public enum SixFourSevenSeg {"
  , "    public static let digitBoxCols: Int = " <> tshow SS.digitBoxCols
  , "    public static let digitBoxRows: Int = " <> tshow SS.digitBoxRows
  , ""
  , "    /// The full \"8\" footprint — drawn in ledGhost behind every digit."
  , "    public static let allSegmentCells: [SIMD2<Int>] = " <> cellListLiteral SS.allSegmentCells
  , ""
  , "    /// The cells lit white for each digit 0…9 (index = digit value)."
  , "    public static let digitLitCells: [[SIMD2<Int>]] = ["
  ]
  ++ [ "        " <> cellListLiteral (SS.litCells d) <> ",   // " <> tshow d | d <- [0 .. 9] ]
  ++
  [ "    ]"
  , "}"
  ]

-- | Generate @StageContract.swift@.
emitStageContract :: Text
emitStageContract = T.unlines
  [ "// GENERATED by sixfour-spec / Codegen.Swift — do not edit by hand."
  , "// Source of truth: ~/SixFour/spec/src/SixFour/Spec/Shape.hs +"
  , "//                  ~/SixFour/spec/src/SixFour/Spec/Color.hs"
  , "// Regenerate with: cabal run spec-codegen"
  , ""
  , "import Foundation"
  , "import simd"
  , ""
  , "/// Compile-time SixFour shape constants. These four numbers are"
  , "/// the only place these magic numbers may appear; anywhere else"
  , "/// in the iOS app must reference them through `SixFourShape`."
  , "public enum SixFourShape {"
  , "    public static let T: Int = " <> tshow tVal
  , "    public static let H: Int = " <> tshow hVal
  , "    public static let W: Int = " <> tshow wVal
  , "    public static let K: Int = " <> tshow kVal
  , "    public static let pixelsPerFrame: Int = " <> tshow pixelsPerFrame
  , "    public static let pixelsPerGIF: Int   = " <> tshow pixelsPerGIF
  , "    public static let candidatesAfterStageA: Int = " <> tshow candidatesAfterStageA
  , "    /// Bins per OKLab axis for the gamut-coverage diversity metric"
  , "    /// (`coverageBinsPerAxis³` voxels). Pinned to SixFour.Spec.Coverage."
  , "    public static let coverageBinsPerAxis: Int = " <> tshow coverageBinsPerAxis
  , "}"
  , ""
  , "/// OKLab triple, bit-exact mirror of `SixFour/Color/ColorScience.swift`."
  , "/// Constants below MUST match — `cabal test` checks this every CI run."
  , "public enum SixFourOKLabConstants {"
  , emitMatrix "M1" m1
  , emitMatrix "M2" m2
  , "}"
  , ""
  , "/// `CompleteVoxelVolume` brand: proof that a per-frame index volume is"
  , "/// a complete T×H×W voxel cube — exactly `SixFourShape.T` frames, each"
  , "/// of `SixFourShape.pixelsPerFrame` indices, and each frame"
  , "/// independently surjective onto all `SixFourShape.K` palette slots"
  , "/// (strict per-frame surjectivity). The GIF encoder accepts only this"
  , "/// type, so a GIF with a dropped frame, a short frame, or a frame that"
  , "/// fails to exercise all K colours is unrepresentable at the call site."
  , "/// Constructed only by `init?(checkingFrames:)`, which performs the"
  , "/// O(T·H·W) scan; the brand cannot be forged."
  , "public struct CompleteVoxelVolume: Sendable {"
  , "    /// `frames[f]`: row-major UInt8 indices for frame f, length H·W."
  , "    public let frames: [[UInt8]]"
  , "    public init?(checkingFrames fs: [[UInt8]]) {"
  , "        guard fs.count == SixFourShape.T else { return nil }"
  , "        let perFrame = SixFourShape.pixelsPerFrame"
  , "        for f in fs {"
  , "            guard f.count == perFrame else { return nil }"
  , "            var seen = Set<UInt8>(); seen.reserveCapacity(SixFourShape.K)"
  , "            for x in f { seen.insert(x) }"
  , "            guard seen.count == SixFourShape.K else { return nil }"
  , "        }"
  , "        self.frames = fs"
  , "    }"
  , "}"
  , ""
  , "/// Stage A contract: per-frame quantizer."
  , "public protocol StageAContract {"
  , "    /// Input: H*W OKLab triples (row-major)."
  , "    /// Output: (palette of K OKLab triples, indices of length H*W)."
  , "    func quantize(frameOKLab: [SIMD3<Float>])"
  , "      -> (palette: [SIMD3<Float>], indices: [UInt8])"
  , "}"
  ]

emitMatrix
  :: Text
  -> ((Double, Double, Double), (Double, Double, Double), (Double, Double, Double))
  -> Text
emitMatrix nm ((a, b, c), (d, e, f), (g, h, i)) = T.unlines
  [ "    /// 3x3 OKLab matrix `" <> nm <> "`, row-major."
  , "    public static let " <> nm <> ": [[Float]] = ["
  , "        [" <> tshowF a <> ", " <> tshowF b <> ", " <> tshowF c <> "],"
  , "        [" <> tshowF d <> ", " <> tshowF e <> ", " <> tshowF f <> "],"
  , "        [" <> tshowF g <> ", " <> tshowF h <> ", " <> tshowF i <> "]"
  , "    ]"
  ]

-- | Generate @SignificanceContract.swift@ — the per-frame palette
-- significance constants, the @SixFourSignificantCell@ (a palette slot as a
-- centroid + per-axis range + population + provenance), and the
-- @SignificantVoxelVolume@ brand: a 'CompleteVoxelVolume' in which every slot
-- of every frame is backed by @≥ minPopulation@ pixels (no donated outlier),
-- with exact mass conservation. Bit-mirrors "SixFour.Spec.Significance".
emitSignificanceContract :: Text
emitSignificanceContract = T.unlines
  [ "// GENERATED by sixfour-spec / Codegen.Swift — do not edit by hand."
  , "// Source of truth: ~/SixFour/spec/src/SixFour/Spec/Significance.hs"
  , "// Regenerate with: cabal run spec-codegen"
  , ""
  , "import Foundation"
  , "import simd"
  , ""
  , "/// Per-frame palette significance constants, mirrored from the Haskell"
  , "/// spec so the app, the oracle, and the trainer score significance"
  , "/// identically. Significance is **population**: a palette slot is"
  , "/// significant iff backed by `minPopulation` pixels — the opposite of a"
  , "/// donated single-pixel outlier. Each slot owns the OKLab range"
  , "/// `mean ± confidenceZ · σ` (the \"range for each bin\")."
  , "public enum SixFourSignificance {"
  , "    /// Two-sided 95% normal quantile z_{0.975} for the per-axis range."
  , "    public static let confidenceZ: Double = " <> tshowF confidenceZ
  , "    /// Minimum pixel population for a slot to be significant (anti-outlier)."
  , "    public static let minPopulation: Int = " <> tshow minPopulation
  , "    /// χ²₃ right-tail critical values P(χ²₃ > v) = α. Single source of"
  , "    /// truth — `ClusterStatisticsOps.ChiSquare3` must defer to this."
  , "    public static func chiSquare3Critical(alpha: Double) -> Double {"
  , "        switch alpha {"
  , "        case 0.001: return " <> tshowF (chiSquare3Critical 0.001)
  , "        case 0.01:  return " <> tshowF (chiSquare3Critical 0.01)
  , "        case 0.025: return " <> tshowF (chiSquare3Critical 0.025)
  , "        case 0.05:  return " <> tshowF (chiSquare3Critical 0.05)
  , "        case 0.10:  return " <> tshowF (chiSquare3Critical 0.10)
  , "        default:    return " <> tshowF (chiSquare3Critical 0.05)
  , "        }"
  , "    }"
  , "    /// A frame of `pixels` can be partitioned into `k` all-significant"
  , "    /// slots iff `pixels ≥ minPopulation · k`. The SixFour shape"
  , "    /// (4096 ≥ 2·256 = 512) satisfies this with a factor of 8 to spare,"
  , "    /// so the all-significant guarantee cannot fail."
  , "    public static func feasible(pixels: Int, k: Int) -> Bool {"
  , "        pixels >= minPopulation * k"
  , "    }"
  , "}"
  , ""
  , "/// Where a palette slot's population came from."
  , "public enum SixFourProvenance: String, Sendable, Codable, CaseIterable {"
  , "    case extracted   // a genuine cluster mode (count ≥ minPopulation)"
  , "    case split       // a sub-mode created to reach K (count ≥ minPopulation)"
  , "    case degenerate  // could not be backed by minPopulation pixels — unreachable on the SixFour shape"
  , "}"
  , ""
  , "/// One palette slot as a statistical cell: centroid, per-axis std-dev"
  , "/// (√ of the OKLab covariance diagonal), population, and provenance."
  , "/// The OKLab range it owns is `mean ± confidenceZ · stdDev`."
  , "public struct SixFourSignificantCell: Sendable {"
  , "    public let mean: SIMD3<Float>"
  , "    public let stdDev: SIMD3<Float>"
  , "    public let count: Int"
  , "    public let provenance: SixFourProvenance"
  , ""
  , "    public init(mean: SIMD3<Float>, stdDev: SIMD3<Float>, count: Int, provenance: SixFourProvenance) {"
  , "        self.mean = mean; self.stdDev = stdDev; self.count = count; self.provenance = provenance"
  , "    }"
  , ""
  , "    /// Lower corner of the α-confidence range box."
  , "    public var rangeLo: SIMD3<Float> { mean - Float(SixFourSignificance.confidenceZ) * stdDev }"
  , "    /// Upper corner of the α-confidence range box."
  , "    public var rangeHi: SIMD3<Float> { mean + Float(SixFourSignificance.confidenceZ) * stdDev }"
  , "    /// Significant ⇔ backed by ≥ minPopulation pixels (not an outlier)."
  , "    public var isSignificant: Bool { count >= SixFourSignificance.minPopulation }"
  , "}"
  , ""
  , "/// `SignificantVoxelVolume` brand: a `CompleteVoxelVolume` (every frame"
  , "/// surjective onto all K slots) in which, additionally, every palette"
  , "/// slot of every frame is statistically significant — backed by"
  , "/// `≥ minPopulation` pixels (so none is a donated outlier) — with exact"
  , "/// per-frame mass conservation. The per-frame `cells` carry the OKLab"
  , "/// ranges. Constructed only by `init?`, which performs the O(T·K) scan;"
  , "/// the brand cannot be forged. The GIF encoder consumes `.complete`."
  , "///"
  , "/// Laws (cross-reference SixFour.Spec.Significance):"
  , "///   * Def 22 MassConservation — Σ count = pixelsPerFrame, per frame."
  , "///   * Def 23 AllSignificant   — every slot count ≥ minPopulation."
  , "///   * Thm 7 NoOutlier         — significance is population, never a count-1 slot."
  , "public struct SignificantVoxelVolume: Sendable {"
  , "    public let complete: CompleteVoxelVolume"
  , "    /// `cells[f]`: the K palette cells of frame f, in slot order."
  , "    public let cells: [[SixFourSignificantCell]]"
  , ""
  , "    public init?(complete: CompleteVoxelVolume, cells: [[SixFourSignificantCell]]) {"
  , "        guard cells.count == SixFourShape.T else { return nil }"
  , "        for frame in cells {"
  , "            guard frame.count == SixFourShape.K else { return nil }"
  , "            var mass = 0"
  , "            for c in frame {"
  , "                guard c.isSignificant else { return nil }   // no outlier slots"
  , "                mass += c.count"
  , "            }"
  , "            guard mass == SixFourShape.pixelsPerFrame else { return nil }"
  , "        }"
  , "        self.complete = complete"
  , "        self.cells = cells"
  , "    }"
  , ""
  , "    /// The wire-relevant per-frame index frames (delegated to the brand"
  , "    /// the encoder already accepts)."
  , "    public var frames: [[UInt8]] { complete.frames }"
  , "}"
  ]

-- | Generate @NetContract.swift@.
emitNetContract :: Text
emitNetContract = T.unlines
  [ "// GENERATED by sixfour-spec / Codegen.Swift — do not edit by hand."
  , "// Source of truth: ~/SixFour/spec/src/SixFour/Spec/Net.hs"
  , "// Regenerate with: cabal run spec-codegen"
  , ""
  , "import Foundation"
  , ""
  , "/// Candidate NN slot identifiers. `.metric` ships today (trainer +"
  , "/// consumer); `.look` is the σ-equivariant look-NN whose FORM is pinned"
  , "/// here (the on-device forward pass loads weights of exactly this shape)."
  , "public enum SixFourNetSlot: String, CaseIterable, Codable, Sendable {"
  , "    case metric = \"metric\""
  , "    case look = \"look\""
  , "}"
  , ""
  , "/// I/O dimensions for each slot, mirrored from the Haskell spec."
  , "public enum SixFourNetIO {"
  , "    public struct Spec: Sendable {"
  , "        public let inputDim: Int"
  , "        public let outputDim: Int"
  , "        public let description: String"
  , "    }"
  , emitSlotSpec "metric" slotMetricDims
  , ""
  , emitSlotSpec "look" slotLookDims
  , ""
  , "    /// The metric organ ships as the 6 upper-triangle floats of the"
  , "    /// 3x3 PSD matrix M = L Lᵀ produced by trainer/train_metric.py."
  , "    public static let metricPSDUpperTriangleCount: Int = "
      <> tshow metricPSDUpperTriangleCount
  , ""
  , "    /// The look-NN FORM (σ-pair decoder), the single canonical seam the MLX"
  , "    /// trainer, the Haskell golden, and the on-device forward pass all share."
  , "    /// `lookSigmaPairDOF` = the 384 SigmaPairTree coefficients the decoder emits"
  , "    /// (= 3·128 σ-pair generators), reconstructed into the 256-leaf palette."
  , "    /// NOT 768: 768 is the FLAT leaf space (256·3) the genome reconstructs INTO."
  , "    public static let lookSigmaPairDOF: Int = " <> tshow (netOutputDim slotLookDims)
  , "    /// MODEL_DIM / CORE_DEPTH / SIGMA_PAIR_LEAVES / MAX_TOKENS (mirrors"
  , "    /// net_shape.py aux_dims; source SixFour.Spec.Net.slotLookDims)."
  , "    public static let lookAuxDims: [String: Int] = "
      <> auxDictLiteral (netAuxDims slotLookDims)
  , "}"
  ]

emitSlotSpec :: Text -> NetIO -> Text
emitSlotSpec nm io = T.unlines
  [ "    public static let " <> nm <> ": Spec = Spec("
  , "        inputDim: "    <> tshow (netInputDim io) <> ","
  , "        outputDim: "   <> tshow (netOutputDim io) <> ","
  , "        description: \"" <> T.pack (netDescription io) <> "\""
  , "    )"
  ]

-- | A Swift `[String: Int]` literal mirroring the slot's aux dims. The source
-- list (Net.slotLookDims) has a fixed order, so the generated text is deterministic.
auxDictLiteral :: [(String, Int)] -> Text
auxDictLiteral xs =
  "[" <> T.intercalate ", "
         [ "\"" <> T.pack k <> "\": " <> tshow v | (k, v) <- xs ]
     <> "]"

tshow :: Show a => a -> Text
tshow = T.pack . show

-- | Emit a Double as a Swift Float literal with full precision.
tshowF :: Double -> Text
tshowF x = T.pack (show x)

-- | Generate @STBN3DContract.swift@. Emits ONLY:
--
--   * 'STBN3DMaskLoader' — reads @Resources/stbn3d-8.bin@ (the 8³ blue-noise
--     tile produced by 'SixFour.Spec.STBN3D.generateSTBN3D') and tiles it to
--     the full 64³ mask consumed by 'PaletteGenerator.swift's blue-noise
--     dither path.
--
-- The retired @emitHybridContract@ also emitted 'SixFourHybridShape',
-- 'SixFourHybridParams', 'SixFourHybridSlot', and three witness types for the
-- trunk+delta palette direction; that direction was deleted when the math-first
-- LookNetE/R/D pipeline replaced it. The STBN3D mask survives because it is
-- the on-device blue-noise reference; nothing else in the Hybrid namespace did.
emitSTBN3DContract :: Text
emitSTBN3DContract = T.unlines
  [ "// GENERATED by sixfour-spec / Codegen.Swift — do not edit by hand."
  , "// Source of truth: ~/SixFour/spec/src/SixFour/Spec/STBN3D.hs"
  , "// Regenerate with: cabal run spec-codegen"
  , ""
  , "import Foundation"
  , ""
  , "/// Loader for the precomputed scalar 3D blue-noise mask."
  , "///"
  , "/// The bit-exact ground truth is `SixFour.Spec.STBN3D`'s"
  , "/// `generateSTBN3D @8 @8 @8`, written to `Resources/stbn3d-8.bin`"
  , "/// (512 bytes). `loadTiled` tiles that 8³ pattern toroidally to"
  , "/// produce the full 64³ mask. The tile uses toroidal distance"
  , "/// during generation, so the tiling is mathematically clean: no"
  , "/// edge discontinuities, only a soft 8-voxel periodic structure."
  , "public enum STBN3DMaskLoader {"
  , "    /// Returns the raw 8³ tile (512 bytes) loaded from the bundle."
  , "    public static func loadTile(bundle: Bundle = .main) -> [UInt8]? {"
  , "        guard let url = bundle.url(forResource: \"stbn3d-8\","
  , "                                    withExtension: \"bin\"),"
  , "              let data = try? Data(contentsOf: url),"
  , "              data.count == 8 * 8 * 8"
  , "        else { return nil }"
  , "        return Array(data)"
  , "    }"
  , ""
  , "    /// Returns the full 64³ mask, produced by tiling the 8³ tile"
  , "    /// 8 × 8 × 8 times along (t, y, x)."
  , "    public static func loadTiled(bundle: Bundle = .main) -> [UInt8]? {"
  , "        guard let tile = loadTile(bundle: bundle) else { return nil }"
  , "        let T = SixFourShape.T"
  , "        let H = SixFourShape.H"
  , "        let W = SixFourShape.W"
  , "        var out = [UInt8](repeating: 0, count: T * H * W)"
  , "        for f in 0..<T { for y in 0..<H { for x in 0..<W {"
  , "            out[(f * H + y) * W + x] = tile[((f % 8) * 8 + (y % 8)) * 8 + (x % 8)]"
  , "        } } }"
  , "        return out"
  , "    }"
  , "}"
  ]
