{- |
Module      : SixFour.Codegen.Swift
Description : Emit Swift contracts to @SixFour/Generated/@.

Produces two files:

  * @StageContract.swift@ — the Stage A quantizer contract and the
    @CompleteVoxelVolume@ brand type the iOS app uses to assert
    strict per-frame surjectivity at encode time.
  * @NetContract.swift@   — slot enum + input/output dimensions for the
    deferred NN slots (metric / merger / embedder).

The emitter is intentionally **string-templated** rather than using
any pretty-printer library: the generated code is read by humans,
diffed by humans, and reviewed by humans, so legibility wins over
combinator elegance.
-}
module SixFour.Codegen.Swift
  ( emitStageContract
  , emitNetContract
  , emitHybridContract
  , emitSignificanceContract
  ) where

import qualified Data.Text    as T
import           Data.Text    (Text)

import SixFour.Spec.Color    (m1, m2)
import SixFour.Spec.Shape
import SixFour.Spec.Coverage (coverageBinsPerAxis)
import SixFour.Spec.Significance (confidenceZ, minPopulation, chiSquare3Critical)
import SixFour.Spec.Net
import SixFour.Spec.Hybrid.Shape
  ( kTrunkVal, kDeltaVal
  , defaultTauPresence, unTauPresence
  , defaultEpsTrunk,    unEpsTrunk
  , defaultDeltaSnapMargin, unDeltaSnapMargin
  )

-- | Generate @StageContract.swift@.
emitStageContract :: Text
emitStageContract = T.unlines
  [ "// GENERATED by sixfour-spec / Codegen.Swift — do not edit by hand."
  , "// Source of truth: ~/SixFour/spec/src/SixFour/Spec/Shape.hs +"
  , "//                  ~/SixFour/spec/src/SixFour/Spec/Color.hs"
  , "// Regenerate with: cabal run spec-codegen"
  , ""
  , "import Foundation"
  , "import simd"
  , ""
  , "/// Compile-time SixFour shape constants. These four numbers are"
  , "/// the only place these magic numbers may appear; anywhere else"
  , "/// in the iOS app must reference them through `SixFourShape`."
  , "public enum SixFourShape {"
  , "    public static let T: Int = " <> tshow tVal
  , "    public static let H: Int = " <> tshow hVal
  , "    public static let W: Int = " <> tshow wVal
  , "    public static let K: Int = " <> tshow kVal
  , "    public static let pixelsPerFrame: Int = " <> tshow pixelsPerFrame
  , "    public static let pixelsPerGIF: Int   = " <> tshow pixelsPerGIF
  , "    public static let candidatesAfterStageA: Int = " <> tshow candidatesAfterStageA
  , "    /// Bins per OKLab axis for the gamut-coverage diversity metric"
  , "    /// (`coverageBinsPerAxis³` voxels). Pinned to SixFour.Spec.Coverage."
  , "    public static let coverageBinsPerAxis: Int = " <> tshow coverageBinsPerAxis
  , "}"
  , ""
  , "/// OKLab triple, bit-exact mirror of `SixFour/Color/ColorScience.swift`."
  , "/// Constants below MUST match — `cabal test` checks this every CI run."
  , "public enum SixFourOKLabConstants {"
  , emitMatrix "M1" m1
  , emitMatrix "M2" m2
  , "}"
  , ""
  , "/// `CompleteVoxelVolume` brand: proof that a per-frame index volume is"
  , "/// a complete T×H×W voxel cube — exactly `SixFourShape.T` frames, each"
  , "/// of `SixFourShape.pixelsPerFrame` indices, and each frame"
  , "/// independently surjective onto all `SixFourShape.K` palette slots"
  , "/// (strict per-frame surjectivity). The GIF encoder accepts only this"
  , "/// type, so a GIF with a dropped frame, a short frame, or a frame that"
  , "/// fails to exercise all K colours is unrepresentable at the call site."
  , "/// Constructed only by `init?(checkingFrames:)`, which performs the"
  , "/// O(T·H·W) scan; the brand cannot be forged."
  , "public struct CompleteVoxelVolume: Sendable {"
  , "    /// `frames[f]`: row-major UInt8 indices for frame f, length H·W."
  , "    public let frames: [[UInt8]]"
  , "    public init?(checkingFrames fs: [[UInt8]]) {"
  , "        guard fs.count == SixFourShape.T else { return nil }"
  , "        let perFrame = SixFourShape.pixelsPerFrame"
  , "        for f in fs {"
  , "            guard f.count == perFrame else { return nil }"
  , "            var seen = Set<UInt8>(); seen.reserveCapacity(SixFourShape.K)"
  , "            for x in f { seen.insert(x) }"
  , "            guard seen.count == SixFourShape.K else { return nil }"
  , "        }"
  , "        self.frames = fs"
  , "    }"
  , "}"
  , ""
  , "/// Stage A contract: per-frame quantizer."
  , "public protocol StageAContract {"
  , "    /// Input: H*W OKLab triples (row-major)."
  , "    /// Output: (palette of K OKLab triples, indices of length H*W)."
  , "    func quantize(frameOKLab: [SIMD3<Float>])"
  , "      -> (palette: [SIMD3<Float>], indices: [UInt8])"
  , "}"
  ]

emitMatrix
  :: Text
  -> ((Double, Double, Double), (Double, Double, Double), (Double, Double, Double))
  -> Text
emitMatrix nm ((a, b, c), (d, e, f), (g, h, i)) = T.unlines
  [ "    /// 3x3 OKLab matrix `" <> nm <> "`, row-major."
  , "    public static let " <> nm <> ": [[Float]] = ["
  , "        [" <> tshowF a <> ", " <> tshowF b <> ", " <> tshowF c <> "],"
  , "        [" <> tshowF d <> ", " <> tshowF e <> ", " <> tshowF f <> "],"
  , "        [" <> tshowF g <> ", " <> tshowF h <> ", " <> tshowF i <> "]"
  , "    ]"
  ]

-- | Generate @SignificanceContract.swift@ — the per-frame palette
-- significance constants, the @SixFourSignificantCell@ (a palette slot as a
-- centroid + per-axis range + population + provenance), and the
-- @SignificantVoxelVolume@ brand: a 'CompleteVoxelVolume' in which every slot
-- of every frame is backed by @≥ minPopulation@ pixels (no donated outlier),
-- with exact mass conservation. Bit-mirrors "SixFour.Spec.Significance".
emitSignificanceContract :: Text
emitSignificanceContract = T.unlines
  [ "// GENERATED by sixfour-spec / Codegen.Swift — do not edit by hand."
  , "// Source of truth: ~/SixFour/spec/src/SixFour/Spec/Significance.hs"
  , "// Regenerate with: cabal run spec-codegen"
  , ""
  , "import Foundation"
  , "import simd"
  , ""
  , "/// Per-frame palette significance constants, mirrored from the Haskell"
  , "/// spec so the app, the oracle, and the trainer score significance"
  , "/// identically. Significance is **population**: a palette slot is"
  , "/// significant iff backed by `minPopulation` pixels — the opposite of a"
  , "/// donated single-pixel outlier. Each slot owns the OKLab range"
  , "/// `mean ± confidenceZ · σ` (the \"range for each bin\")."
  , "public enum SixFourSignificance {"
  , "    /// Two-sided 95% normal quantile z_{0.975} for the per-axis range."
  , "    public static let confidenceZ: Double = " <> tshowF confidenceZ
  , "    /// Minimum pixel population for a slot to be significant (anti-outlier)."
  , "    public static let minPopulation: Int = " <> tshow minPopulation
  , "    /// χ²₃ right-tail critical values P(χ²₃ > v) = α. Single source of"
  , "    /// truth — `ClusterStatisticsOps.ChiSquare3` must defer to this."
  , "    public static func chiSquare3Critical(alpha: Double) -> Double {"
  , "        switch alpha {"
  , "        case 0.001: return " <> tshowF (chiSquare3Critical 0.001)
  , "        case 0.01:  return " <> tshowF (chiSquare3Critical 0.01)
  , "        case 0.025: return " <> tshowF (chiSquare3Critical 0.025)
  , "        case 0.05:  return " <> tshowF (chiSquare3Critical 0.05)
  , "        case 0.10:  return " <> tshowF (chiSquare3Critical 0.10)
  , "        default:    return " <> tshowF (chiSquare3Critical 0.05)
  , "        }"
  , "    }"
  , "    /// A frame of `pixels` can be partitioned into `k` all-significant"
  , "    /// slots iff `pixels ≥ minPopulation · k`. The SixFour shape"
  , "    /// (4096 ≥ 2·256 = 512) satisfies this with a factor of 8 to spare,"
  , "    /// so the all-significant guarantee cannot fail."
  , "    public static func feasible(pixels: Int, k: Int) -> Bool {"
  , "        pixels >= minPopulation * k"
  , "    }"
  , "}"
  , ""
  , "/// Where a palette slot's population came from."
  , "public enum SixFourProvenance: String, Sendable, Codable, CaseIterable {"
  , "    case extracted   // a genuine cluster mode (count ≥ minPopulation)"
  , "    case split       // a sub-mode created to reach K (count ≥ minPopulation)"
  , "    case degenerate  // could not be backed by minPopulation pixels — unreachable on the SixFour shape"
  , "}"
  , ""
  , "/// One palette slot as a statistical cell: centroid, per-axis std-dev"
  , "/// (√ of the OKLab covariance diagonal), population, and provenance."
  , "/// The OKLab range it owns is `mean ± confidenceZ · stdDev`."
  , "public struct SixFourSignificantCell: Sendable {"
  , "    public let mean: SIMD3<Float>"
  , "    public let stdDev: SIMD3<Float>"
  , "    public let count: Int"
  , "    public let provenance: SixFourProvenance"
  , ""
  , "    public init(mean: SIMD3<Float>, stdDev: SIMD3<Float>, count: Int, provenance: SixFourProvenance) {"
  , "        self.mean = mean; self.stdDev = stdDev; self.count = count; self.provenance = provenance"
  , "    }"
  , ""
  , "    /// Lower corner of the α-confidence range box."
  , "    public var rangeLo: SIMD3<Float> { mean - Float(SixFourSignificance.confidenceZ) * stdDev }"
  , "    /// Upper corner of the α-confidence range box."
  , "    public var rangeHi: SIMD3<Float> { mean + Float(SixFourSignificance.confidenceZ) * stdDev }"
  , "    /// Significant ⇔ backed by ≥ minPopulation pixels (not an outlier)."
  , "    public var isSignificant: Bool { count >= SixFourSignificance.minPopulation }"
  , "}"
  , ""
  , "/// `SignificantVoxelVolume` brand: a `CompleteVoxelVolume` (every frame"
  , "/// surjective onto all K slots) in which, additionally, every palette"
  , "/// slot of every frame is statistically significant — backed by"
  , "/// `≥ minPopulation` pixels (so none is a donated outlier) — with exact"
  , "/// per-frame mass conservation. The per-frame `cells` carry the OKLab"
  , "/// ranges. Constructed only by `init?`, which performs the O(T·K) scan;"
  , "/// the brand cannot be forged. The GIF encoder consumes `.complete`."
  , "///"
  , "/// Laws (cross-reference SixFour.Spec.Significance):"
  , "///   * Def 22 MassConservation — Σ count = pixelsPerFrame, per frame."
  , "///   * Def 23 AllSignificant   — every slot count ≥ minPopulation."
  , "///   * Thm 7 NoOutlier         — significance is population, never a count-1 slot."
  , "public struct SignificantVoxelVolume: Sendable {"
  , "    public let complete: CompleteVoxelVolume"
  , "    /// `cells[f]`: the K palette cells of frame f, in slot order."
  , "    public let cells: [[SixFourSignificantCell]]"
  , ""
  , "    public init?(complete: CompleteVoxelVolume, cells: [[SixFourSignificantCell]]) {"
  , "        guard cells.count == SixFourShape.T else { return nil }"
  , "        for frame in cells {"
  , "            guard frame.count == SixFourShape.K else { return nil }"
  , "            var mass = 0"
  , "            for c in frame {"
  , "                guard c.isSignificant else { return nil }   // no outlier slots"
  , "                mass += c.count"
  , "            }"
  , "            guard mass == SixFourShape.pixelsPerFrame else { return nil }"
  , "        }"
  , "        self.complete = complete"
  , "        self.cells = cells"
  , "    }"
  , ""
  , "    /// The wire-relevant per-frame index frames (delegated to the brand"
  , "    /// the encoder already accepts)."
  , "    public var frames: [[UInt8]] { complete.frames }"
  , "}"
  ]

-- | Generate @NetContract.swift@.
emitNetContract :: Text
emitNetContract = T.unlines
  [ "// GENERATED by sixfour-spec / Codegen.Swift — do not edit by hand."
  , "// Source of truth: ~/SixFour/spec/src/SixFour/Spec/Net.hs"
  , "// Regenerate with: cabal run spec-codegen"
  , ""
  , "import Foundation"
  , ""
  , "/// Candidate NN slot identifiers. Currently only `.metric` exists;"
  , "/// other slots return when their trainers + tests ship."
  , "public enum SixFourNetSlot: String, CaseIterable, Codable, Sendable {"
  , "    case metric = \"metric\""
  , "}"
  , ""
  , "/// I/O dimensions for each slot, mirrored from the Haskell spec."
  , "public enum SixFourNetIO {"
  , "    public struct Spec: Sendable {"
  , "        public let inputDim: Int"
  , "        public let outputDim: Int"
  , "        public let description: String"
  , "    }"
  , emitSlotSpec "metric" slotMetricDims
  , ""
  , "    /// The metric organ ships as the 6 upper-triangle floats of the"
  , "    /// 3x3 PSD matrix M = L Lᵀ produced by trainer/train_metric.py."
  , "    public static let metricPSDUpperTriangleCount: Int = "
      <> tshow metricPSDUpperTriangleCount
  , "}"
  ]

emitSlotSpec :: Text -> NetIO -> Text
emitSlotSpec nm io = T.unlines
  [ "    public static let " <> nm <> ": Spec = Spec("
  , "        inputDim: "    <> tshow (netInputDim io) <> ","
  , "        outputDim: "   <> tshow (netOutputDim io) <> ","
  , "        description: \"" <> T.pack (netDescription io) <> "\""
  , "    )"
  ]

tshow :: Show a => a -> Text
tshow = T.pack . show

-- | Emit a Double as a Swift Float literal with full precision.
tshowF :: Double -> Text
tshowF x = T.pack (show x)

-- | Generate @HybridContract.swift@. Adds:
--
--   * 'SixFourHybridShape'   — KTrunk, KDelta, sum sanity
--   * 'SixFourHybridParams'  — runtime knobs (tauPresence, epsTrunk, deltaSnapMargin)
--   * 'SixFourHybridSlot'    — Trunk(Int)/Delta(Int) provenance enum
--   * Three witness protocols (SurjectiveTrunk, SurjectiveDeltaPerFrame, TemporalStable)
--   * STBN3DMaskLoader — reads the precomputed mask from the app bundle
--
-- The constants are bit-mirrored from "SixFour.Spec.Hybrid.Shape"; the
-- emitted laws-doc lists each algebraic obligation by name so that on-
-- device implementations cannot drift from the spec.
emitHybridContract :: Text
emitHybridContract = T.unlines
  [ "// GENERATED by sixfour-spec / Codegen.Swift — do not edit by hand."
  , "// Source of truth: ~/SixFour/spec/src/SixFour/Spec/Hybrid/*.hs"
  , "// Regenerate with: cabal run spec-codegen"
  , ""
  , "import Foundation"
  , "import simd"
  , ""
  , "/// Compile-time split of the SixFour palette into trunk + delta."
  , "/// Trunk slots live in [0, KTrunk); delta slots live in [KTrunk, K)."
  , "public enum SixFourHybridShape {"
  , "    public static let KTrunk: Int = " <> tshow kTrunkVal
  , "    public static let KDelta: Int = " <> tshow kDeltaVal
  , "    /// Sanity: KTrunk + KDelta must equal SixFourShape.K (256)."
  , "    public static var paletteSumIsLegal: Bool {"
  , "        KTrunk + KDelta == SixFourShape.K"
  , "    }"
  , "}"
  , ""
  , "/// Runtime knobs for the hybrid pipeline. Defaults are mirrored"
  , "/// from `SixFour.Spec.Hybrid.Shape`; tweaking on-device should"
  , "/// stay within the documented ranges."
  , "public enum SixFourHybridParams {"
  , "    /// Min fraction of frames a color must appear in (within `epsTrunk`)"
  , "    /// to be promoted into the trunk. Range: 0.10 ... 0.95."
  , "    public static let tauPresence: Double = "
      <> tshowF (unTauPresence defaultTauPresence)
  , "    /// OKLab ΔE clustering radius for trunk extraction. Range: 0.005 ... 0.05."
  , "    public static let epsTrunk: Double = "
      <> tshowF (unEpsTrunk defaultEpsTrunk)
  , "    /// Route to trunk if dist(c, trunk) ≤ margin · dist(c, delta)."
  , "    /// Range: 1.0 ... 2.0. Higher = more trunk = better temporal coherence."
  , "    public static let deltaSnapMargin: Double = "
      <> tshowF (unDeltaSnapMargin defaultDeltaSnapMargin)
  , "}"
  , ""
  , "/// Provenance tag for one resolved palette index. Trunk(i) means"
  , "/// the on-disk byte is `i`; Delta(j) means it is `KTrunk + j`."
  , "public enum SixFourHybridSlot: Equatable, Hashable, Sendable {"
  , "    case trunk(Int)"
  , "    case delta(Int)"
  , ""
  , "    public init(byte: UInt8) {"
  , "        let i = Int(byte)"
  , "        if i < SixFourHybridShape.KTrunk { self = .trunk(i) }"
  , "        else { self = .delta(i - SixFourHybridShape.KTrunk) }"
  , "    }"
  , ""
  , "    public var byte: UInt8 {"
  , "        switch self {"
  , "        case .trunk(let i): return UInt8(i)"
  , "        case .delta(let j): return UInt8(SixFourHybridShape.KTrunk + j)"
  , "        }"
  , "    }"
  , "}"
  , ""
  , "/// Three unforgeable witnesses on a hybrid index stream. Constructed"
  , "/// only by `make(checking:)` which performs the relevant O(T·H·W)"
  , "/// scan. Downstream code may trust each invariant for free."
  , "///"
  , "/// Laws (cross-reference SixFour.Spec.Hybrid.Laws):"
  , "///   * SurjectiveTrunk         — every trunk slot used somewhere in the cube."
  , "///   * SurjectiveDeltaPerFrame — every delta slot used in its own frame."
  , "///   * TemporalStable          — voxels whose source is constant across t map to a single trunk index."
  , "public struct SurjectiveTrunkWitness: Sendable {"
  , "    public let indices: [UInt8]"
  , "    public init?(checking xs: [UInt8]) {"
  , "        let kT = SixFourHybridShape.KTrunk"
  , "        var seen = Set<UInt8>(); seen.reserveCapacity(kT)"
  , "        for b in xs where Int(b) < kT { seen.insert(b) }"
  , "        guard seen.count == kT else { return nil }"
  , "        self.indices = xs"
  , "    }"
  , "}"
  , ""
  , "public struct SurjectiveDeltaPerFrameWitness: Sendable {"
  , "    public let indices: [UInt8]"
  , "    public init?(checking xs: [UInt8]) {"
  , "        let kT = SixFourHybridShape.KTrunk"
  , "        let kD = SixFourHybridShape.KDelta"
  , "        let perFrame = SixFourShape.H * SixFourShape.W"
  , "        guard xs.count == SixFourShape.T * perFrame else { return nil }"
  , "        for f in 0..<SixFourShape.T {"
  , "            var seen = Set<UInt8>(); seen.reserveCapacity(kD)"
  , "            let base = f * perFrame"
  , "            for i in 0..<perFrame {"
  , "                let b = xs[base + i]"
  , "                if Int(b) >= kT { seen.insert(UInt8(Int(b) - kT)) }"
  , "            }"
  , "            guard seen.count == kD else { return nil }"
  , "        }"
  , "        self.indices = xs"
  , "    }"
  , "}"
  , ""
  , "public struct TemporalStableWitness: Sendable {"
  , "    public let indices: [UInt8]"
  , "    /// `staticSite(y, x)` returns true for sites whose source RGB"
  , "    /// is constant within the caller's chosen tolerance across all"
  , "    /// T frames. The witness checks each such site only references"
  , "    /// trunk slots."
  , "    public init?(checking xs: [UInt8], staticSite: (Int, Int) -> Bool) {"
  , "        let kT = SixFourHybridShape.KTrunk"
  , "        let H = SixFourShape.H"
  , "        let W = SixFourShape.W"
  , "        let T = SixFourShape.T"
  , "        guard xs.count == T * H * W else { return nil }"
  , "        for y in 0..<H { for x in 0..<W where staticSite(y, x) {"
  , "            for f in 0..<T {"
  , "                if Int(xs[(f * H + y) * W + x]) >= kT { return nil }"
  , "            }"
  , "        } }"
  , "        self.indices = xs"
  , "    }"
  , "}"
  , ""
  , "/// Loader for the precomputed scalar 3D blue-noise mask."
  , "///"
  , "/// The bit-exact ground truth is `SixFour.Spec.Hybrid.STBN3D`'s"
  , "/// `generateSTBN3D @8 @8 @8`, written to `Resources/stbn3d-8.bin`"
  , "/// (512 bytes). `loadTiled` tiles that 8³ pattern toroidally to"
  , "/// produce the full 64³ mask. The tile uses toroidal distance"
  , "/// during generation, so the tiling is mathematically clean: no"
  , "/// edge discontinuities, only a soft 8-voxel periodic structure."
  , "/// Upgrading to a true 64³ mask requires an FFT-based void filter"
  , "/// (O(n log n) per swap) and is tracked as TR-1 in the plan file."
  , "public enum STBN3DMaskLoader {"
  , "    /// Returns the raw 8³ tile (512 bytes) loaded from the bundle."
  , "    public static func loadTile(bundle: Bundle = .main) -> [UInt8]? {"
  , "        guard let url = bundle.url(forResource: \"stbn3d-8\","
  , "                                    withExtension: \"bin\"),"
  , "              let data = try? Data(contentsOf: url),"
  , "              data.count == 8 * 8 * 8"
  , "        else { return nil }"
  , "        return Array(data)"
  , "    }"
  , ""
  , "    /// Returns the full 64³ mask, produced by tiling the 8³ tile"
  , "    /// 8 × 8 × 8 times along (t, y, x)."
  , "    public static func loadTiled(bundle: Bundle = .main) -> [UInt8]? {"
  , "        guard let tile = loadTile(bundle: bundle) else { return nil }"
  , "        let T = SixFourShape.T"
  , "        let H = SixFourShape.H"
  , "        let W = SixFourShape.W"
  , "        var out = [UInt8](repeating: 0, count: T * H * W)"
  , "        for f in 0..<T { for y in 0..<H { for x in 0..<W {"
  , "            out[(f * H + y) * W + x] = tile[((f % 8) * 8 + (y % 8)) * 8 + (x % 8)]"
  , "        } } }"
  , "        return out"
  , "    }"
  , "}"
  ]
