{- |
Module      : SixFour.Codegen.VoxelReduce
Description : Emit VoxelReduceGolden.swift — the byte-exact gate for the VoxelReduce Swift port.

The hand-written Swift port @VoxelReduce@ mirrors 'SixFour.Spec.VoxelReduce' (the joint
spatio-temporal @(2×2)×(2×2)→1@ reduction @64³ ↔ 16³@), itself a composition of
'SixFour.Spec.CubeLadder' (spatial) and 'SixFour.Spec.TemporalLoop' (temporal). Because the
reduction is integer-exact (Q16, floor division), the golden is plain Swift @Int@ literals — no
tolerance — and @VoxelReduceGoldenTests@ must reproduce the substrate EXACTLY. Pins the
COMPOSITION ORDER (spatial-then-temporal) cross-language; the round-trip is also tested in Swift.

Fixture: the same fixed 4³ cube @Properties.VoxelReduce@ pins (side=4, frames=4), reduced one
level (the @64³→16³@ ×2 step, here at side 4 / 4 frames).
-}
module SixFour.Codegen.VoxelReduce
  ( emitVoxelReduceGolden
  ) where

import qualified Data.Text as T
import           Data.Text (Text)

import SixFour.Spec.VoxelReduce (voxelReduce, vrSubstrate)

-- | The fixed 4³ cube — identical to @Properties.VoxelReduce.goldenCube@ (side=4, frames=4).
goldenCube :: [[(Int, Int, Int)]]
goldenCube =
  [ [ ( (i * 7 + f * 13) `mod` 200 - 100
      , (i * 5 + f * 3 ) `mod` 200 - 100
      , (i * 11 + f * 2) `mod` 200 - 100 )
    | i <- [0 .. 15] ]
  | f <- [0 .. 3] ]

-- | Flatten a cube (frame-major, position, then l\/a\/b) to a single @[Int]@.
flatCube :: [[(Int, Int, Int)]] -> [Int]
flatCube cube = concat [ [a, b, c] | frame <- cube, (a, b, c) <- frame ]

-- | Emit the Swift golden-vector fixture for the joint spatio-temporal reduction.
emitVoxelReduceGolden :: Text
emitVoxelReduceGolden = T.unlines
  [ "// GENERATED by sixfour-spec / Codegen.VoxelReduce — do not edit by hand."
  , "// Regenerate with: cabal run spec-codegen."
  , "//"
  , "// Byte-exact golden for the joint spatio-temporal (2x2)x(2x2)->1 reduction"
  , "// (SixFour.Spec.VoxelReduce). Q16 integers, no tolerance; the Swift VoxelReduce"
  , "// port must reproduce the substrate EXACTLY (pins the spatial-then-temporal order)."
  , ""
  , "enum VoxelReduceGolden {"
  , "    static let levels = 1"
  , "    static let side = 4"
  , "    static let frames = 4"
  , ""
  , "    /// The fixed 4x4x4 cube, flattened frame-major, position, then (l,a,b)."
  , "    static let cubeFlat: [Int] = " <> intArr (flatCube goldenCube)
  , ""
  , "    /// voxelReduce 1 4 cube: the reduced substrate, flattened frame'-major, position, (l,a,b)."
  , "    static let substrateFlat: [Int] = " <> intArr (flatCube substrate)
  , "}"
  ]
  where
    substrate = vrSubstrate (voxelReduce 1 4 goldenCube)

intArr :: [Int] -> Text
intArr xs = "[" <> T.intercalate ", " (map (T.pack . show) xs) <> "]"
