{-# LANGUAGE DataKinds #-}
{-# LANGUAGE TypeApplications #-}
{-# LANGUAGE ScopedTypeVariables #-}
{- |
Tests for the statistically-calibrated GIF generator ("SixFour.Gen.*"):

  * __golden__       — the §8 'descriptor' of a bit-exact synth stack matches the
                       Rust @analysis-core@ oracle (cross-language correctness).
  * __realizer__     — every realized frame sums to 4096, floors at 2, and forms
                       a 'CompleteVoxelVolume' / 'SignificantVoxelVolume'.
  * __targeting__    — 'populationsForEntropySixFour' hits the requested H(w).
  * __roundtrip__    — encode∘decode preserves indices exactly, so the H(w)
                       entropy trajectory survives losslessly.
-}
module Main (main) where

import           Test.Tasty
import           Test.Tasty.QuickCheck as QC
import           Data.Maybe          (isJust, fromJust)
import qualified Data.Vector         as V
import qualified Data.Vector.Unboxed as U

import SixFour.Spec.Shape   (T, H, W, K, kVal)
import SixFour.Spec.Cyclic  ( SinkhornParams (..), descriptor
                            , paletteEntropy, CyclicStack (..) )
import SixFour.Spec.Indices ( IndexTensor (..), withCompleteVoxelVolume
                            , mkIndexTensor, mkCompleteVoxelVolume )

import SixFour.Gen.Synth    (SynthParams (..), defaultSynthParams, synthStack)
import SixFour.Gen.Realize  (Realized (..), realize, quantizeWeights, proveSignificant)
import SixFour.Gen.Stats    (populationsForEntropySixFour)
import SixFour.Gen.GifWire  (encodeVolume, defaultFps)
import SixFour.Gen.GifDecode (decodeGif, decodedIndices, dgFrames, dfIndices)
import SixFour.Gen.AxisInput (frameToGMM, decodedGifToTokenSet)
import SixFour.Spec.GMM      (poolGMM, totalWeight)
import SixFour.Spec.LookNetE (gmmTokenSetSize)

main :: IO ()
main = defaultMain $ testGroup "spec-gen / stats"
  [ goldenTests, realizerTests, targetingTests, roundTripTests, axisInputTests ]

-- ---------------------------------------------------------------------------
-- Golden cross-check vs the Rust §8 oracle (studio/analysis-core, cyclic.rs)
-- Generated by: cargo test -p analysis-core print_synth_golden -- --nocapture
-- ---------------------------------------------------------------------------

goldenParams :: SynthParams
goldenParams = SynthParams
  { nClusters = 3, spread = 0.06, drift = 0.18, gamut = 0.8
  , concSkew = 1.0, popDrift = 0.5, seed = 42 }

-- Rust uses Params { eps = 0.1, iters = 20 }; match it for the cross-check.
goldenSink :: SinkhornParams
goldenSink = SinkhornParams { spEpsilon = 0.1, spIterCount = 20, spKMeansIts = 10 }

goldenDescriptor :: [Double]
goldenDescriptor =
  [ 1.6151134625800043, 0.06123241494686771, -7.636037463964857, 0.6340668806259018
  , 0.21359638907158254, 0.026699548633947818, 3.151418632203691, 1.2001279836818401
  , 1.473733866806888, 1.4971354133234476, -1.0675119595625815, 0.9166601661646859
  , 0.4120346778272635, 0.08267781931630015, 0.005000882008849558, 0.0005732416951844809 ]

goldenTests :: TestTree
goldenTests = testGroup "golden (Rust oracle)"
  -- Tolerance 1e-5: every component matches to ~1e-13 EXCEPT the holonomy
  -- defect (idx 11), whose 64-fold product of Sinkhorn-derived row-stochastic
  -- maps accumulates cross-language pow/exp divergence (~5e-6). The `Bures`
  -- golden, also iterative, uses 1e-4 for the same reason.
  [ QC.testProperty "descriptor matches Rust within 1e-5" $ once $
      let hs    = V.toList (descriptor goldenSink (synthStack @8 @12 goldenParams))
          delta = maximum (zipWith (\a b -> abs (a - b)) hs goldenDescriptor)
      in counterexample ("max |Δ| = " ++ show delta ++ "\nhaskell = " ++ show hs) (delta < 1e-5)
  ]

-- ---------------------------------------------------------------------------
-- Realizer
-- ---------------------------------------------------------------------------

realizerTests :: TestTree
realizerTests = testGroup "realizer"
  [ QC.testProperty "quantizeWeights sums to budget, floors honoured" $ \(xs :: [Double]) ->
      let ws  = V.fromList (1 : map (abs . (+ 0.01)) (take 255 (xs ++ repeat 1)))  -- 256 positive
          cs  = quantizeWeights 4096 2 ws
      in sum cs === 4096 .&&. property (all (>= 2) cs) .&&. length cs === 256
  , QC.testProperty "realize ⇒ CompleteVoxelVolume + ≥2 floor + significant" $ once $
      let rz = fromJust (realize @T @H @W @K (synthStack @T @K defaultSynthParams))
          idx = withCompleteVoxelVolume (rzVolume rz) (\(IndexTensor v) -> U.toList v)
          perFrameOK = all frameComplete [ take 4096 (drop (f * 4096) idx) | f <- [0 .. 63] ]
          frameComplete fr = length (dedupCount fr) == kVal
      in property (perFrameOK && isJust (proveSignificant rz))
  ]
  where
    dedupCount = foldr (\x acc -> if x `elem` acc then acc else x : acc) []

-- ---------------------------------------------------------------------------
-- Exact entropy targeting
-- ---------------------------------------------------------------------------

targetingTests :: TestTree
targetingTests = testGroup "entropy targeting"
  [ QC.testProperty ("H(w) target hit within 0.1 for " ++ show h) $ once $
      let pops     = populationsForEntropySixFour h
          achieved = paletteEntropy (V.fromList (map fromIntegral pops))
      in counterexample ("target=" ++ show h ++ " achieved=" ++ show achieved)
                        (abs (achieved - h) < 0.1 && sum pops == 4096 && all (>= 2) pops)
  | h <- [1.0, 2.0, 3.0, 4.0, 5.0] ]

-- ---------------------------------------------------------------------------
-- Lossless entropy round-trip through the GIF
-- ---------------------------------------------------------------------------

roundTripTests :: TestTree
roundTripTests = testGroup "lossless round-trip"
  [ QC.testProperty "indices + H(w) trajectory survive encode∘decode" $ once $
      let stk      = synthStack @T @K defaultSynthParams { seed = 5 }
          rz       = fromJust (realize @T @H @W @K stk)
          srcStack = rzStack rz
          palettes = map fst (V.toList (unStack srcStack))
          bytes    = either (error "encode") id
                       (encodeVolume defaultFps Nothing (rzVolume rz) palettes)
          dg       = either (error "decode") id (decodeGif bytes)
          srcIdx   = withCompleteVoxelVolume (rzVolume rz) (\(IndexTensor v) -> U.toList v)
          hwSrc    = [ paletteEntropy w | (_, w) <- V.toList (unStack srcStack) ]
          hwDec    = [ paletteEntropy (hist (dfIndices fr)) | fr <- dgFrames dg ]
      in (decodedIndices dg == srcIdx) .&&. (hwDec === hwSrc)
  ]
  where
    hist idx = V.accum (+) (V.replicate kVal 0) [ (i, 1 :: Double) | i <- idx ]

-- ---------------------------------------------------------------------------
-- GIF → GMM-token bridge (AxisInput): a decoded GIF IS the look-NN input
-- ---------------------------------------------------------------------------

axisInputTests :: TestTree
axisInputTests = testGroup "GIF → GMM-token bridge (AxisInput)"
  [ QC.testProperty "decoded GIF → pooled GmmTokenSet: |frames|·K tokens, Σw = 1" $ once $
      let stk      = synthStack @T @K defaultSynthParams { seed = 9 }
          rz       = fromJust (realize @T @H @W @K stk)
          palettes = map fst (V.toList (unStack (rzStack rz)))
          bytes    = either (error "encode") id
                       (encodeVolume defaultFps Nothing (rzVolume rz) palettes)
          dg       = either (error "decode") id (decodeGif bytes)
          gmm      = poolGMM (map frameToGMM (dgFrames dg))
          mts      = decodedGifToTokenSet dg
          expected = length (dgFrames dg) * kVal
      in isJust mts
         .&&. (gmmTokenSetSize (fromJust mts) === expected)
         .&&. (length gmm === expected)
         .&&. counterexample ("Σw = " ++ show (totalWeight gmm))
                (abs (totalWeight gmm - 1) < 1e-9)
  ]
