//  S4PropertyTests.swift
//  PROPERTY-BASED TESTING for the Swift kernel core — INSTITUTED 2026-07-06.
//
//  Two layers, both seeded and fully reproducible:
//
//  1. SPEC-ORACLE REPLAY: `spec-fixtures` emits pbt_golden.json — case FAMILIES
//     (256 rgbt quads, 64 haar streams, 32 cube grids, 24 quantize frames)
//     generated by a pinned SplitMix64 stream and answered by the Haskell spec
//     oracles (RGBTLift.liftQuad, TemporalLoop.haarSplitTime,
//     CubeLadder.liftLevel, QuantFixed.quantizeFrameQ16). The kernels must
//     reproduce every output byte-exactly. This upgrades the one-case goldens
//     to property-based differential testing with the spec as the oracle.
//
//  2. ALGEBRAIC LAWS on random inputs (no oracle needed — the law IS the
//     expectation): octant lift∘unlift identity + the K∘S section law,
//     pooling transitivity (sums compose), GIF assemble→decode→reassemble
//     round-trip + byte-determinism, the ladder delay law over its whole
//     domain, and quantize nearest-assignment soundness.
//
//  Failures print the harness seed + case index — rerunning reproduces the
//  exact case (SplitMix64 is pinned; there is no time or global randomness).

import XCTest
@testable import SixFour

/// Deterministic test-local SplitMix64 (same constants as KernelsSynth's PRNG).
private struct SplitMix64 {
    var state: UInt64
    init(seed: UInt64) { state = seed }
    mutating func next() -> UInt64 {
        state &+= 0x9E37_79B9_7F4A_7C15
        var z = state
        z = (z ^ (z >> 30)) &* 0xBF58_476D_1CE4_E5B9
        z = (z ^ (z >> 27)) &* 0x94D0_49BB_1331_11EB
        return z ^ (z >> 31)
    }
    /// Uniform-ish Int in [lo, hi] (mod bias accepted, mirrors the spec emitter).
    mutating func int(_ lo: Int, _ hi: Int) -> Int {
        lo + Int(next() % UInt64(hi - lo + 1))
    }
    mutating func i32(_ lo: Int32, _ hi: Int32) -> Int32 {
        Int32(int(Int(lo), Int(hi)))
    }
    mutating func byte() -> UInt8 { UInt8(truncatingIfNeeded: next()) }
}

final class S4PropertyTests: XCTestCase {

    // MARK: - Fixture plumbing (mirrors the ZigPort* convention)

    private static let repoRoot: URL = URL(fileURLWithPath: #filePath)
        .deletingLastPathComponent()   // SixFourTests/
        .deletingLastPathComponent()   // repo root

    private func loadPbt() throws -> [String: Any] {
        let url = Self.repoRoot.appendingPathComponent("trainer/out/pbt_golden.json")
        guard let data = try? Data(contentsOf: url) else {
            throw XCTSkip("pbt_golden.json absent — run `cd spec && cabal run spec-fixtures`")
        }
        return try XCTUnwrap(JSONSerialization.jsonObject(with: data) as? [String: Any])
    }

    private func intArray(_ v: Any?) throws -> [Int32] {
        try XCTUnwrap(v as? [Any]).map { Int32(truncatingIfNeeded: ($0 as! NSNumber).int64Value) }
    }
    private func tripleArray(_ v: Any?) throws -> [Int32] {
        var out = [Int32]()
        for t in try XCTUnwrap(v as? [Any]) {
            out.append(contentsOf: try intArray(t))
        }
        return out
    }

    // MARK: - 1. Spec-oracle replay (the property fixtures)

    /// 256 random quads: the kernel matches the spec oracle, and unlift inverts.
    func testPbtRgbtQuadFamilyMatchesSpecAndRoundTrips() throws {
        let cases = try XCTUnwrap((try loadPbt())["rgbt_quad"] as? [[String: Any]])
        XCTAssertEqual(cases.count, 256)
        for (i, c) in cases.enumerated() {
            let inp = try intArray(c["in"]), expect = try intArray(c["out"])
            var out = [Int32](repeating: 0, count: 4)
            var back = [Int32](repeating: 0, count: 4)
            XCTAssertEqual(s4_rgbt_lift_quad(inp, &out), 0, "case \(i)")
            XCTAssertEqual(out, expect, "rgbt case \(i): kernel != spec oracle")
            XCTAssertEqual(s4_rgbt_unlift_quad(out, &back), 0, "case \(i)")
            XCTAssertEqual(back, inp, "rgbt case \(i): unlift∘lift != id")
        }
    }

    /// 64 random 8-frame streams: split matches the oracle, join inverts.
    func testPbtHaarTimeFamilyMatchesSpecAndRoundTrips() throws {
        let cases = try XCTUnwrap((try loadPbt())["haar_time"] as? [[String: Any]])
        XCTAssertEqual(cases.count, 64)
        for (i, c) in cases.enumerated() {
            let frames = try tripleArray(c["frames"])
            let expLow = try tripleArray(c["low"]), expHigh = try tripleArray(c["high"])
            var low  = [Int32](repeating: 0, count: expLow.count)
            var high = [Int32](repeating: 0, count: expHigh.count)
            XCTAssertEqual(s4_haar_split_level(8, frames, &low, &high), 0, "case \(i)")
            XCTAssertEqual(low, expLow, "haar case \(i): low != spec")
            XCTAssertEqual(high, expHigh, "haar case \(i): high != spec")
            var joined = [Int32](repeating: 0, count: frames.count)
            XCTAssertEqual(s4_haar_join_level(4, 4, low, high, &joined), 0, "case \(i)")
            XCTAssertEqual(joined, frames, "haar case \(i): join∘split != id")
        }
    }

    /// 32 random side-8 grids: one up-rung matches the oracle, unlift inverts.
    func testPbtCubeLevelFamilyMatchesSpecAndRoundTrips() throws {
        let cases = try XCTUnwrap((try loadPbt())["cube_level"] as? [[String: Any]])
        XCTAssertEqual(cases.count, 32)
        for (i, c) in cases.enumerated() {
            let grid = try intArray(c["grid"])
            let expCoarse = try intArray(c["coarse"]), expDets = try tripleArray(c["details"])
            var coarse = [Int32](repeating: 0, count: expCoarse.count)
            var dets   = [Int32](repeating: 0, count: expDets.count)
            XCTAssertEqual(s4_cube_lift_level(8, grid, &coarse, &dets), 0, "case \(i)")
            XCTAssertEqual(coarse, expCoarse, "cube case \(i): coarse != spec")
            XCTAssertEqual(dets, expDets, "cube case \(i): details != spec")
            var back = [Int32](repeating: 0, count: grid.count)
            XCTAssertEqual(s4_cube_unlift_level(4, coarse, dets, &back), 0, "case \(i)")
            XCTAssertEqual(back, grid, "cube case \(i): unlift∘lift != id")
        }
    }

    /// 24 random frames through maximin+Lloyd: centroids AND assignment match
    /// the spec byte-exactly (tie-breaking included — that is the point).
    func testPbtQuantizeFamilyMatchesSpec() throws {
        let cases = try XCTUnwrap((try loadPbt())["quant"] as? [[String: Any]])
        XCTAssertEqual(cases.count, 24)
        let p = 64, k = 8
        for (i, c) in cases.enumerated() {
            let pixels = try tripleArray(c["pixels"])
            let iters = Int32(truncatingIfNeeded: (c["iters"] as! NSNumber).int64Value)
            let expCentroids = try tripleArray(c["centroids"])
            let expIndices = try intArray(c["indices"]).map { UInt8($0) }
            var centroids = [Int32](repeating: 0, count: k * 3)
            var indices = [UInt8](repeating: 0, count: p)
            let scratchBytes = p * 8 + 3 * k * 8 + k * 4
            var scratch = [Int64](repeating: 0, count: (scratchBytes + 7) / 8)
            let rc = scratch.withUnsafeMutableBufferPointer { sp in
                s4_quantize_frame(pixels, Int32(p), Int32(k), iters,
                                  &centroids, &indices,
                                  UnsafeMutableRawPointer(sp.baseAddress), scratchBytes)
            }
            XCTAssertEqual(rc, 0, "quant case \(i)")
            XCTAssertEqual(centroids, expCentroids, "quant case \(i): centroids != spec")
            XCTAssertEqual(indices, expIndices, "quant case \(i): indices != spec")
        }
    }

    // MARK: - 2. Algebraic laws on random inputs

    /// Octant SES on 500 random cells: lift∘unlift == id (the I splitting is
    /// exact), and the K∘S section law — unlifting a pure coarse value and
    /// re-lifting recovers it with zero detail.
    func testOctantLiftUnliftIdentityAndSectionLaw() {
        var rng = SplitMix64(seed: 0xC0FF_EE00_0C7A_0001)
        for i in 0..<500 {
            var cell = [Int32](repeating: 0, count: 8)
            for j in 0..<8 { cell[j] = rng.i32(-100_000, 100_000) }
            var lifted = [Int32](repeating: 0, count: 8)
            var back = [Int32](repeating: 0, count: 8)
            XCTAssertEqual(s4_octant_lift(cell, &lifted), 0, "case \(i)")
            XCTAssertEqual(s4_octant_unlift(lifted, &back), 0, "case \(i)")
            XCTAssertEqual(back, cell, "octant case \(i): unlift∘lift != id (I must be exact)")

            // K∘S = id on the coarse: a zero-detail band unlifts to a flat cell
            // whose re-lift has the same coarse and all-zero detail.
            let coarse = rng.i32(-100_000, 100_000)
            var band: [Int32] = [coarse, 0, 0, 0, 0, 0, 0, 0]
            var flat = [Int32](repeating: 0, count: 8)
            XCTAssertEqual(s4_octant_unlift(band, &flat), 0)
            XCTAssertEqual(s4_octant_lift(flat, &band), 0)
            XCTAssertEqual(band[0], coarse, "case \(i): K(S(c)) != c")
            XCTAssertEqual(Array(band[1...]), [Int32](repeating: 0, count: 7),
                           "case \(i): the zero section grew detail")
        }
    }

    /// Sums compose: pooling 64→16 directly equals pooling 64→32 then 32→16,
    /// on 20 random images — the transitive pyramid carrier as a property.
    func testPoolingTransitivityOnRandomImages() {
        var rng = SplitMix64(seed: 0xC0FF_EE00_0C7A_0002)
        for i in 0..<20 {
            var rgb = [UInt8](repeating: 0, count: 64 * 64 * 3)
            for j in rgb.indices { rgb[j] = rng.byte() }
            var direct16 = [UInt64](repeating: 0, count: 16 * 16 * 3)
            var sums32 = [UInt64](repeating: 0, count: 32 * 32 * 3)
            XCTAssertEqual(s4_pool_sums_srgb8(rgb, 64, 16, &direct16), 0, "case \(i)")
            XCTAssertEqual(s4_pool_sums_srgb8(rgb, 64, 32, &sums32), 0, "case \(i)")
            let via32 = ColorHead.poolSpatial2(sums32, side: 32)
            XCTAssertEqual(via32, direct16, "case \(i): 64→32→16 != 64→16 (sums must compose)")
        }
    }

    /// GIF89a codec on 32 random bursts: assemble→decode recovers indices,
    /// palettes, and shape exactly; reassembling the decode is byte-identical
    /// (the codec is a bijection onto its range, deterministically).
    func testGifAssembleDecodeRoundTripAndDeterminism() {
        var rng = SplitMix64(seed: 0xC0FF_EE00_0C7A_0003)
        for i in 0..<32 {
            let side = 8, k = [4, 16, 256][i % 3], fc = rng.int(2, 4)
            var indices = [UInt8](repeating: 0, count: fc * side * side)
            for j in indices.indices { indices[j] = UInt8(rng.int(0, k - 1)) }
            var palettes = [UInt8](repeating: 0, count: fc * k * 3)
            for j in palettes.indices { palettes[j] = rng.byte() }

            var gif = [UInt8](repeating: 0, count: 1 << 16)
            var gifLen = 0
            XCTAssertEqual(s4_gif_assemble(indices, palettes, Int32(fc), Int32(side), Int32(k),
                                           5, nil, 0, &gif, gif.count, &gifLen), 0, "case \(i)")

            var outIdx = [UInt8](repeating: 0, count: indices.count)
            var outPal = [UInt8](repeating: 0, count: palettes.count)
            var dfc: Int32 = 0, dside: Int32 = 0, dk: Int32 = 0
            let scratchBytes = s4_gif_decode_scratch_bytes(gifLen)
            var scratch = [UInt8](repeating: 0, count: scratchBytes)
            let rc = scratch.withUnsafeMutableBufferPointer { sp in
                s4_gif_decode(gif, gifLen, &outIdx, &outPal, &dfc, &dside, &dk,
                              UnsafeMutableRawPointer(sp.baseAddress), scratchBytes)
            }
            XCTAssertEqual(rc, 0, "case \(i)")
            XCTAssertEqual((dfc, dside, dk).0, Int32(fc), "case \(i)")
            XCTAssertEqual(dside, Int32(side), "case \(i)")
            XCTAssertEqual(dk, Int32(k), "case \(i)")
            XCTAssertEqual(outIdx, indices, "case \(i): decoded indices differ")
            XCTAssertEqual(outPal, palettes, "case \(i): decoded palettes differ")

            var gif2 = [UInt8](repeating: 0, count: gif.count)
            var gifLen2 = 0
            XCTAssertEqual(s4_gif_assemble(outIdx, outPal, dfc, dside, dk,
                                           5, nil, 0, &gif2, gif2.count, &gifLen2), 0)
            XCTAssertEqual(Array(gif[..<gifLen]), Array(gif2[..<gifLen2]),
                           "case \(i): reassembly not byte-identical (determinism broken)")
        }
    }

    /// The ladder delay law over its WHOLE domain: representable exactly when
    /// side divides 320 cs, and then delay·side == 320 — every side, not one.
    func testLadderDelayLawOverFullDomain() {
        for side in Int32(1)...320 {
            let d = s4_ladder_delay_cs(side)
            if 320 % side == 0 {
                XCTAssertEqual(d * side, 320, "side \(side): delay·side != window")
            } else {
                XCTAssertEqual(d, -2, "side \(side): must refuse (NOT_REPRESENTABLE)")
            }
        }
        XCTAssertEqual(s4_ladder_delay_cs(0), -1)
        XCTAssertEqual(s4_ladder_delay_cs(-64), -1)
    }

    /// Quantize soundness on 16 random frames: every pixel's assigned centroid
    /// is no farther than ANY other centroid (the assignment really is
    /// nearest-by-Q16-distance, ties notwithstanding).
    func testQuantizeAssignmentIsNearest() {
        var rng = SplitMix64(seed: 0xC0FF_EE00_0C7A_0004)
        let p = 64, k = 8
        for i in 0..<16 {
            var pixels = [Int32](repeating: 0, count: p * 3)
            for j in pixels.indices { pixels[j] = rng.i32(0, 65535) }
            var centroids = [Int32](repeating: 0, count: k * 3)
            var indices = [UInt8](repeating: 0, count: p)
            let scratchBytes = p * 8 + 3 * k * 8 + k * 4
            var scratch = [Int64](repeating: 0, count: (scratchBytes + 7) / 8)
            let rc = scratch.withUnsafeMutableBufferPointer { sp in
                s4_quantize_frame(pixels, Int32(p), Int32(k), 2,
                                  &centroids, &indices,
                                  UnsafeMutableRawPointer(sp.baseAddress), scratchBytes)
            }
            XCTAssertEqual(rc, 0, "case \(i)")
            func dist2(_ px: Int, _ c: Int) -> Int64 {
                var s: Int64 = 0
                for ch in 0..<3 {
                    let d = Int64(pixels[px * 3 + ch]) - Int64(centroids[c * 3 + ch])
                    s += d * d
                }
                return s
            }
            for px in 0..<p {
                let assigned = dist2(px, Int(indices[px]))
                for c in 0..<k {
                    XCTAssertLessThanOrEqual(assigned, dist2(px, c),
                        "case \(i) pixel \(px): assigned centroid \(indices[px]) farther than \(c)")
                }
            }
        }
    }
}
