"""STRICT-ENFORCEMENT GATE: the trainer's RGB->OKLab is THE canonical transform.

The frozen JEPA encoder must see the IDENTICAL integer voxel at train and capture
time. There is exactly one RGB->OKLab: the owned Zig kernel (integer matmul +
icbrtQ16), golden-pinned to the Haskell oracle (trainer/out/color_golden.json,
generated by `cabal run spec-fixtures`). This test makes the trainer a
golden-gated consumer of that ONE transform, so re-introducing a numpy `np.cbrt`
reimplementation (which rounds differently, causing train/capture input skew)
fails here.

Run: cd trainer && .venv/bin/python test_color_canonical.py
"""
from __future__ import annotations

import json
import pathlib

import numpy as np

from native_kernels import linear_to_oklab_q16, srgb8_to_oklab_q16

_GOLDEN = pathlib.Path(__file__).parent / "out" / "color_golden.json"


def _load_golden():
    return json.loads(_GOLDEN.read_text())


def test_forward_oklab_matches_haskell_oracle_byte_exact():
    """The Zig forward transform the trainer uses == the Haskell oracle golden, byte
    for byte. This is the cross-language pin: trainer == Zig == Haskell."""
    g = _load_golden()
    lin = np.array([e["lin"] for e in g["linear_to_oklab"]], dtype=np.int32)
    want = np.array([e["oklab"] for e in g["linear_to_oklab"]], dtype=np.int32)
    got = linear_to_oklab_q16(lin)
    assert np.array_equal(got, want), (
        f"trainer RGB->OKLab drifted from the Haskell oracle golden; "
        f"max |diff| = {int(np.abs(got - want).max())} Q16 LSBs"
    )


def test_numpy_cbrt_would_fail_the_golden():
    """TEETH: a numpy np.cbrt reimplementation does NOT reproduce the golden, which is
    exactly why it is forbidden. If this ever passes, the kernel has become a plain
    float transform and the integer determinism guarantee is gone."""
    g = _load_golden()
    q16 = float(g["q16_one"])
    lin = np.array([e["lin"] for e in g["linear_to_oklab"]], dtype=np.float64) / q16
    r, gg, b = lin[:, 0], lin[:, 1], lin[:, 2]
    l = 0.4122214708 * r + 0.5363325363 * gg + 0.0514459929 * b
    m = 0.2119034982 * r + 0.6806995451 * gg + 0.1073969566 * b
    s = 0.0883024619 * r + 0.2817188376 * gg + 0.6299787005 * b
    l_, m_, s_ = np.cbrt(l), np.cbrt(m), np.cbrt(s)
    L = 0.2104542553 * l_ + 0.7936177850 * m_ - 0.0040720468 * s_
    A = 1.9779984951 * l_ - 2.4285922050 * m_ + 0.4505937099 * s_
    B = 0.0259040371 * l_ + 0.7827717662 * m_ - 0.8086757660 * s_
    numpy_q16 = np.rint(np.stack([L, A, B], axis=-1) * q16).astype(np.int64)
    want = np.array([e["oklab"] for e in g["linear_to_oklab"]], dtype=np.int64)
    assert not np.array_equal(numpy_q16, want), (
        "numpy np.cbrt unexpectedly matched the golden; the forbidden-path teeth are gone"
    )


def test_srgb8_path_is_deterministic_and_in_range():
    """The 8-bit GIF training entry (srgb8_to_oklab_q16) is deterministic and L>=0
    (OKLab L is non-negative for valid colour)."""
    cols = np.array([[0, 0, 0], [255, 255, 255], [37, 113, 200]], dtype=np.uint8)
    a = srgb8_to_oklab_q16(cols)
    b = srgb8_to_oklab_q16(cols)
    assert np.array_equal(a, b)
    assert (a[:, 0] >= 0).all()


def test_train_metric_has_no_numpy_oklab():
    """Regression guard: train_metric.py must not call np.cbrt (the divergent path)."""
    src = (pathlib.Path(__file__).parent / "train_metric.py").read_text()
    # allow the word inside comments explaining the ban, but not an actual call
    assert "np.cbrt(" not in src, "train_metric.py reintroduced a numpy np.cbrt OKLab path"
    assert "srgb8_to_oklab_q16" in src, "train_metric.py no longer routes through the canonical kernel"


if __name__ == "__main__":
    failures = 0
    for name, fn in sorted(globals().items()):
        if name.startswith("test_") and callable(fn):
            try:
                fn()
                print(f"PASS {name}")
            except AssertionError as e:
                failures += 1
                print(f"FAIL {name}: {e}")
    raise SystemExit(failures)
