#!/usr/bin/env python3
"""Embed the Haskell GIF goldens as base64 in a Swift test fixture.

Matches the project's embedded-golden convention (SixFour/Generated/*Golden.swift)
instead of bundling resources (avoids the simctl folder-reference gotcha). The
golden bytes themselves come from spec-fixtures (cabal run spec-fixtures); this only
re-embeds them. Regenerate after the goldens change.
"""
import base64, pathlib
root = pathlib.Path(__file__).resolve().parent.parent
out = root / "trainer" / "out"
gif = (out / "golden.gif").read_bytes()
halfs = (out / "golden_input.halfs").read_bytes()
assert len(halfs) == 2 * 32 * 32 * 3 * 2, f"unexpected halfs size {len(halfs)}"
swift = f'''// GENERATED by scripts/embed-gif-golden.py from trainer/out/golden.gif +
// golden_input.halfs (the Haskell spec-fixtures GIF golden). Embedded base64 rather
// than bundled as a resource, matching the SixFour/Generated/*Golden.swift convention.
// DO NOT EDIT; regenerate: python3 scripts/embed-gif-golden.py
import Foundation

enum GifGoldenFixture {{
    /// The byte-exact GIF the Haskell driver emits for the fixed FC=2, SD=32, K=256,
    /// FloydSteinberg (dither mode 0), Lloyd=15 burst ({len(gif)} bytes).
    static let goldenGif = Data(base64Encoded: "{base64.b64encode(gif).decode()}")!

    /// The linear-sRGB Float16 input burst ({len(halfs)} bytes = 2*32*32*3 LE halfs).
    private static let goldenInputHalfsRaw = Data(base64Encoded: "{base64.b64encode(halfs).decode()}")!

    /// Input as [UInt16] IEEE-half bit-patterns (little-endian), ready for encodeBurst.
    static var goldenInputHalfs: [UInt16] {{
        let d = goldenInputHalfsRaw
        return stride(from: 0, to: d.count, by: 2).map {{ UInt16(d[$0]) | (UInt16(d[$0 + 1]) << 8) }}
    }}

    // The exact params the golden was produced with (authoritative: gif_fixture_test.zig).
    static let frameCount: Int32 = 2
    static let side: Int32 = 32
    static let k: Int32 = 256
    static let lloydIters: Int32 = 15
    static let frameDelayCentiseconds: UInt16 = 5
}}
'''
(root / "SixFourTests" / "GifGoldenFixture.swift").write_text(swift)
print(f"wrote SixFourTests/GifGoldenFixture.swift (gif={len(gif)}B, halfs={len(halfs)}B)")
