#!/usr/bin/env python3
"""Generate SixFour/Kernels/KernelsLUTData.swift from the literal LUT binaries.

The Zig core @embedFile'd five .bin goldens; the Swift core embeds the same
bytes as base64 string literals (strings compile fast where huge array
literals do not), decoded once on first touch. Byte-identity with the .bin
files is asserted by ZigPortColorTests.

Run from repo root: python3 scripts/gen-lut-swift.py
"""
import base64
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
SRC = ROOT / "SixFour" / "Kernels" / "LUTGoldens"
OUT = ROOT / "SixFour" / "Kernels" / "KernelsLUTData.swift"

LUTS = [
    ("s4LutGamma", "gamma_lut.bin"),
    ("s4LutSrgbLinear", "srgb_linear_lut.bin"),
    ("s4LutLog3g10Decode", "log3g10_decode_lut.bin"),
    ("s4LutFilmicTonemap", "filmic_tonemap_lut.bin"),
    ("s4LutSrgbEncode", "srgb_encode_lut.bin"),
]

CHUNK = 8000  # chars per string literal line (compiler-friendly)

def emit(name: str, data: bytes) -> str:
    b64 = base64.b64encode(data).decode("ascii")
    chunks = [b64[i:i + CHUNK] for i in range(0, len(b64), CHUNK)]
    lines = ",\n".join(f'    "{c}"' for c in chunks)
    return (
        f"/// {name}: {len(data)} bytes, byte-identical to SixFour/Kernels/LUTGoldens/{dict(LUTS_BY)[name]}.\n"
        f"public let {name}: [UInt8] = s4DecodeLut([\n{lines}\n], expectedCount: {len(data)})\n"
    )

LUTS_BY = [(n, f) for n, f in LUTS]

def main() -> None:
    parts = [
        "//  KernelsLUTData.swift\n"
        "//  GENERATED by scripts/gen-lut-swift.py from the literal LUT goldens\n"
        "//  (formerly @embedFile'd by Native/src/kernels.zig). Do not hand-edit;\n"
        "//  regenerate if the .bin goldens ever change (they are goldens: they\n"
        "//  should not).\n\n"
        "import Foundation\n\n"
        "/// Decode the base64 chunks into the LUT bytes. Traps on corruption —\n"
        "/// an embedded golden that fails to decode is a build defect, not a\n"
        "/// runtime condition.\n"
        "func s4DecodeLut(_ chunks: [String], expectedCount: Int) -> [UInt8] {\n"
        "    guard let data = Data(base64Encoded: chunks.joined()) else {\n"
        "        fatalError(\"KernelsLUTData: corrupt embedded LUT\")\n"
        "    }\n"
        "    precondition(data.count == expectedCount, \"KernelsLUTData: LUT size mismatch\")\n"
        "    return [UInt8](data)\n"
        "}\n"
    ]
    for name, fname in LUTS:
        data = (SRC / fname).read_bytes()
        parts.append(emit(name, data))
    OUT.write_text("\n".join(parts))
    print(f"wrote {OUT} ({OUT.stat().st_size} bytes)")

if __name__ == "__main__":
    main()
