{- |
Module      : SixFour.Spec.RootLatticeDetail
Description : The "1 coarse + (b-1) detail" band structure is the root lattice A_{b-1}. The idealized linear octant lift is the split short exact sequence 0 → A_{b-1} → ℤ^b → ℤ → 0: the coarse is the rank-1 sum functional Σ : ℤ^b ↠ ℤ (the DC quotient) and the DETAIL lives in its kernel A_{b-1} = {x : Σ x_i = 0}, the mean-free root lattice generated by the b-1 simple roots e_i − e_{i+1}. This makes the band count b-1 an ALGEBRAIC IDENTITY (= rank A_{b-1}), not a coincidence, and generalizes the b=8 octant (7 = rank A_7) to any branching b.

Discrete geometry + algebraic number theory: A_{b-1} is the densest lattice sphere packing in
dimension b-1 (b ≤ 9), and its coefficient ring is ℤ (no field — byte-exactness forbids dividing
by the non-units of ℤ). The wavelet-lifting "vanishing-moment / zero-integral detail" condition IS
membership in A_{b-1} = ker Σ. See "SixFour.Spec.HierarchicalDelta" (the carrier algebra) and
"SixFour.Spec.EncoderFrozen" (the shipped lift).

HONEST BOUNDARY (the analysis flagged this, so it is doc not law): the SHIPPED reversible lift
(@kernels.zig sLift@, @divFloor@) is a reversible SET-bijection of ℤ^b, NOT a ℤ-module
homomorphism (additivity fails under flooring). This module gates the IDEALIZED LINEAR Haar
skeleton — the lattice structure that makes the band count a theorem — not the floored kernel's
arithmetic. The two agree on the structure (which bands exist), not on per-element additivity.
-}
-- COMPARTMENT: PURE-SPEC-WALL | tag:none
module SixFour.Spec.RootLatticeDetail
  ( -- * The split exact sequence  0 → A_{b-1} → ℤ^b → ℤ → 0
    sumFunctional
  , inA
  , numDetailBands
    -- * The root lattice A_{b-1} = ℤ-span of the simple roots e_i − e_{i+1}
  , simpleRoots
  , rootCoords
  , fromRootCoords
    -- * The mean-free detail band as a TYPE (Σ = 0 by construction; constructor hidden)
  , MeanFree
  , unMeanFree
  , mkMeanFreeFromRootCoords
  , mkMeanFreeChecked
    -- * The idealized linear Haar detail (consecutive differences)
  , haarDetail
    -- * Laws
  , lawDetailIsMeanFree
  , lawBandCountEqualsRank
  , lawSimpleRootsAreMeanFree
  , lawNonRootNotInA
  , lawRootCoordsRoundTrip
  , lawDetailKernelIsConstants
  , lawOctantIsA7
  , lawMeanFreeIsSigmaZero
  ) where

-- | The coarse projection Σ : ℤ^b ↠ ℤ — the rank-1 sum quotient (the DC component).
sumFunctional :: [Integer] -> Integer
sumFunctional = sum

-- | Membership in the root lattice @A_{b-1} = ker Σ = {x : Σ x_i = 0}@ — the mean-free
-- (vanishing-zeroth-moment) detail subspace.
inA :: [Integer] -> Bool
inA = (== 0) . sumFunctional

-- | The number of detail bands at branching @b@: @b - 1 = rank A_{b-1}@ (= 7 for the b=8 octant).
numDetailBands :: Int -> Int
numDetailBands b = b - 1

-- | The @b-1@ simple roots of @A_{b-1}@: @e_i − e_{i+1}@ for @i = 0 .. b-2@. Each is mean-free,
-- and they ℤ-generate the whole root lattice.
simpleRoots :: Int -> [[Integer]]
simpleRoots b = [ root i | i <- [0 .. b - 2] ]
  where
    root i = [ coord i j | j <- [0 .. b - 1] ]
    coord i j
      | j == i     =  1
      | j == i + 1 = -1
      | otherwise  =  0

-- | The @b-1@ root coordinates of a vector: the prefix sums @c_i = Σ_{j≤i} x_j@, @i = 0 .. b-2@.
-- For a mean-free @x@ these are the integer coefficients in @x = Σ_i c_i · (e_i − e_{i+1})@.
rootCoords :: [Integer] -> [Integer]
rootCoords xs = take (length xs - 1) (scanl1 (+) xs)

-- | Rebuild a mean-free vector from its @b-1@ root coordinates: @x_k = c_k − c_{k-1}@ with the
-- boundary convention @c_{-1} = c_{b-1} = 0@ (the latter is @Σ x = 0@, i.e. membership in A).
fromRootCoords :: Int -> [Integer] -> [Integer]
fromRootCoords b cs = [ c k - c (k - 1) | k <- [0 .. b - 1] ]
  where
    c i | i < 0 || i >= b - 1 = 0
        | otherwise           = cs !! i

-- | The idealized linear Haar detail of @b@ voxels: the @b-1@ consecutive differences
-- @x_{i+1} − x_i@. Adding a constant to every voxel leaves it unchanged (the DC is in the kernel).
haarDetail :: [Integer] -> [Integer]
haarDetail xs = zipWith (-) (drop 1 xs) xs

-- ---------------------------------------------------------------------------
-- MeanFree: the detail band's Σ = 0 invariant, carried in the TYPE.
-- ---------------------------------------------------------------------------

-- | A detail vector with its mean-free invariant @Σ x_i = 0@ (membership in @A_{b-1} = ker Σ@)
-- carried in the TYPE, not re-checked at every call site. The constructor is HIDDEN: a 'MeanFree'
-- can be built ONLY via 'mkMeanFreeFromRootCoords' (always mean-free, by the root-coordinate chart)
-- or the checked 'mkMeanFreeChecked' guard. It can NEVER be built by subtracting a mean — that would
-- divide by @b@, a NON-UNIT of @ℤ@ (see "SixFour.Spec.RefinementSystem" @units@), and break
-- byte-exactness. This is Win C of the expressivity plan: make the mean-free property a type
-- invariant instead of the runtime obligation 'lawDetailIsMeanFree' re-establishes.
newtype MeanFree = MeanFree [Integer] deriving (Eq, Show)

-- | Read the underlying mean-free vector out of a 'MeanFree'.
unMeanFree :: MeanFree -> [Integer]
unMeanFree (MeanFree xs) = xs

-- | Build a 'MeanFree' from @b-1@ root coordinates via 'fromRootCoords' (consecutive subtraction
-- ONLY — no division). The result is ALWAYS in @A_{b-1}@ (@Σ = 0@), so this constructor is total and
-- cannot produce an invalid band. The canonical, byte-exact way to make a detail band.
mkMeanFreeFromRootCoords :: Int -> [Integer] -> MeanFree
mkMeanFreeFromRootCoords b cs = MeanFree (fromRootCoords b cs)

-- | Build a 'MeanFree' from an arbitrary vector, returning 'Nothing' unless it is ALREADY mean-free
-- ('inA'). The honest guard REFUSES non-mean-free input rather than silently projecting it onto the
-- kernel (projection would divide by @b@). So a value of type 'MeanFree' is a PROOF that @Σ = 0@.
mkMeanFreeChecked :: [Integer] -> Maybe MeanFree
mkMeanFreeChecked xs
  | inA xs    = Just (MeanFree xs)
  | otherwise = Nothing

-- ---------------------------------------------------------------------------
-- Laws (each FAILS if the lattice structure is violated — non-vacuous).
-- ---------------------------------------------------------------------------

-- | The simple-root reconstruction of any vector's mean-free part is mean-free: the rebuilt vector
-- @fromRootCoords b (rootCoords x)@ lies in @A_{b-1}@ (sum 0). Teeth: it equals @x@ exactly iff @x@
-- was already mean-free, so it certifies membership.
lawDetailIsMeanFree :: [Integer] -> Bool
lawDetailIsMeanFree xs =
  let b = length xs
  in b < 1 || inA (fromRootCoords b (rootCoords xs))

-- | The band count is an algebraic identity: @numDetailBands b == rank A_{b-1} == |simpleRoots b|@.
lawBandCountEqualsRank :: Int -> Bool
lawBandCountEqualsRank b0 =
  let b = 1 + (abs b0 `mod` 32)            -- a real branching b ∈ [1,32]
  in numDetailBands b == length (simpleRoots b)
     && numDetailBands b == b - 1
     && all ((== b) . length) (simpleRoots b)

-- | Every simple root is mean-free (lives in @A_{b-1}@). Teeth: @lawNonRootNotInA@.
lawSimpleRootsAreMeanFree :: Int -> Bool
lawSimpleRootsAreMeanFree b0 =
  let b = 2 + (abs b0 `mod` 31)            -- b ∈ [2,32] so there is ≥1 root
  in all inA (simpleRoots b)

-- | Teeth for the above: a standard basis vector @e_0 = [1,0,…]@ is NOT in @A_{b-1}@ (sum 1 ≠ 0).
lawNonRootNotInA :: Bool
lawNonRootNotInA = not (inA (1 : replicate 7 0))      -- e_0 in ℤ^8

-- | The @b-1@ root coordinates are a FAITHFUL chart of @A_{b-1}@: rebuilding from coordinates and
-- reading them back is the identity. This is the root-lattice generation theorem (A_{b-1} is the
-- free ℤ-module on the simple roots), made integer-exact. Teeth: a corrupted chart round-trips wrong.
lawRootCoordsRoundTrip :: [Integer] -> Bool
lawRootCoordsRoundTrip cs0 =
  let cs = cs0
      b  = length cs + 1
  in rootCoords (fromRootCoords b cs) == cs

-- | The kernel of the Haar detail is exactly the constants (the rank-1 DC line @ℤ·1@): adding a
-- constant @k@ to every voxel does not change the detail, and a non-constant change does. This is
-- the other half of the SES — detail captures precisely the mean-free A_{b-1} part.
lawDetailKernelIsConstants :: [Integer] -> Integer -> Bool
lawDetailKernelIsConstants xs k =
  haarDetail (map (+ k) xs) == haarDetail xs
  && (length xs < 2 || k == 0
      || haarDetail (bump xs) /= haarDetail xs)        -- a single-voxel (non-constant) bump shows
  where
    bump (y : ys) = (y + 1) : ys                       -- perturb only the first voxel
    bump []       = []

-- | The shipped b=8 octant: 7 detail bands == rank A_7, all mean-free, A_7 (densest packing in
-- dimension 7) is the lattice the octant lift's detail lives in.
lawOctantIsA7 :: Bool
lawOctantIsA7 =
     numDetailBands 8 == 7
  && length (simpleRoots 8) == 7
  && all inA (simpleRoots 8)
  && all ((== 8) . length) (simpleRoots 8)

-- | The 'MeanFree' invariant @Σ = 0@ holds BY CONSTRUCTION for both constructors: any root-coordinate
-- chart builds a mean-free band ('mkMeanFreeFromRootCoords' is total and sums to 0), the checked
-- guard accepts exactly the mean-free vectors, and a sum-1 vector is REFUSED ('Nothing'). This is the
-- law that lets the band's mean-freeness be a TYPE fact rather than a re-checked runtime obligation.
-- Teeth: a 'fromRootCoords' that introduced a non-zero sum, or a 'mkMeanFreeChecked' that admitted a
-- non-mean-free vector, fails.
lawMeanFreeIsSigmaZero :: [Integer] -> Bool
lawMeanFreeIsSigmaZero cs =
  let b       = length cs + 1
      built   = unMeanFree (mkMeanFreeFromRootCoords b cs)
      checked = mkMeanFreeChecked built
      refused = mkMeanFreeChecked (1 : replicate (length cs) 0)   -- Σ = 1 ≠ 0
  in sumFunctional built == 0
     && (case checked of Just mf -> sumFunctional (unMeanFree mf) == 0; Nothing -> False)
     && refused == Nothing
