{- |
Module      : SixFour.Spec.SigmaPairHead
Description : σ-pair-symmetric decoder — the structural answer the tensor finding demanded.

The (now-retired) @Quad4Fit@ tensor measurement showed that Quad4's 511-dim image
does NOT preferentially fit σ-symmetric palettes (median residual ≈ 6 % on
σ-symmetric synthetic palettes, indistinguishable from random palettes).
Free-parameter trees (binary or 4-ary) achieve σ-symmetric output only via a
learned loss — never structurally.

This module fixes that by inverting the construction: rather than emitting 256
free OKLab points and hoping they pair under σ, emit **128** OKLab points
\(c_0, \ldots, c_{127}\) and define the 256-leaf palette as the
σ-pair-interleaved list

    [c_0, σ(c_0), c_1, σ(c_1), …, c_{127}, σ(c_{127})]

Now the σ-pair structure is /algebraic/: every odd-indexed leaf is the σ
reflection of its even-indexed predecessor, /no matter what the 128 c_i are/.
The 128 c_i themselves are generated by a depth-7 binary Haar pyramid (the
existing 'SixFour.Spec.PairTree' machinery, instantiated at depth 7 → 128
leaves), so the genome has exactly 384 free reals:

    DOF  =  3 (root)  +  3 · (1 + 2 + 4 + … + 64)  =  3 · 128  =  384

This is exactly the dimension of the σ-symmetric palette subspace under the
canonical pair-interleaved ordering. The 'SigmaPairHead' design matrix
\(B \in \mathbb R^{768 \times 384}\) has full rank 384, so the image is the
ENTIRE σ-symmetric subspace — not a proper subset of it. Its residual on any
σ-symmetric palette is exactly zero; its residual on a random palette is the
σ-antisymmetric energy of that palette (a non-trivial fraction that
'Properties.SigmaPairHead' reports empirically).

This is the decoder Option 4 of the plan addendum was reaching for. The
choice "768 → 511 (Quad4) → 384 (SigmaPairHead)" is the dimensional
reduction the σ-symmetric constraint actually demands, not the 33 % that
Quad4's misnomered σ-equivariance promised.

Laws (see @Properties.SigmaPairHead@):
  * 'reconstructPaired' yields 256 leaves in σ-pair-interleaved order
    (algebraic, not learned).
  * The design matrix rank equals 384 (full rank).
  * 'sigmaPairResidual' is ≈ 0 on σ-symmetric synthetic palettes (by
    construction).
  * 'sigmaPairResidual' is substantially > 0 on random palettes — the
    contrast that proves the architecture is preferentially σ-aligned.
-}
-- COMPARTMENT: MLX-MODEL | tag:MacTag
module SixFour.Spec.SigmaPairHead
  ( -- * The σ-pair-paired tree
    SigmaPairTree(..)
  , sigmaPairDepth
  , sigmaPairInnerLeaves
  , sigmaPairLeaves
  , sigmaPairDegreesOfFreedom
  , sigmaPairWellFormed
    -- * Reconstruction + the forward analyser (the σ-pair genome's two directions)
  , reconstructPaired
  , analyzePaired
    -- * The σ-action on the output that makes the image σ-fixed (pointwise on the list)
  , sigmaSwapAndReflect
    -- * Laws (QuickCheck'd in Properties.SigmaPairHead)
  , lawAnalyzeReconstructPairedRoundTrip
  , lawAnalyzePairedProjectsToSigmaFixed
    -- * Linear-algebra form (tensor-level verification)
  , sigmaPairDesignMatrix
  , sigmaPairBasis
  , sigmaPairImageRank
  , sigmaPairResidual
  ) where

import qualified Data.Vector.Unboxed as U

import SixFour.Spec.Color       (OKLab(..))
import SixFour.Spec.LinAlg
import SixFour.Spec.PairTree    (HaarPalette(..), sigmaReflect)
import qualified SixFour.Spec.PairTree as PT
import SixFour.Spec.Quad4        (paletteToVec)

-- =============================================================================
-- The σ-pair-paired tree
-- =============================================================================

-- | A depth-7 binary Haar palette whose 128 leaves are the @c_i@ generators of
-- the σ-pair palette. The full 256-leaf palette is
-- @[c_0, σ(c_0), c_1, σ(c_1), …]@ (see 'reconstructPaired').
newtype SigmaPairTree = SigmaPairTree
  { unSigmaPairTree :: HaarPalette
  } deriving (Eq, Show)

-- | Depth of the underlying binary Haar tree (= 7 → 128 inner leaves).
sigmaPairDepth :: Int
sigmaPairDepth = 7

-- | Number of inner c_i generators (= 128 = 256 / 2).
sigmaPairInnerLeaves :: Int
sigmaPairInnerLeaves = 2 ^ sigmaPairDepth

-- | Number of palette leaves emitted (= 256).
sigmaPairLeaves :: Int
sigmaPairLeaves = 2 * sigmaPairInnerLeaves

-- | DOF: @3 (root) + 3·(1+2+4+…+64) = 3·128 = 384@.
sigmaPairDegreesOfFreedom :: Int
sigmaPairDegreesOfFreedom = 3 * sigmaPairInnerLeaves

-- | A well-formed 'SigmaPairTree' has exactly 'sigmaPairDepth' Haar levels
-- and the @PT.wellFormed@ shape for each level (@level i@ has @2^i@ offsets).
sigmaPairWellFormed :: SigmaPairTree -> Bool
sigmaPairWellFormed (SigmaPairTree hp) =
  length (PT.levels hp) == sigmaPairDepth && PT.wellFormed hp

-- =============================================================================
-- Reconstruction
-- =============================================================================

-- | Reconstruct the 256-leaf σ-pair palette from a 'SigmaPairTree'. Order:
-- @[c_0, σ(c_0), c_1, σ(c_1), …, c_{127}, σ(c_{127})]@.
reconstructPaired :: SigmaPairTree -> [OKLab]
reconstructPaired (SigmaPairTree hp) =
  concatMap (\c -> [c, sigmaReflect c]) (PT.reconstruct hp)

-- | The FORWARD σ-pair analyser — the left inverse of 'reconstructPaired'. The
-- 256-leaf palette is @[c_0, σ(c_0), c_1, σ(c_1), …]@, so the 128 @c_i@ generators
-- are exactly the even-indexed leaves; Haar-analyse them into the depth-7 tree.
--
-- On a σ-pair-interleaved palette this is an EXACT inverse
-- (@reconstructPaired ∘ analyzePaired = id@, ε in 'Double'). On an ARBITRARY
-- 256-leaf palette it is the PROJECTION onto the σ-pair subspace: the odd leaves
-- are discarded and regenerated as @σ(c_i)@, so the result is always σ-fixed
-- ('lawAnalyzePairedProjectsToSigmaFixed'). This is the forward direction the
-- branch-parameterized collapse needs for the @2⁸@ genome (the @4⁴@ genome's
-- forward map is 'SixFour.Spec.Quad4.quad4Analyze').
analyzePaired :: [OKLab] -> SigmaPairTree
analyzePaired = SigmaPairTree . PT.analyze . evens
  where
    evens (x : _ : rest) = x : evens rest
    evens [x]            = [x]
    evens []             = []

-- =============================================================================
-- The σ-action on the output (pointwise σ + swap adjacent pairs)
-- =============================================================================

-- | Pointwise σ-reflection followed by swapping adjacent pairs. On a
-- σ-pair-interleaved palette, this is the identity — that is the formal
-- statement that 'reconstructPaired''s image lies in the σ-symmetric
-- eigenspace under this lifted action.
sigmaSwapAndReflect :: [OKLab] -> [OKLab]
sigmaSwapAndReflect = swapPairs . map sigmaReflect
  where
    swapPairs (x : y : rest) = y : x : swapPairs rest
    swapPairs xs             = xs

-- =============================================================================
-- Linear-algebra form
-- =============================================================================

-- | Decode a 384-vector back into a depth-7 'HaarPalette'. Format:
-- @[root.L, root.a, root.b, level0_offset₀.L, level0_offset₀.a,
-- level0_offset₀.b, level1_offset₀.L, …]@ — root then per-level offsets,
-- 3 reals per OKLab.
haarPaletteFromVec :: U.Vector Double -> HaarPalette
haarPaletteFromVec v =
  let rt   = OKLab (v U.! 0) (v U.! 1) (v U.! 2)
      rest = U.toList (U.drop 3 v)
      lvls = unflatten rest [2 ^ i | i <- [0 .. sigmaPairDepth - 1]]
  in HaarPalette rt lvls
  where
    unflatten _  []     = []
    unflatten ys (n:ns) =
      let (now, rem') = splitAt (3 * n) ys
          row         = chunksOfOKLab now
      in row : unflatten rem' ns
    chunksOfOKLab (l : a : b : rs) = OKLab l a b : chunksOfOKLab rs
    chunksOfOKLab _                = []

-- | The 768 × 384 'SigmaPairHead' design matrix: column @j@ is the palette
-- obtained by setting the j-th genome coordinate to 1 and all others to 0.
sigmaPairDesignMatrix :: Matrix
sigmaPairDesignMatrix =
  case fromColumns 768
         [ reconstructAtBasis j
         | j <- [0 .. sigmaPairDegreesOfFreedom - 1] ] of
    Just m  -> m
    Nothing -> error "sigmaPairDesignMatrix: column length mismatch"
  where
    reconstructAtBasis j =
      let zeros  = U.replicate sigmaPairDegreesOfFreedom 0.0
          oneHot = zeros U.// [(j, 1.0)]
          hp     = haarPaletteFromVec oneHot
      in paletteToVec (reconstructPaired (SigmaPairTree hp))

-- | Orthonormal basis of @im(sigmaPairDesignMatrix)@ via Modified Gram-Schmidt.
-- CAF: computed once on first access.
sigmaPairBasis :: Matrix
sigmaPairBasis = fst (modifiedGramSchmidt 1e-9 sigmaPairDesignMatrix)

-- | Numerical rank — should be exactly 384 (the design matrix has no
-- redundant directions, and its image is exactly the σ-symmetric eigenspace).
sigmaPairImageRank :: Int
sigmaPairImageRank = matCols sigmaPairBasis

-- | Relative residual when projecting a target palette onto the σ-pair
-- subspace. Zero on σ-symmetric palettes (by construction); positive on
-- σ-asymmetric content (the irreducible loss the σ-pair architecture pays).
sigmaPairResidual :: [OKLab] -> Double
sigmaPairResidual leaves = residualFraction sigmaPairBasis (paletteToVec leaves)

-- =============================================================================
-- Laws for the forward analyser (QuickCheck'd in Properties.SigmaPairHead)
-- =============================================================================

-- | @analyzePaired ∘ reconstructPaired = id@ on the tree (within ε; the Haar
-- transform is exact in ℝ, ε-close in 'Double'). Pins that the forward analyser
-- recovers the genome the decoder emitted.
lawAnalyzeReconstructPairedRoundTrip :: Double -> SigmaPairTree -> Bool
lawAnalyzeReconstructPairedRoundTrip eps t =
  not (sigmaPairWellFormed t) ||
  haarClose eps (unSigmaPairTree (analyzePaired (reconstructPaired t))) (unSigmaPairTree t)

-- | For ANY 256-leaf palette, @reconstructPaired (analyzePaired leaves)@ lies in
-- the σ-symmetric subspace: @sigmaSwapAndReflect@ fixes it (within ε). This is the
-- formal statement that the forward analyser PROJECTS onto the σ-pair genome.
lawAnalyzePairedProjectsToSigmaFixed :: Double -> [OKLab] -> Bool
lawAnalyzePairedProjectsToSigmaFixed eps leaves =
  length leaves /= sigmaPairLeaves ||
  let pal = reconstructPaired (analyzePaired leaves)
  in and (zipWith (okClose eps) (sigmaSwapAndReflect pal) pal)

-- internal closeness (PairTree does not export these)
okClose :: Double -> OKLab -> OKLab -> Bool
okClose eps (OKLab a b c) (OKLab a' b' c') =
  abs (a - a') < eps && abs (b - b') < eps && abs (c - c') < eps

haarClose :: Double -> HaarPalette -> HaarPalette -> Bool
haarClose eps (HaarPalette r1 l1) (HaarPalette r2 l2) =
  okClose eps r1 r2 && length l1 == length l2 && and (zipWith levelClose l1 l2)
  where levelClose xs ys = length xs == length ys && and (zipWith (okClose eps) xs ys)
